### ISSUE TITLE
removing installGlobals leads to crash in dev

### ISSUE THREAD

**Issue by JustFly1984** [remix-run/remix#10269]
### Reproduction

As adviset in docs, I've removed installGlobals from vite config, and starting dev start crashing in runtime after browser makes first request.

```sh
3:36:05 PM [vite] Internal server error: Headers.set: ":method" is an invalid header name.
      at Object.webidl.errors.exception (node:internal/deps/undici/undici:3564:14)
      at Object.webidl.errors.invalidArgument (node:internal/deps/undici/undici:3575:28)
      at _Headers.set (node:internal/deps/undici/undici:8814:31)
      at fromNodeHeaders (/Users/user/projects/client/node_modules/.pnpm/@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_dyiyu57qvxnruishmq7l5zb5f4/node_modules/@remix-run/dev/dist/vite/node-adapter.js:30:17)
      at Object.fromNodeRequest (/Users/user/projects/client/node_modules/.pnpm/@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_dyiyu57qvxnruishmq7l5zb5f4/node_modules/@remix-run/dev/dist/vite/node-adapter.js:46:14)
      at /Users/user/projects/client/node_modules/.pnpm/@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_dyiyu57qvxnruishmq7l5zb5f4/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:65:37
3:36:05 PM [vite] Internal server error: Headers.set: ":method" is an invalid header name.
      at Object.webidl.errors.exception (node:internal/deps/undici/undici:3564:14)
      at Object.webidl.errors.invalidArgument (node:internal/deps/undici/undici:3575:28)
      at _Headers.set (node:internal/deps/undici/undici:8814:31)
      at fromNodeHeaders (/Users/user/projects/client/node_modules/.pnpm/@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_dyiyu57qvxnruishmq7l5zb5f4/node_modules/@remix-run/dev/dist/vite/node-adapter.js:30:17)
      at Object.fromNodeRequest (/Users/user/projects/client/node_modules/.pnpm/@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_dyiyu57qvxnruishmq7l5zb5f4/node_modules/@remix-run/dev/dist/vite/node-adapter.js:46:14)
      at /Users/user/projects/client/node_modules/.pnpm/@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_dyiyu57qvxnruishmq7l5zb5f4/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:65:37
      at processTicksAndRejections (node:internal/process/task_queues:105:5)
```

### System Info

```shell
System:
    OS: macOS 15.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 184.81 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 9.14.2 - /opt/homebrew/bin/pnpm
    bun: 1.1.36 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 131.0.6778.86
    Safari: 18.1
  npmPackages:
    @remix-run/cloudflare: 2.15.0 => 2.15.0 
    @remix-run/cloudflare-pages: 2.15.0 => 2.15.0 
    @remix-run/dev: 2.15.0 => 2.15.0 
    @remix-run/node: 2.15.0 => 2.15.0 
    @remix-run/react: 2.15.0 => 2.15.0 
    @remix-run/serve: 2.15.0 => 2.15.0 
    vite: 5.4.11 => 5.4.11
```

### Used Package Manager

pnpm

### Expected Behavior

Should not crash on dev. Please either remove advise from docs, or fix and release 2.15.1

### Actual Behavior

crashes on dev after removing installGlobals. stop crashing after revert.

**Comment by iwan-uschka** [comment]
I am not sure if it is also the reason that `Response.json` is not defined. Calling it in Node@20.13.0 directly works without any issues.

Context: according to https://remix.run/docs/en/2.13.1/guides/single-fetch#resource-routes ressource routes should use `Response.json` instead of `json` imported from `@remix-run/node`.

I am not able to update from Remix@v2 to ReactRouter@v7 (https://reactrouter.com/upgrading/remix).

**Comment by anhdd-kuro** [comment]
Same error if remove `installGlobals` or change to `installGlobals({ nativeFetch: true })`

**Comment by anhdd-kuro** [comment]
Ok in my case , https is the root cause this error
What evert I use ( vite-plugin-mkcert, mkcert ... ) , the same error occur
Dose anyone know how to fix it ?
Here is config files

``` ts
import { vitePlugin as remix } from "@remix-run/dev";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";
import tailwindcss from "@tailwindcss/vite";
import { createCA, createCert } from "mkcert";

const ca = await createCA({
  organization: "company",
  countryCode: "JP",
  state: "state",
  locality: "locality",
  validity: 365,
});

const cert = await createCert({
  ca,
  domains: ["127.0.0.1", "localhost"],
  validity: 365,
});

// ! v3に公式に更新したら以下を削除
declare module "@remix-run/server-runtime" {
  // or cloudflare, deno, etc.
  interface Future {
    v3_singleFetch: true;
  }
}

// console.log(process.env)

export default defineConfig({
  plugins: [
    remix({
      ignoredRouteFiles: ["**/.*"],
      future: {
        v3_relativeSplatPath: true,
        v3_singleFetch: true,
      },
    }),
    tsconfigPaths(),
    tailwindcss(),
  ],
  server: {
    port: Number(process.env.PORT || 3456),
    // https://remix.run/docs/en/main/guides/local-tls
    https: cert,
  },
  build: {
    assetsInlineLimit: 0,
  },
});
```

or

``` ts
import { vitePlugin as remix } from "@remix-run/dev";
import { installGlobals } from "@remix-run/node";
import { defineConfig } from "vite";
import mkcert from "vite-plugin-mkcert";
import tsconfigPaths from "vite-tsconfig-paths";
import tailwindcss from "@tailwindcss/vite";

installGlobals();

// console.log(process.env)

export default defineConfig({
  plugins: [
    remix({
      ignoredRouteFiles: ["**/.*"],
      future: {
        v3_relativeSplatPath: true,
      },
    }),
    tsconfigPaths(),
    mkcert(),
    tailwindcss(),
  ],
  server: {
    port: Number(process.env.PORT || 3000),
  },
  ssr: {
  },
  build: {
    assetsInlineLimit: 0,
  },
});

```

**Comment by albertzarifa** [comment]
I was having the same issue after adding , Vite's plugin `vitejs/plugin-basic-ssl` to run HTTPS instead of HTTP in my local development environment.

The only workaround that made it work for me was setting server.proxy to an empty object in Vite’s defineConfig(). Here’s what worked for me:

```
export default defineConfig({
  server: {
    host: "0.0.0.0", // required to work in a devcontainer
    port: 3000, // required to work in a devcontainer
    proxy: {},
  },
  plugins: [ basicSsl()],
});
```

Hope that helps!
