### ISSUE TITLE
Error: Unable to decode turbo-stream response from URL

### ISSUE THREAD

**Issue by zackperdue** [remix-run/remix#10348]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-gpjalp3q?file=app%2Froutes%2Fitems.%24slug.tsx

### System Info

```shell
System:
    OS: macOS 15.1.1
    CPU: (14) arm64 Apple M3 Max
    Memory: 107.41 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.15.3 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 131.0.6778.140
    Safari: 18.1.1
```

### Used Package Manager

npm

### Expected Behavior

When loading this route the page should load correctly and page should be visible.

### Actual Behavior

```When loading route, I get an error Error: Unable to decode turbo-stream response from URL: https://website.com/items/one.data
at cu (https://website.com/assets/components-BetrtQQV.js:112:2432)
    at async ih (https://website.com/assets/components-BetrtQQV.js:112:1485)
    at async xn (https://website.com/assets/index-uys_nLR2.js:11:4625)
    at async ke (https://website.com/assets/index-uys_nLR2.js:10:29048)
    at async Nt (https://website.com/assets/index-uys_nLR2.js:10:29667)
    at async _r (https://website.com/assets/index-uys_nLR2.js:10:23174)
    at async Pe (https://website.com/assets/index-uys_nLR2.js:10:20554)
    at async Object.It [as navigate] (https://website.com/assets/index-uys_nLR2.js:10:18894)
```

**Comment by clowNay** [comment]
I'm seeing the same issue here, does it have something to with basename/base? It seems for me that it is the request to .data that fails, because it hits an invalid URL.

In my example I have base of `/dev/foo/bar/` and if I load a routing link that points to path `/` it seems to try to fetch loaderData from `/dev/foo/bar.data` which to me seems a bit incorrect.

**Comment by zackperdue** [comment]
> I'm seeing the same issue here, does it have something to with basename/base? It seems to me that it is the request to .data that fails, because it hits an invalid URL.
> 
> 
> 
> In my example I have base of `/dev/foo/bar/` and if I load a routing link that points to path `/` it seems to try to fetch loaderData from `/dev/foo/bar.data` which to me seems a bit incorrect.

Yeah I'm not too sure. I'm hosting on lambdas but I'm not sure if that matters. The page never loads no matter how I navigate to it whether with a link or directly. The weird thing is it only happens when it's deployed and not in dev mode on my local machine.

**Comment by zackperdue** [comment]
I also have to very similar routes. One works but the other doesn't and gets this turbo stream error.

working:
route: _public.items.$slug.tsx
url: website.com/items/some-thing

not working:
route: _public.some-items.$slug.tsx
url: website.com/some-items/another-thing

it seems as though its breaking when hyphens are included in the path as well as a route parameter.

**Comment by brophdawg11** [comment]
That reproduction is working fine for me?  Is this still an issue?

**Comment by mcfriend99** [comment]
> I also have two very similar routes. One works but the other doesn't and gets this turbo stream error.
> 
> working: route: _public.items.$slug.tsx url: website.com/items/some-thing
> 
> not working: route: _public.some-items.$slug.tsx url: website.com/some-items/another-thing
> 
> I also tried something just to see, and this worked: route: _public.someItems.$slug.tsx url: website.com/someItems/another-thing
> 
> it seems as though its breaking when hyphens are included in the path as well as a route parameter.

I'm having the same problem but I don't have any hyphens anywhere. And it happens for all routes that uses a fetcher, submit, and/or navigate and the occurrence is somehow not predictable. I mean the app can go days without it happening, but some days, it just happens a lot and sometimes, it happens a few times to a few users.

I think its tied to the mechanism remix uses to fetch data from the server/loader. Problem is that there is no way to ignore useFetcher and useSubmit errors in remixjs that I have found.

**Comment by aaronadamsCA** [comment]
> I mean the app can go days without it happening, but some days, it just happens a lot and sometimes, it happens a few times to a few users.

Unfortunately I can corroborate this today. I'm using the same route pretty heavily today, and it's giving this error intermittently, quite frequently, for no apparent reason. A retry/refresh works fine.

We have all future flags enabled, and the route in question uses `useNavigate`.

**Comment by einarq** [comment]
I'm experiencing the same issue here, and it seems one of my express middlewares was returning a 401, which was then indeed clobbered on the RR7 side.

Would be good if the error message was a bit more informative.

**Comment by liucka04** [comment]
I am also having the same problem. I have wrapped all route in `Response.json` both internal and external and the issue is still happening. I'm monitoring my users and every 200-300th request fails. Any recommendations from @brophdawg11 here? Here's my package JSON:

```
{
  "name": "my-app",
  "private": true,
  "scripts": {
    ... 
  },
  "type": "module",
  "engines": {
    "node": "^18.20 || ^20.10 || >=21.0.0"
  },
  "dependencies": {
    "@mdxeditor/editor": "^3.23.2",
    "@neondatabase/serverless": "^0.10.4",
    "@prisma/client": "^6.2.1",
    "@remix-run/dev": "^2.15.0",
    "@remix-run/fs-routes": "^2.15.0",
    "@remix-run/node": "^2.15.0",
    "@remix-run/react": "^2.15.0",
    "@remix-run/serve": "^2.15.0",
    "@sentry/remix": "^9",
    "@sentry/vite-plugin": "^3.2.2",
    "@shopify/app-bridge-react": "^4.1.6",
    "@shopify/polaris": "^12.27.0",
    "@shopify/shopify-app-remix": "^3.7.0",
    "@shopify/shopify-app-session-storage-prisma": "^6.0.0",
    "@types/mixpanel-browser": "^2.51.0",
    "classnames": "^2.5.1",
    "dotenv": "^16.4.7",
    "drizzle-orm": "^0.39.3",
    "isbot": "^5.1.0",
    "jotai": "^2.12.1",
    "mixpanel-browser": "^2.61.0",
    "openai": "^4.85.3",
    "prisma": "^6.2.1",
    "radash": "^12.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.54.2",
    "remix-utils": "^8.1.0",
    "vite-tsconfig-paths": "^5.0.1"
  },
  "devDependencies": {
    "@remix-run/eslint-config": "^2.16.2",
    "@remix-run/route-config": "^2.16.2",
    "@shopify/api-codegen-preset": "^1.1.1",
    "@shopify/shopify-app-session-storage-drizzle": "^2.0.13",
    "@types/eslint": "^9.6.1",
    "@types/node": "^22.2.0",
    "@types/react": "^18.2.31",
    "@types/react-dom": "^18.2.14",
    "@types/showdown": "^2.0.6",
    "@types/turndown": "^5.0.5",
    "@vercel/remix": "^2.15.3",
    "autoprefixer": "^10.4.17",
    "drizzle-kit": "^0.30.4",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^10.0.1",
    "postcss": "^8.4.35",
    "prettier": "^3.2.4",
    "showdown": "^2.1.0",
    "tailwindcss": "^3.4.1",
    "turndown": "^7.2.0",
    "typescript": "^5.2.2",
    "vite": "^6.2.2"
  },
  "workspaces": {
    "packages": [
      "extensions/*"
    ]
  },
  "trustedDependencies": [
    "@shopify/plugin-cloudflare"
  ],
  "resolutions": {
    "@graphql-tools/url-loader": "8.0.16"
  },
  "overrides": {
    "@graphql-tools/url-loader": "8.0.16"
  },
}
```

I'm running on vercel's severless functions Node v22

**Comment by shmuli-a0** [comment]
I seem to get this particularly on Safari on my iPhone. Using RRv7 hosted on Cloudflare Workers. Can't seem to repro on my laptop though

**Comment by shmuli9** [comment]
I seem to get this particularly on Safari on my iPhone. Using RRv7 hosted on Cloudflare Workers. Can't seem to repro on my laptop though

**Comment by ahmetcanaksu** [comment]
> I encountered a similar issue — in my case, it occurred when my CloudFront firewall blocked the request.

Same here :/
