### ISSUE TITLE
[Bug]: remix-serve build fails with Cannot find module './env' on 1.1.0 

### ISSUE THREAD

**Issue by noahpryor** [remix-run/remix#1128]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [X] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.0

### What version of Node are you using? Minimum supported version is 14.

v16.13.1

### Steps to Reproduce

No changes necessary to the test case starter [stackblitz](https://stackblitz.com/github/remix-run/remix/tree/dev/examples/basic?file=package.json)

1. `npm install`
2. `npm run build`
3. `npm run start`

You should now

### Expected Behavior

The compiled production build to run 

### Actual Behavior

This error is thrown 

```bash
❯ npm run start
$ remix-serve build
Error: Cannot find module './env'
Require stack:
- /home/projects/aonizyvpa.github/node_modules/@remix-run/serve/cli.js
    at Function.Module._resolveFilename (https://aonizyvpa--github.w.staticblitz.com/blitz.a3339ebb87d0fe73c7995fe67420660e0dc95de2.js:6:165845)
    at Function.Module._load (https://aonizyvpa--github.w.staticblitz.com/blitz.a3339ebb87d0fe73c7995fe67420660e0dc95de2.js:6:163423)
    at Module.require (https://aonizyvpa--github.w.staticblitz.com/blitz.a3339ebb87d0fe73c7995fe67420660e0dc95de2.js:6:166635)
    at i (https://aonizyvpa--github.w.staticblitz.com/blitz.a3339ebb87d0fe73c7995fe67420660e0dc95de2.js:6:427483)
    at _0x4bca57 (https://aonizyvpa--github.w.staticblitz.com/blitz.a3339ebb87d0fe73c7995fe67420660e0dc95de2.js:11:113768)
    at Object.eval (/home/projects/aonizyvpa.github/node_modules/@remix-run/serve/cli.js:13:1)
    at Object.function (https://aonizyvpa--github.w.staticblitz.com/blitz.a3339ebb87d0fe73c7995fe67420660e0dc95de2.js:11:114121)
    at Module._compile (https://aonizyvpa--github.w.staticblitz.com/blitz.a3339ebb87d0fe73c7995fe67420660e0dc95de2.js:6:167880)
    at Object.Module._extensions..js (https://aonizyvpa--github.w.staticblitz.com/blitz.a3339ebb87d0fe73c7995fe67420660e0dc95de2.js:6:168239)
    at Module.load (https://aonizyvpa--github.w.staticblitz.com/blitz.a3339ebb87d0fe73c7995fe67420660e0dc95de2.js:6:166317) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/projects/aonizyvpa.github/node_modules/@remix-run/serve/cli.js'
  ]
}
```

An empty file seems to exist at `node_modules/@remix-run/serve/env.d.ts`, the issue does not occur on version 1.0.6

**Comment by chaance** [comment]
Thanks for flagging this! Patched in 1.1.1.
