### ISSUE TITLE
[Bug]: Regression: tests that check for typeof formData are green on Remix 1.0.6, Failing on 1.1.1

### ISSUE THREAD

**Issue by arthurgeek** [remix-run/remix#1185]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16.13.0

### Steps to Reproduce

I have the following code:

```typescript
export const action: ActionFunction = async ({
  request,
}): Promise<Response | FormattedError> => {
  const form = await request.formData()
  const accountId = form.get('accountId')
  const description = form.get('description')
  const createdAt = form.get('createdAt')
  const amount = form.get('amount')

  console.log(typeof accountId)
  console.log(typeof description)
  console.log(typeof createdAt)
  console.log(typeof amount)

  if (
    typeof accountId !== 'string' ||
    typeof description !== 'string' ||
    typeof createdAt !== 'string' ||
    typeof amount !== 'string'
  ) {
    return json(
      { fieldErrors: {}, formErrors: ['Form not submitted correctly'] },
      { status: 400 },
    )
  }

  # [extra logic]
}
```

when calling the action using the following test:

```typescript
const date = new Date(2021, 2, 2).toISOString()

const body = new URLSearchParams({
  accountId: 'account-id',
  description: '',
  createdAt: date,
  amount: '',
})

const request = new Request(
  '/dashboard/accounts/account-id/transactions/new',
  {
    method: 'POST',
    body,
  }
)

const response = await action({ request, params: {}, context: {} })
```

the `console.log` on remix 1.06, prints:

```
  ● Console

    console.log
      string

      at _callee$ (app/routes/dashboard/accounts/$accountId.transactions.new.tsx:41:11)

    console.log
      string

      at _callee$ (app/routes/dashboard/accounts/$accountId.transactions.new.tsx:42:11)

    console.log
      string

      at _callee$ (app/routes/dashboard/accounts/$accountId.transactions.new.tsx:43:11)

    console.log
      string

      at _callee$ (app/routes/dashboard/accounts/$accountId.transactions.new.tsx:44:11)
```

And on 1.1.1, it prints:

```
  ● Console

    console.log
      string

      at _callee$ (app/routes/dashboard/accounts/$accountId.transactions.new.tsx:41:11)

    console.log
      object

      at _callee$ (app/routes/dashboard/accounts/$accountId.transactions.new.tsx:42:11)

    console.log
      string

      at _callee$ (app/routes/dashboard/accounts/$accountId.transactions.new.tsx:43:11)

    console.log
      object

      at _callee$ (app/routes/dashboard/accounts/$accountId.transactions.new.tsx:44:11)
```

It seems an empty string `''` now have the `typeof` object and not `string` anymore.

### Expected Behavior

The `console.log` line above should print `string` for empty (`''`) strings instead of `object`.

### Actual Behavior

Empty strings (`''`) have `typeof` `object`.

**Comment by airjp73** [comment]
It sounds like the `FormData` is returning `null` for these empty strings. I'm not sure if that's totally intentional -- if I run this in the browser, I still get an empty string. Maybe it's a discrepancy between the server-side polyfill of `FormData` and the actual, browser implementation?

<img width="361" alt="Screen Shot 2021-12-21 at 6 44 54 PM" src="https://user-images.githubusercontent.com/25882770/147011817-32c0fe3b-5585-4ef7-8b97-ae03eae8a099.png">

**Comment by sergiodxa** [comment]
The problem is that you are passing a URLSearchParams instance to the Request body instead of a FormData instance.

```ts
const date = new Date(2021, 2, 2).toISOString()

const body = new FormData()
body.set('accountId', 'account-id')
body.set('description', '')
body.set('createdAt', date)
body.set('amount', '')

const request = new Request(
  '/dashboard/accounts/account-id/transactions/new',
  { method: 'POST', body }
)

const response = await action({ request, params: {}, context: {} })
```

That should work.

**Comment by arthurgeek** [comment]
@sergiodxa the same happens in the browser when user does not type anything in the input field.

**Comment by sergiodxa** [comment]
<img width="385" alt="Screen Shot 2021-12-21 at 18 50 49" src="https://user-images.githubusercontent.com/1312018/147012151-583f7fa3-e3c6-42ab-b7c0-c6d726d93760.png">

In the browser, using FormData instead of URLSearchParams works

**Comment by arthurgeek** [comment]
@sergiodxa just tested again: when submitting the form using the browser, I also get `null` in v1.1.1 while `''` was returned in v1.0.6.

**Comment by arthurgeek** [comment]
I also changed my test to use `FormData` instead of `URLSearchParams` and got the same issue.

btw, thanks for the code, I'll update my tests to use `FormData`, as it's more consistent with browser behaviour :)

**Comment by sergiodxa** [comment]
> @sergiodxa just tested again: when submitting the form using the browser, I also get `null` in v1.1.1 while `''` was returned in v1.0.6.

The [FormData.get() docs](https://developer.mozilla.org/en-US/docs/Web/API/FormData/get#return_value) mention that if there's no input with the name you're trying to access it will return `null` if it can find it then it will be a [FormDataEntryValue](https://developer.mozilla.org/en-US/docs/Web/API/FormDataEntryValue).

Are you sending the fields with the same name as you try to read in the action?

**Comment by sergiodxa** [comment]
Could you create a reproduction app in https://remix.new ?

**Comment by arthurgeek** [comment]
Here it goes:

v1.1.1: https://stackblitz.com/edit/node-envpbk?file=app/routes/index.tsx

Try submitting the form without typing anything.

If you run the exact same code in v1.0.6 the behaviour is different.

**Comment by DKeen0123** [comment]
I believe this has broken the jokes app tutorial (I'm just going through it). 

In the example where you add validation to submit a new joke (just before the authentication section) the form will silently error on submit when fields are empty.

**Comment by arthurgeek** [comment]
@kentcdodds @ryanflorence could you take a look at this and tell us if it's indeed a bug or expected behavior of the new version? Either way I'll try to submit a fix, either for the bug or the example apps.

**Comment by canac** [comment]
I'm running into this too. It appears to be a bug because in all browsers I tested (Chrome, Safari, Firefox), this snippet logs `''` not `null`.

```js
const formData = new FormData();
formData.set('foo', '');
console.log(formData.get('foo'));
```

As a workaround, I'm replacing `formData.get('foo')` with `form.has('foo') ? form.get('foo') ?? '' : null` in my Remix code until this gets resolved.

**Comment by canac** [comment]
Looks like this was fixed in #1869.

**Comment by kentcdodds** [comment]
Looks like it. If anyone has issues with this in the future, please open a new issue. Thanks!
