### ISSUE TITLE
[Bug]: npm run build does not create a build folder

### ISSUE THREAD

**Issue by arunabhdas** [remix-run/remix#1313]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16.7.0

### Steps to Reproduce

1) npx create-remix@latest

2) Add build script to package.json as follows - 

```
  "scripts": {
    "build": "remix build",
    "dev": "remix dev",
    "postinstall": "remix setup node",
    "start": "remix-serve build"
  },
```

Run 

```
npm run build
```

Run 

```
npm start
```

### Expected Behavior

build folder should be created and rpm start should work

### Actual Behavior

```
==> npm start

> start
> remix-serve build

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: /build'
Require stack:
- /node_modules/@remix-run/serve/index.js
- /node_modules/@remix-run/serve/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.createApp (/node_modules/@remix-run/serve/index.js:35:12)
    at Object.<anonymous> (/node_modules/@remix-run/serve/cli.js:32:7)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
...
    
  ]
}

```

**Comment by sairaj2119** [comment]
I reproduced the steps and everything was working fine, what did you choose the deployment target? is it Remix app server

**Comment by arunabhdas** [comment]
I picked Vercel

**Comment by sairaj2119** [comment]
You have to pass the `serverBuildDirectory` which is defined in your `remix.config.js` to `remix-serve` in order to start the app

in case of Vercel it's this
```json

"start": "remix-serve ./api/_build"

```

**Comment by sairaj2119** [comment]
Even better would be to start with `NODE_ENV` as `production` to make it work more like a production app

```json

"start": "NODE_ENV=production remix-serve ./api/_build"


```
