### ISSUE TITLE
[Bug]: Using axios inside loader throws exception

### ISSUE THREAD

**Issue by anonrig** [remix-run/remix#1318]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [X] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

v17.3.0

### Steps to Reproduce

client.getSelfServiceLoginFlow uses axios on the internal implementation, and it causes the following error

```javascript
export const loader: LoaderFunction = async ({ request }) => {
  const url = new URL(request.url)
  const flow = url.searchParams.get('flow')

  if (!flow) {
    return new Response(null, {
      status: 301,
      headers: {
        Location: endpoints.login
      }
    })
  }

  const { data } = await client.getSelfServiceLoginFlow(flow, request.headers.get('cookie') ?? undefined)
  const isBefore = dayjs(data?.expires_at ?? undefined).isBefore(dayjs())

  if (isBefore) {
    return new Response(null, {
      status: 301,
      headers: {
        Location: endpoints.login
      }
    })
  }

  return { kratos: data }
}
```

### Expected Behavior

Axios should work properly. It seems that there's an issue with ESBuild causing adapter to be not defined. [Here's the link for related axios issue](https://github.com/axios/axios/issues/2968)

### Actual Behavior

Error:

```
There was an error running the data loader for route routes/signin
TypeError: adapter is not a function
    at dispatchRequest (/Users/yagiz/Developer/socketkit/socketkit/node_modules/.pnpm/axios@0.21.4/node_modules/axios/lib/core/dispatchRequest.js:53:10)
    at Axios.request (/Users/yagiz/Developer/socketkit/socketkit/node_modules/.pnpm/axios@0.21.4/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/Users/yagiz/Developer/socketkit/socketkit/node_modules/.pnpm/axios@0.21.4/node_modules/axios/lib/helpers/bind.js:9:15)
    at /Users/yagiz/Developer/socketkit/socketkit/node_modules/.pnpm/@ory+kratos-client@0.8.2-alpha.1/node_modules/@ory/kratos-client/dist/common.js:141:22
    at /Users/yagiz/Developer/socketkit/socketkit/node_modules/.pnpm/@ory+kratos-client@0.8.2-alpha.1/node_modules/@ory/kratos-client/dist/api.js:2434:121
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at loader (/Users/yagiz/Developer/socketkit/socketkit/pages/web/build/route-module:/Users/yagiz/Developer/socketkit/socketkit/pages/web/app/routes/signin.tsx:32:20)
    at callRouteLoader (/Users/yagiz/Developer/socketkit/socketkit/node_modules/.pnpm/@remix-run+server-runtime@1.1.1_react-dom@17.0.2+react@17.0.2/node_modules/@remix-run/server-runtime/esm/data.js:69:14)
```

**Comment by drewdecarme** [comment]
Your issue here isn't Axios or Remix related. Cloudflare Workers doesn't support `XMLHttpRequest` which Axios utilizes for requests. Cloudflare Workers only supports the Fetch API.

There's plans on creating an actual V1 of Axios, but not in the near future. https://github.com/axios/axios/issues/4209

**Comment by machour** [comment]
Not a remix issue.
