### ISSUE TITLE
[Bug]: AggregateError is missing the errors property when caught in the client

### ISSUE THREAD

**Issue by ivosabev** [remix-run/remix#1357]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16

### Steps to Reproduce

```tsx
import type {LoaderFunction} from 'remix';

export const loader: LoaderFunction = async () => {
  const e = new AggregateError([new Error('1'), new Error('2'), new Error('3')]);
  console.log('AggregateError Server', e.errors);
  throw e;
};

export default function Play() {
  return null;
}

export function ErrorBoundary({error}: {error: Error}) {
  console.log('AggregateError', (error as AggregateError).errors);
  return null;
}
```

### Expected Behavior
```
AggregateError [
  Error: 1
      at loader3 (/Users/ivolution/Sites/koop/server/build/index.js:2953:33)
      at Object.callRouteLoader (/Users/ivolution/Sites/koop/node_modules/@remix-run/server-runtime/data.js:73:20)
      at /Users/ivolution/Sites/koop/node_modules/@remix-run/server-runtime/server.js:270:113
      at Array.map (<anonymous>)
      at renderDocumentRequest (/Users/ivolution/Sites/koop/node_modules/@remix-run/server-runtime/server.js:270:67)
      at requestHandler (/Users/ivolution/Sites/koop/node_modules/@remix-run/server-runtime/server.js:55:26)
      at /Users/ivolution/Sites/koop/node_modules/@remix-run/express/server.js:45:28
      at /Users/ivolution/Sites/koop/server/index.js:27:59
      at Layer.handle [as handle_request] (/Users/ivolution/Sites/koop/node_modules/express/lib/router/layer.js:95:5)
      at next (/Users/ivolution/Sites/koop/node_modules/express/lib/router/route.js:137:13),
  Error: 2
      at loader3 (/Users/ivolution/Sites/koop/server/build/index.js:2953:49)
      at Object.callRouteLoader (/Users/ivolution/Sites/koop/node_modules/@remix-run/server-runtime/data.js:73:20)
      at /Users/ivolution/Sites/koop/node_modules/@remix-run/server-runtime/server.js:270:113
      at Array.map (<anonymous>)
      at renderDocumentRequest (/Users/ivolution/Sites/koop/node_modules/@remix-run/server-runtime/server.js:270:67)
      at requestHandler (/Users/ivolution/Sites/koop/node_modules/@remix-run/server-runtime/server.js:55:26)
      at /Users/ivolution/Sites/koop/node_modules/@remix-run/express/server.js:45:28
      at /Users/ivolution/Sites/koop/server/index.js:27:59
      at Layer.handle [as handle_request] (/Users/ivolution/Sites/koop/node_modules/express/lib/router/layer.js:95:5)
      at next (/Users/ivolution/Sites/koop/node_modules/express/lib/router/route.js:137:13),
  Error: 3
      at loader3 (/Users/ivolution/Sites/koop/server/build/index.js:2953:65)
      at Object.callRouteLoader (/Users/ivolution/Sites/koop/node_modules/@remix-run/server-runtime/data.js:73:20)
      at /Users/ivolution/Sites/koop/node_modules/@remix-run/server-runtime/server.js:270:113
      at Array.map (<anonymous>)
      at renderDocumentRequest (/Users/ivolution/Sites/koop/node_modules/@remix-run/server-runtime/server.js:270:67)
      at requestHandler (/Users/ivolution/Sites/koop/node_modules/@remix-run/server-runtime/server.js:55:26)
      at /Users/ivolution/Sites/koop/node_modules/@remix-run/express/server.js:45:28
      at /Users/ivolution/Sites/koop/server/index.js:27:59
      at Layer.handle [as handle_request] (/Users/ivolution/Sites/koop/node_modules/express/lib/router/layer.js:95:5)
      at next (/Users/ivolution/Sites/koop/node_modules/express/lib/router/route.js:137:13)
]
```

### Actual Behavior
```
AggregateError undefined
```

**Comment by machour** [comment]
Thank you for reporting this. 
Closing in favor of #1360
