### ISSUE TITLE
[Bug]: Cannot find module '/usr/server/app/start' when using pm2 and docker  

### ISSUE THREAD

**Issue by hannadrehman** [remix-run/remix#1361]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [X] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16.8.0

### Steps to Reproduce

came across a weird issue while using pm2 and dockerizing remix app. 

i am using pm2 docker image, you can find their docs [here](https://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/)

docker file 
```yml
FROM keymetrics/pm2:16-alpine

WORKDIR /usr/server/app

COPY ./packages/remix/package.json ./  

RUN pm2 install pm2-server-monit
RUN yarn 
COPY ./packages/remix .

CMD [ "pm2-runtime", "start", "ecosystem.config.js" ]

```

pm2 ecosystem.config.js
```js
module.exports = {
  apps: [
    {
      name: 'ssr-service',
      script: './node_modules/.bin/remix-serve',
      args: 'build',
      cwd: './',
      watch: false,
      instances: 'max',
      rutorestart: true,
      exec_mode: 'cluster_mode',
      error_file: '/dev/null',
      out_file: '/dev/null',
      merge_logs: true,
      env: {
        NODE_ENV: process.env.NODE_ENV || 'production',
        RUNTIME_ENV: process.env.RUNTIME_ENV || 'production',
        PORT: process.env.PORT || 3001,
      },
    },
  ],
};

```

package.json
```json

{
  "private": true,
  "name": "ssr-service",
  "description": "",
  "license": "",
  "scripts": {
    "build": "remix build",
    "dev": "remix dev",
    "postinstall": "remix setup node",
    "start": "remix-serve build",
    "start:prod": "pm2 start ecosystem.config.js"
  },
  "dependencies": {
    "@remix-run/react": "^1.1.1",
    "@remix-run/serve": "^1.1.1",
    "dotenv": "^8.2.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "remix": "^1.1.1"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.1.1"
  },
  "engines": {
    "node": ">=14"
  },
  "sideEffects": false
}

```
i am running standard `docker build` and `docker run` commands. 

`docker build -f./Dockerfile . -t rm/1`
`docker run rm/1`

before i run docker commands i am making sure i run `yarn build` to build the remix app

after docker run i get this error 

```
Error: Cannot find module '/usr/server/app/start'
Require stack:
- /usr/server/app/node_modules/@remix-run/serve/index.js
- /usr/server/app/node_modules/@remix-run/serve/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
```

### Expected Behavior

it should start server without any errors

### Actual Behavior

getting module not found error 

```
Error: Cannot find module '/usr/server/app/start'
Require stack:
- /usr/server/app/node_modules/@remix-run/serve/index.js
- /usr/server/app/node_modules/@remix-run/serve/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.createApp (/usr/server/app/node_modules/@remix-run/serve/index.js:35:12)
    at Object.<anonymous> (/usr/server/app/node_modules/@remix-run/serve/cli.js:33:7)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:303:25
```

according this this error message the command is expecting some `start` to module to be present in the `remix-server` package

i dug little bit into the code how `remix-server` is working and found this piece of code in `/node_modules/@remix-run/serve/cli.js`

```js
let port = process.env.PORT || 3000;
let buildPathArg = process.argv[2];  //now this is interesting. we are sort of expecting build arg to be at index 2. very risky
console.log(process.argv); 
if (!buildPathArg) {
  console.error(`
  Usage: remix-serve <build-dir>`);
  process.exit(1);
}

```
added some console logs and found args is getting these values 

```js 
 [
    '/usr/local/bin/node',
    '/usr/local/lib/node_modules/pm2/lib/ProcessContainer.js',
    'start',
    'ecosystem.config.js',
    'build'
  ]

```
well u can see `build` is at the last index. this is obviously because pm2 is starting the remix server.

to test i ran `pm2 start ecosystem.config.js`  directly without docker and it leads to the same issue. 

a quick fix to test locally was to add a npm script in package.json
```    
"start:prod": "pm2 start ecosystem.config.js"
```
and this worked. 
but docker issue still persisted. 

i think we need to find a better way to pass on params to the serve package

**Comment by shamsup** [comment]
Seems related to https://github.com/Unitech/pm2/issues/4950

**Comment by shamsup** [comment]
posting resolution here from the [discord thread](https://discord.com/channels/770287896669978684/928368462626193408/928374688915267614)

> without patching Remix or pm2, the easiest option is probably to create your own start script rather than using the `remix-serve` cli command:
> 
> ```javascript
> // index.js
> const {createApp} = require('@remix-run/serve');
> 
> let app = createApp('./build');
> let port = process.env.PORT || 3000;
> app.listen(port, () => {
>   console.log(`Remix App Server started at http://localhost:${port}`);
> });
> ```
> 
> With this, your `script` in your pm2 config becomes `script: './index.js'`.

**Comment by hannadrehman** [comment]
this is what worked finally 
```js
const path = require('path');
const { createApp } = require('@remix-run/serve');
const { serverBuildDirectory } = require('./remix.config');

const buildPath = path.resolve(process.cwd(), serverBuildDirectory);

const app = createApp(buildPath);
const port = process.env.PORT;

app.listen(port, () => {
  // eslint-disable-next-line
  console.log(`Remix App Server started at http://localhost:${port}`);
});

```

**Comment by Exilz** [comment]
@hannadrehman Using your `serve.js` file was the only way I could fix my `Cannot find module './env'` error. 
Related #1128

**Comment by mcansh** [comment]
@Exilz what version of remix are you using? `@remix/run/serve@^1.1.1` has a env.js file so this surprises me that it's popping up for you

**Comment by Exilz** [comment]
@mcansh Here are my versions

```json
    "@remix-run/react": "^1.4.1",
    "@remix-run/serve": "^1.4.1",
    "remix": "^1.4.1",
    "@remix-run/dev": "^1.1.3",
```

I'm surprised it doesn't work since it's supposed to have been fixed earlier. This only happens in our production environments. I can't reproduce it on my machine (node 14, mac M1).

Our production env is on AWS Beanstalk running a 64bit Amazon Linux 2 with Node 16.

**Comment by jacob-ebey** [comment]
After looking into this, it seems to be an issue with PM2. Closing for now, if the issue persists after an underlying PM2 fix is in, please re-open or file a new issue.
