### ISSUE TITLE
[Bug]: Unable to install tailwind without postcss

### ISSUE THREAD

**Issue by Manitej66** [remix-run/remix#1497]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

14.17.3

### Steps to Reproduce

Just like the [docs](https://remix.run/docs/en/v1/guides/styling#tailwind) mentioned,

`yarn add concurrently tailwindcss -D`

then run `npx tailwind init -p`

### Expected Behavior

no error while starting the server

### Actual Behavior

```bash
❯ npx tailwindcss init
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'postcss'
Require stack:
- /Users/maniteja/Documents/GitHub/supabase-remix-auth/node_modules/tailwindcss/lib/lib/generateRules.js
- /Users/maniteja/Documents/GitHub/supabase-remix-auth/node_modules/tailwindcss/lib/lib/expandTailwindAtRules.js
- /Users/maniteja/Documents/GitHub/supabase-remix-auth/node_modules/tailwindcss/lib/processTailwindFeatures.js
- /Users/maniteja/Documents/GitHub/supabase-remix-auth/node_modules/tailwindcss/lib/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/maniteja/Documents/GitHub/supabase-remix-auth/node_modules/tailwindcss/lib/lib/generateRules.js:6:39)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/maniteja/Documents/GitHub/supabase-remix-auth/node_modules/tailwindcss/lib/lib/generateRules.js',
    '/Users/maniteja/Documents/GitHub/supabase-remix-auth/node_modules/tailwindcss/lib/lib/expandTailwindAtRules.js',
    '/Users/maniteja/Documents/GitHub/supabase-remix-auth/node_modules/tailwindcss/lib/processTailwindFeatures.js',
    '/Users/maniteja/Documents/GitHub/supabase-remix-auth/node_modules/tailwindcss/lib/cli.js'
  ]
}
```

**Comment by sergiodxa** [comment]
That sounds like a bug in TailwindCSS

**Comment by Manitej66** [comment]
> That sounds like a bug in TailwindCSS

I think using yarn is the issue, I'll try with npm. Will update the issue if it fixes the issue.

**Comment by ccssmnn** [comment]
Agree with @sergiodxa. Has nothing to do with remix. 

@Manitej66 did you solve it? I'm successfully using tailwindcss & remix.
