### ISSUE TITLE
[Bug]: "remix dev" error when creating project with "cloudflare workers" option

### ISSUE THREAD

**Issue by coleea** [remix-run/remix#1721]
### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

16.13.2

### Steps to Reproduce

environment 
 - os : ubuntu 20
 - node : 16.13

I created remix project using command `npx create-remix@latest`, and set deploy targets on `cloudflare workers`. 

I installed `@remix-run/serve`, then run `remix dev`. meesage below appeared.

`Remix App Server started at http://121.172.71.142:3000`

and I connected `http://121.172.71.142:3000`, but error occured.

```
/mnt/mx500-234g/project/apps-for-study/remix-for-cfworkers-v2/build/index.js:10
import * as React from "react";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /mnt/mx500-234g/project/apps-for-study/remix-for-cfworkers-v2/node_modules/@remix-run/serve/index.js:39:17
    at Layer.handle [as handle_request] (/mnt/mx500-234g/project/apps-for-study/remix-for-cfworkers-v2/node_modules/express/lib/router/layer.js:95:5)
```

What am I missing ? thank you.

### Expected Behavior

I could expect to see page of `http://121.172.71.142:3000/` that I made.

### Actual Behavior

```
/mnt/mx500-234g/project/apps-for-study/remix-for-cfworkers-v2/build/index.js:10
import * as React from "react";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /mnt/mx500-234g/project/apps-for-study/remix-for-cfworkers-v2/node_modules/@remix-run/serve/index.js:39:17
    at Layer.handle [as handle_request] (/mnt/mx500-234g/project/apps-for-study/remix-for-cfworkers-v2/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by machour** [comment]
@coleea There have been a lot of changes to the cloudflare integration. Are you still seeing this problem with the newest remix version?

**Comment by coleea** [comment]
@machour it works. this issue needs to be closed.
thank you
