### ISSUE TITLE
[Feature]: Return arbitrary Response object directly from loader

### ISSUE THREAD

**Issue by colinclerk** [remix-run/remix#1753]
### What is the new or updated feature that you are suggesting?

We would like to return an arbitrary Response object directly from a loader.

### Why should this feature be included?

Our use case is that we're building an authentication library and we have special handling for the 401 Unauthorized case. We'd like to provide our handling directly through the loader, instead of asking developers to also modify the CatchBoundary.

Beyond our use case, it was a little confusing to learn that `redirect()` or `json()` Responses can be returned directly from a loader, but arbitrary Response objects cannot. We'd love a convention like returned Response objects are passed directly to the browser, while thrown Response objects go through the CatchBoundary.

**Comment by sergiodxa** [comment]
You can 100% return a new Response object with any status code and body from a loader.

If the route has a default export the data will be JSON.parse-d so your data should be compatible with that, for example don’t return a Buffer.

Also the json helper function can receive a status code or ResponseInit as second argument and there you can make the response created by it to be an unauthorized response.

**Comment by colinclerk** [comment]
Hi @sergiodxa - thanks for your help!

Our route has a default export and we want to return an HTML response directly from the loader under certain conditions.  We haven't been able to make this work - perhaps because of the JSON.parse restriction you mention?  If the capability already exists we'd love to use it!

Here's failing loader:
```js
export const loader: LoaderFunction = async () => {
  return new Response("<!DOCTYPE html><html><body>Test</body></html>", {
    status: 401,
  });
};
```

The error we receive is somewhat cryptic (it results in a 500 in the browser):
```
TypeError: Cannot read properties of undefined (reading 'toString')
    at Index (/Users/colinsidoti/my-remix-app/build/index.js:443:14)
    at processChild (/Users/colinsidoti/my-remix-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/colinsidoti/my-remix-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/colinsidoti/my-remix-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/colinsidoti/my-remix-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/Users/colinsidoti/my-remix-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at handleRequest (/Users/colinsidoti/my-remix-app/build/index.js:389:51)
    at renderDocumentRequest (/Users/colinsidoti/my-remix-app/node_modules/@remix-run/server-runtime/server.js:404:18)
    at async requestHandler (/Users/colinsidoti/my-remix-app/node_modules/@remix-run/server-runtime/server.js:55:20)
    at async /Users/colinsidoti/my-remix-app/node_modules/@remix-run/express/server.js:45:22
```

**Comment by sergiodxa** [comment]
@colinclerk if the route has a default export the data of the loader is used to supply data for that route component, instead of sending html, send data and render that html directly in the component of the route.

Another option is to don’t have a default export so the route becomes a Resource Route.

**Comment by colinclerk** [comment]
Yes, this is where we're stuck.  We're building an SDK and don't want to ask the developer to modify both their default export and their loader.

We'd like to be able to return arbitrary Response objects from the loader, just like we can return redirect and json Response objects.

For context, we're able to do this from `getServerSideProps` in Next.js by calling:
```
ctx.res.writeHead(401, { 'Content-Type': 'text/html' });
ctx.res.end(body);
```

**Comment by colinclerk** [comment]
For anyone who came here through the PR - in the comments above I was originally confused about the behavior of the `json()` helper.  I thought a `json` response would skip the default export render, but in fact only `redirect()` skips the render.
