### ISSUE TITLE
[Bug]: Importing OL (Open Layers) is failing

### ISSUE THREAD

**Issue by kubaracek** [remix-run/remix#1829]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

latest

### What version of Node are you using? Minimum supported version is 14.

17

### Steps to Reproduce

I'm not 100% sure if this is a Remix bug but when I opened the build app.js file it seems like Remix is doing some magic around imports.

What I struggle with is to import `ol` (OpenLayers) package to Remix. It constantly fails on an error. Tried to solve this for hours but was unable. Is this a bug or I just do something wrong and this package must be imported in a different way?

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /sandbox/node_modules/ol/format/IGC.js
require() of ES modules is not supported.
require() of /sandbox/node_modules/ol/format/IGC.js from /sandbox/build/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename IGC.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /sandbox/node_modules/ol/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/sandbox/build/index.js:408:29)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
``` 

![image](https://user-images.githubusercontent.com/16261998/152783747-34922f24-d6ff-4497-9178-c1d786257ea5.png)

### Expected Behavior

I'm able to import and use `ol`

### Actual Behavior

Fails on import `ERR_REQUIRE_ESM`

**Comment by kubaracek** [comment]
I see it was reported https://github.com/remarkjs/remark-gfm/issues/36 several times.. closing
