### ISSUE TITLE
[Bug]: Turborepo example won't work with Prisma

### ISSUE THREAD

**Issue by kettanaito** [remix-run/remix#1842]
### Which Remix packages are impacted?

- `@remix-run/vercel`

### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

v16.13.0

### Steps to Reproduce

1. Add Prisma to the project.
2. Try to bundle the `api/api.js` according to the instructions in the [Turborepo example](https://github.com/remix-run/remix/tree/9227936d697abd39736dd3f52b66da4a34aafcbb/examples/turborepo-vercel).
3. Create a Vercel project and deploy your app there.

### Expected Behavior

Provide an example that illustrates how to deploy Remix in a monorepo (i.e. Turboreop) where your app depends on a more complex logic than a `ui` package. 

It's crucial to have some guidance on this, as Vercel edge functions have a [list of limitations](https://vercel.com/docs/concepts/functions/edge-functions#runtime), one of which being inability to use `fs` operations in edge functions. That's what happens when bundling Prisma client. With these limitations in mind, how should I bundle/deploy my Remix app that has a route depending on the Prisma client? 

### Actual Behavior

The following exception is thrown when running the `api/index.js` edge function in a Vercel deployment:

```
2022-02-08T15:29:19.468Z	undefined	ERROR	Error: ENOENT: no such file or directory, open '/var/task/output/server/pages/api/schema.prisma'
	at Object.openSync (fs.js:497:3)    at Object.readFileSync (fs.js:393:35)
	at new LibraryEngine (/var/task/output/server/pages/api/index.js:191039:40)
	at PrismaClient.getEngine (/var/task/output/server/pages/api/index.js:195362:16)
	at new PrismaClient (/var/task/output/server/pages/api/index.js:195333:29)
	at Object.<anonymous> (/var/task/output/server/pages/api/index.js:196256:19)
	at Module._compile (internal/modules/cjs/loader.js:1085:14)    	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
	at Module.load (internal/modules/cjs/loader.js:950:32)
	at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
```

**Comment by xstevenyung** [comment]
I think this could be related to https://github.com/remix-run/remix/issues/1842

**Comment by tirthGajjar** [comment]
@kettanaito did you get it to work?

**Comment by tirthGajjar** [comment]
Hello, @machour @chaance let me know if I can help in any way to fix this.

**Comment by LonJonn** [comment]
This is still broken. Could someone put together an example with both turborepo + prisma deployed to vercel?

**Comment by LonJonn** [comment]
Yep

**Comment by machour** [comment]
@kettanaito could you try again using the last version of the remix adapter from Vercel?
