### ISSUE TITLE
Tutorial: Creating Gists

### ISSUE THREAD

**Issue by squidpunch** [remix-run/remix#197]
https://docs.remix.run/v0.17/tutorial/6-actions/

* Missing the import for `redirect` 💥 
* typescript validation of `fileName` (A computed property name must be of type 'string', 'number', 'symbol', or 'any'.ts(2464)) 🤷 

without fixing the redirect, a less than obvious error occurs:

```
Error: cannot clone body after it is used
    at clone (/Users/davidlarrabee/workspace/sandbox/my-remix-app/node_modules/node-fetch/lib/index.js:538:9)
    at new Request (/Users/davidlarrabee/workspace/sandbox/my-remix-app/node_modules/node-fetch/lib/index.js:1202:93)
    at Request.clone (/Users/davidlarrabee/workspace/sandbox/my-remix-app/node_modules/node-fetch/lib/index.js:1266:10)
    at /Users/davidlarrabee/workspace/sandbox/my-remix-app/node_modules/@remix-run/node/server.js:123:106
    at Array.map (<anonymous>)
    at handleDocumentRequest (/Users/davidlarrabee/workspace/sandbox/my-remix-app/node_modules/@remix-run/node/server.js:123:43)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/davidlarrabee/workspace/sandbox/my-remix-app/node_modules/@remix-run/express/server.js:32:22
```

**Comment by machour** [comment]
Not applicable anymore
