### ISSUE TITLE
Deno template errors on dynamic require()

### ISSUE THREAD

**Issue by mjackson** [remix-run/remix#1993]
### What version of Remix are you using?

1.2.1

### Steps to Reproduce

`npx create-remix@latest` and choose Deno as deploy target. Then `npm run dev` and you'll see the error.

### Expected Behavior

The dev server boots.

### Actual Behavior

```
error: Uncaught Error: Dynamic require of "https://deno.land/std/node/stream/mod.ts" is not supported
  throw new Error('Dynamic require of "' + x + '" is not supported');
        ^
    at file:///Users/michael/Projects/my-remix-app/build/index.js:30:9
    at file:///Users/michael/Projects/my-remix-app/build/index.js:2207:22
    at node_modules/react-dom/cjs/react-dom-server.node.development.js (file:///Users/michael/Projects/my-remix-app/build/index.js:5510:9)
    at __require2 (file:///Users/michael/Projects/my-remix-app/build/index.js:48:44)
    at node_modules/react-dom/server.node.js (file:///Users/michael/Projects/my-remix-app/build/index.js:5523:24)
    at __require2 (file:///Users/michael/Projects/my-remix-app/build/index.js:48:44)
    at node_modules/react-dom/server.js (file:///Users/michael/Projects/my-remix-app/build/index.js:5533:22)
    at __require2 (file:///Users/michael/Projects/my-remix-app/build/index.js:48:44)
    at file:///Users/michael/Projects/my-remix-app/build/index.js:7021:33
```

**Comment by machour** [comment]
Fixed by #1997
