### ISSUE TITLE
Client-Only-Components example is broken

### ISSUE THREAD

**Issue by lmachens** [remix-run/remix#2056]
### What version of Remix are you using?

1.2.1

### Steps to Reproduce

- Clone https://github.com/remix-run/remix/tree/main/examples/client-only-components
- `npm install`
- `npm run dev`

Open website in browser

```
ReferenceError: localStorage is not defined
    at Object.<anonymous> (/home/lmachens/dev/remix/examples/client-only-components/build/index.js:376:24)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/lmachens/dev/remix/examples/client-only-components/node_modules/@remix-run/serve/index.js:40:17
    at Layer.handle [as handle_request] (/home/lmachens/dev/remix/examples/client-only-components/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/lmachens/dev/remix/examples/client-only-components/node_modules/express/lib/router/route.js:137:13)
```

### Expected Behavior

Client side components should not be loaded on server side.

### Actual Behavior

Client side modules are loaded.
It worked in 1.3.1.
And it works if you add `.tsx` to the import path :

`.client";` > `.client.tsx";`

**Comment by sergiodxa** [comment]
This issues was fixed on this PR https://github.com/remix-run/remix/pull/2019, the bug was introduced on the latest minor release, it will be most likely fixed on the new patch or minor.
