### ISSUE TITLE
Create and run a new project with deployment target architect fails with yarn and pnpm

### ISSUE THREAD

**Issue by tobiasfoerg** [remix-run/remix#2073]
### What version of Remix are you using?

1.2.2

### Steps to Reproduce

Create a new Remix project
`npx create-remix`
Select `arc` as deployment target
Select `Typescript`
Do you want to run `npm install` -> No
cd into project
install global deps like described in README.md: `npm install -g @architect/architect aws-sdk`

### With yarn
install deps: `yarn`
start dev: `yarn dev`

### with pnpm
install deps: `pnpm install`
start dev: `pnpm dev`

### Expected Behavior

remix app is available on port 3333

### Actual Behavior

Start the app and visit `localhost:3333` results in:

#### With Yarn
```console
$ yarn dev
yarn run v1.22.17
$ cross-env NODE_ENV=development remix build && run-p dev:*
Building Remix app in development mode...
Built in 190ms
$ cross-env NODE_ENV=development remix watch
$ cross-env NODE_ENV=development arc sandbox
Watching Remix app in development mode...
💿 Built in 190ms
         App ⌁ remix-architect-app
      Region ⌁ us-west-2
     Profile ⌁ @aws profile / AWS_PROFILE not configured
     Version ⌁ Architect 10.0.0
         cwd ⌁ /home/tfoerg/github/tobiasfoerg/arc-test

✓ Sandbox Found Architect project manifest: app.arc
✓ Sandbox No custom testing environment variables found
✓ Sandbox Started AWS service emulator
✓ Sandbox @http server started
✓ Sandbox Project files hydrated into functions
✓ Sandbox Available @http (HTTP API mode / Lambda proxy v2.0 format) routes
    any /* ................................ server

    http://localhost:3333

✓ Sandbox Started in 4ms
❤︎ Local environment ready!

✓ Sandbox Started file watcher

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'aws-sdk'
Require stack:
- /home/tfoerg/github/tobiasfoerg/arc-test/node_modules/@architect/functions/src/tables/dynamo.js
- /home/tfoerg/github/tobiasfoerg/arc-test/node_modules/@architect/functions/src/http/session/providers/ddb/find.js
- /home/tfoerg/github/tobiasfoerg/arc-test/node_modules/@architect/functions/src/http/session/providers/ddb/index.js
- /home/tfoerg/github/tobiasfoerg/arc-test/node_modules/@architect/functions/src/http/session/read.js
- /home/tfoerg/github/tobiasfoerg/arc-test/node_modules/@architect/functions/src/http/http.js
- /home/tfoerg/github/tobiasfoerg/arc-test/node_modules/@architect/functions/src/http/index.js
- /home/tfoerg/github/tobiasfoerg/arc-test/node_modules/@architect/functions/src/index.js
- /home/tfoerg/github/tobiasfoerg/arc-test/node_modules/@remix-run/architect/sessions/arcTableSessionStorage.js
- /home/tfoerg/github/tobiasfoerg/arc-test/node_modules/@remix-run/architect/index.js
- /home/tfoerg/github/tobiasfoerg/arc-test/server/index.js
- /home/tfoerg/github/tobiasfoerg/arc-test/server/[eval]
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/tfoerg/github/tobiasfoerg/arc-test/node_modules/@architect/functions/src/tables/dynamo.js:1:11)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

#### With pnpm:
```console
➜ pnpm dev                                    

> remix-app-template@ dev /home/tfoerg/github/tobiasfoerg/arc-test
> cross-env NODE_ENV=development remix build && run-p dev:*

Building Remix app in development mode...
Built in 193ms

> remix-app-template@ dev:arc /home/tfoerg/github/tobiasfoerg/arc-test
> cross-env NODE_ENV=development arc sandbox


> remix-app-template@ dev:remix /home/tfoerg/github/tobiasfoerg/arc-test
> cross-env NODE_ENV=development remix watch

Watching Remix app in development mode...
💿 Built in 239ms
         App ⌁ remix-architect-app
      Region ⌁ us-west-2
     Profile ⌁ @aws profile / AWS_PROFILE not configured
     Version ⌁ Architect 10.0.0
         cwd ⌁ /home/tfoerg/github/tobiasfoerg/arc-test

✓ Sandbox Found Architect project manifest: app.arc
✓ Sandbox No custom testing environment variables found
✓ Sandbox Started AWS service emulator
✓ Sandbox @http server started
✓ Sandbox Project files hydrated into functions
✓ Sandbox Available @http (HTTP API mode / Lambda proxy v2.0 format) routes
    any /* ................................ server

    http://localhost:3333

✓ Sandbox Started in 5ms
❤︎ Local environment ready!

✓ Sandbox Started file watcher


/home/tfoerg/github/tobiasfoerg/arc-test/node_modules/.pnpm/@architect+functions@4.1.2/node_modules/@architect/functions/src/tables/dynamo.js:18
    throw ReferenceError('Incompatible version: please upgrade Architect Functions to >=5.x')
          ^
/home/tfoerg/github/tobiasfoerg/arc-test/node_modules/.pnpm/@architect+functions@4.1.2/node_modules/@architect/functions/src/tables/dynamo.js:18
    throw ReferenceError('Incompatible version: please upgrade Architect Functions to >=5.x')
    ^

ReferenceError: Incompatible version: please upgrade Architect Functions to >=5.x
    at getDynamo (/home/tfoerg/github/tobiasfoerg/arc-test/node_modules/.pnpm/@architect+functions@4.1.2/node_modules/@architect/functions/src/tables/dynamo.js:18:11)
    at Object.<anonymous> (/home/tfoerg/github/tobiasfoerg/arc-test/node_modules/.pnpm/@architect+functions@4.1.2/node_modules/@architect/functions/src/tables/dynamo.js:87:9)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/tfoerg/github/tobiasfoerg/arc-test/node_modules/.pnpm/@architect+functions@4.1.2/node_modules/@architect/functions/src/http/session/providers/ddb/find.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
```

#### With npm
> It does wort with npm

**Comment by machour** [comment]
@tobiasfoerg a lot of things changed since this issue was first reported. Can you still reproduce it with the latest version of remix?

**Comment by tobiasfoerg** [comment]
@machour I will check this out during the next days and let you know.
