### ISSUE TITLE
`TypeError: unusable` when reading form data in actionfunction using miniflare / Cloudflare

### ISSUE THREAD

**Issue by stepri** [remix-run/remix#2195]
### What version of Remix are you using?

1.2.3

### Steps to Reproduce

- create a new project using Cloudflare Pages
- create a form with a POST method
- create an action and try to read formdata
- run project using `npm run dev`

This error also happens on Cloudflare Workers

See example repo: https://github.com/stepri/formdata-remix-cloudflare/blob/main/app/routes/test.tsx

### Expected Behavior

No error

### Actual Behavior

500 Internal Server Error:

```
TypeError: unusable
    at Request.clone (/myproject/node_modules/undici/lib/fetch/request.js:725:13)
    at Request.clone (/myproject/node_modules/@miniflare/core/src/standards/http.ts:423:38)
    at renderDocumentRequest (/myproject/node_modules/@remix-run/server-runtime/esm/server.js:414:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at requestHandler (/myproject/node_modules/@remix-run/server-runtime/esm/server.js:51:20)
    at handleFetch (/myproject/node_modules/@remix-run/cloudflare-pages/esm/worker.js:47:18)
    at /myproject/node_modules/@remix-run/cloudflare-pages/esm/worker.js:55:14
    at next (/myproject/node_modules/wrangler/pages/functions/template-worker.ts:108:26)
    at EventTarget.[kDispatchFetch] (/myproject/node_modules/@miniflare/core/src/standards/event.ts:359:13)
    at Server.<anonymous> (/myproject/node_modules/@miniflare/http-server/src/index.ts:168:20)
```

**Comment by AntanasMisiunas** [comment]
I'm experiencing the same issue. However this happens only if I disable Javascript on the site.

**Comment by brookslybrand** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!  

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2.  If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.  

We plan to continue to address 2 types of issues in Remix v2:

* Bugs that pose security concerns
* Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new minimal reproduction against v7.

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
