### ISSUE TITLE
Server exits when `maxFileSize` is exceeded when using `unstable_createFileUploadHandler()`

### ISSUE THREAD

**Issue by uwuru** [remix-run/remix#2230]
### What version of Remix are you using?

1.2.3

### Steps to Reproduce

1. Do a standard install with default options by running `npx create-remix@latest`.
2. Start the server with `yarn dev`.
3. Replace `index.tsx` with the following code.

<details>
<summary>Click to show</summary>

```ts
import {
  ActionFunction,
  Form,
  unstable_createFileUploadHandler,
  unstable_parseMultipartFormData,
} from "remix";

const uploadHandler = unstable_createFileUploadHandler({
  directory: "public/uploads",
  file: ({ filename }) => filename,
  maxFileSize: 1_000_000,
});

export const action: ActionFunction = async ({ request }) => {
  const formData = await unstable_parseMultipartFormData(
    request,
    uploadHandler
  );

  const file = formData.get("selected-file");

  return { file };
};

export default function Index() {
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.4" }}>
      <h1>Upload limit demo</h1>
      <Form method="post" encType="multipart/form-data">
        <input type="file" id="selected-file" name="selected-file" />
        <button>Upload</button>
      </Form>
    </div>
  );
}
```
</details>

4. Upload a file that is larger than 1MB.

### Expected Behavior

The server to continue running. It should not exit as it does currently. Results in `ERR_CONNECTION_REFUSED` in browser.

### Actual Behavior

The server will exit. Console output:

```
There was an error running the action for route routes/index
Error: Field "selected-file" exceeded upload size of 1000000 bytes.
    at Meter._transform (/path/to/app/node_modules/@remix-run/node/upload/meter.js:30:23)
    at Meter.Transform._read (internal/streams/transform.js:205:10)
    at Meter.Readable.read (internal/streams/readable.js:462:10)
    at flow (internal/streams/readable.js:982:34)
    at WriteStream.pipeOnDrainFunctionResult (internal/streams/readable.js:806:7)
    at WriteStream.emit (events.js:400:28)
    at afterWrite (internal/streams/writable.js:461:12)
    at onwrite (internal/streams/writable.js:446:7)
    at internal/fs/streams.js:368:5
    at FSReqCallback.wrapper [as oncomplete] (fs.js:660:5)
Error: Field "selected-file" exceeded upload size of 1000000 bytes.
    at Meter._transform (/path/to/app/node_modules/@remix-run/node/upload/meter.js:30:23)
    at Meter.Transform._read (internal/streams/transform.js:205:10)
    at Meter.Readable.read (internal/streams/readable.js:462:10)
    at flow (internal/streams/readable.js:982:34)
    at WriteStream.pipeOnDrainFunctionResult (internal/streams/readable.js:806:7)
    at WriteStream.emit (events.js:400:28)
    at afterWrite (internal/streams/writable.js:461:12)
    at onwrite (internal/streams/writable.js:446:7)
    at internal/fs/streams.js:368:5
    at FSReqCallback.wrapper [as oncomplete] (fs.js:660:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I have found if I comment out this then it does not happen and remains running as expected:
https://github.com/remix-run/remix/blob/8a056ee4d17a1c4ecd2831196283a5cade1852c4/packages/remix-node/parseMultipartFormData.ts#L80-L83

Also, I have shared this on Discord #help where 1 person came forward as they had the same issue and was wondering if I had managed to resolve it. Someone else also replicated the issue successfully.

**Comment by a3diti** [comment]
Same problem, always exits only when max file size is exceeded
```
[1] POST /up?_data=routes%2Fuser%2Fup 500 - - 231.214 ms
[1] 
[1] /home/***/node_modules/@remix-run/node/upload/meter.js:30
[1]       return callback(new MeterError(this.field, this.maxBytes));
[1]                       ^
[1] Error: Field "cv" exceeded upload size of 10000000 bytes.
[1]     at Meter._transform (/home/***/node_modules/@remix-run/node/upload/meter.js:30:23)
[1]     at Meter.Transform._write (node:internal/streams/transform:184:23)
[1]     at writeOrBuffer (node:internal/streams/writable:389:12)
[1]     at _write (node:internal/streams/writable:330:10)
[1]     at Meter.Writable.write (node:internal/streams/writable:334:10)
[1]     at FileStream.ondata (node:internal/streams/readable:754:22)
[1]     at FileStream.emit (node:events:526:28)
[1]     at FileStream.Readable.read (node:internal/streams/readable:527:10)
[1]     at flow (node:internal/streams/readable:1011:34)
[1]     at resume_ (node:internal/streams/readable:992:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[1] yarn server:dev exited with code 
```

**Comment by a3diti** [comment]
Confirmed, if I comment line 83 `throw error;` I can properly catch the error when `maxFileSize` exceeds.

My temporary fix is patching this line locally with [patch-package](https://www.npmjs.com/package/patch-package) 

`patches/@remix-run+node+1.3.5.patch`
```
diff --git a/node_modules/@remix-run/node/parseMultipartFormData.js b/node_modules/@remix-run/node/parseMultipartFormData.js
index 661421d..2b64034 100644
--- a/node_modules/@remix-run/node/parseMultipartFormData.js
+++ b/node_modules/@remix-run/node/parseMultipartFormData.js
@@ -84,7 +84,7 @@ async function internalParseFormData(contentType, body, abortController, uploadH
               // *after* busboy has finished. Rethrow the error for surfacing
               // in the Promise.all(fileWorkQueue) below.
 
-              throw error;
+              // throw error;
             } finally {
               filestream.resume();
             }
```

**Comment by mcbergsma** [comment]
I'm getting the same thing using `unstable_createMemoryUploadHandler` when the `maxFileSize` is surpassed. Can't catch the error, just crashes the server.

**Comment by jackharrhy** [comment]
For people confused why `maxFileSize` no longer exists in the codebase, it seems to be renamed to `maxPartSize`

**Comment by fzsf163** [comment]
So I am getting the same error in version -
```
    "@remix-run/css-bundle": "2.5.1",
    "@remix-run/express": "2.5.1",
    "@remix-run/node": "2.5.1",
    "@remix-run/react": "2.5.1",
```

How do I catch this in action or component ? I am pretty new to remix js. 
```
  const e = useRouteError();
  if (isRouteErrorResponse(e) || e instanceof Error) {
    console.log(e);
  }
```
this does not give any error. Also I do not understand how the Error Boundary component is triggered as given in the doc.

**Comment by brookslybrand** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!

With this issue specifically, I recommend looking into how we recommend [handling file uploads in React Router 7](https://reactrouter.com/how-to/file-uploads)

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2.  If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.  

We plan to continue to address 2 types of issues in Remix v2:

* Bugs that pose security concerns
* Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new minimal reproduction against v7.

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
