### ISSUE TITLE
Invalid character error in cookie serialize

### ISSUE THREAD

**Issue by aiji42** [remix-run/remix#2255]
### What version of Remix are you using?

1.2.3

### Steps to Reproduce

 Serialize data containing Non-ASCII characters with `.serialize` the cookie object generated by `createCookie`.

```js
const cookie = createCookie('foo')
cookie.serialize({ data: '日本語' })
```

### Expected Behavior

Serialization can be done without any errors.

### Actual Behavior

Invalid character error occurs.
```
InvalidCharacterError: Invalid character
    at btoa (/Users/uejima.aiji/git/user/node_modules/@miniflare/core/src/standards/encoding.ts:37:13)
    at encodeData (/Users/uejima.aiji/git/user/node_modules/@remix-run/server-runtime/esm/cookies.js:94:10)
    at encodeCookieValue (/Users/uejima.aiji/git/user/node_modules/@remix-run/server-runtime/esm/cookies.js:68:17)
    at Object.serialize (/Users/uejima.aiji/git/user/node_modules/@remix-run/server-runtime/esm/cookies.js:50:56)
    at loader (/Users/uejima.aiji/git/user/build/route:/Users/uejima.aiji/git/user/app/root.tsx:24:16)
    at callRouteLoader (/Users/uejima.aiji/git/user/node_modules/@remix-run/server-runtime/esm/data.js:69:20)
    at /Users/uejima.aiji/git/user/node_modules/@remix-run/server-runtime/esm/server.js:266:108
    at Array.map (<anonymous>)
    at renderDocumentRequest (/Users/uejima.aiji/git/user/node_modules/@remix-run/server-runtime/esm/server.js:266:67)
    at requestHandler (/Users/uejima.aiji/git/user/node_modules/@remix-run/server-runtime/esm/server.js:51:26)
```

**Comment by aiji42** [comment]
When using third party authentication such as Google auth, ASCII characters such as the user's name may be unintentionally included in the data stored in cookies.

**Comment by aiji42** [comment]
Defining the `toBinary` and `fromBinary` functions solves the problem. (https://developer.mozilla.org/ja/docs/Web/API/btoa#unicode_strings)
```ts
// https://github.com/remix-run/remix/blob/main/packages/remix-server-runtime/cookies.ts#L168
function encodeData(value: any): string {
  return btoa(toBinary(JSON.stringify(value)));
}

function decodeData(value: string): any {
  try {
    return JSON.parse(fromBinary(atob(value)));
  } catch (error) {
    return {};
  }
}

// Added
function toBinary(value: string): string {
  const codeUnits = new Uint16Array(value.length);
  for (let i = 0; i < codeUnits.length; i++) {
    codeUnits[i] = value.charCodeAt(i);
  }
  return String.fromCharCode(...new Uint8Array(codeUnits.buffer));
}

function fromBinary(value: string): string {
  const bytes = new Uint8Array(value.length);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = value.charCodeAt(i);
  }
  return String.fromCharCode(...new Uint16Array(bytes.buffer));
}
```

**Comment by machour** [comment]
Thank you for the PR with the smaller footprint!
Closing this issue in favor of #1282
