### ISSUE TITLE
npx create-remix@latest copies entire remix source

### ISSUE THREAD

**Issue by coreyleelarson** [remix-run/remix#2348]
### What version of Remix are you using?

1.3.0

### Steps to Reproduce

- Run `npx create-remix@latest`
- Enter app name e.g. "test-remix" and hit enter
- Select "Just the basics"
- Select "Remix App Server"
- Select "Typescript"
- Enter "n" to prevent installing dependencies
- Observe all files in the "test-remix" directory

<img width="926" alt="Screen Shot 2022-03-16 at 4 48 34 PM" src="https://user-images.githubusercontent.com/1900645/158697653-f7038c88-159d-4798-87cb-a0e6b7f528a2.png">

### Expected Behavior

Remix application structure is copied.

### Actual Behavior

Entire Remix source is copied.

<img width="283" alt="Screen Shot 2022-03-16 at 4 50 47 PM" src="https://user-images.githubusercontent.com/1900645/158697619-402d2e87-0867-4be3-81b9-f02b952de52f.png">

**Comment by coreyleelarson** [comment]
Currently working around it by running `npx create-remix@1.2.3`

**Comment by zegevlier** [comment]
I seem to have a similar issue, when I try to make a new Cloudflare Workers project in this new version, I get the following error log:
```
Error: Cannot find module 'G:\my-new-project\package.json'
Require stack:
- C:\Users\User\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\create.js
- C:\Users\User\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli\commands.js
- C:\Users\User\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.createApp (C:\Users\User\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\create.js:156:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.create (C:\Users\User\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli\commands.js:68:3)
    at async run (C:\Users\User\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli.js:324:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\User\\AppData\\Local\\npm-cache\\_npx\\d12062682bcda260\\node_modules\\@remix-run\\dev\\create.js',
    'C:\\Users\\User\\AppData\\Local\\npm-cache\\_npx\\d12062682bcda260\\node_modules\\@remix-run\\dev\\cli\\commands.js',
    'C:\\Users\\User\\AppData\\Local\\npm-cache\\_npx\\d12062682bcda260\\node_modules\\@remix-run\\dev\\cli.js'
  ]
}
Error: Command failed: npx --yes @remix-run/dev@1.3.1 create
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:902:15)
    at run (C:\Users\User\AppData\Local\npm-cache\_npx\5164864a48bff686\node_modules\create-remix\cli.js:30:17)
    at Object.<anonymous> (C:\Users\User\AppData\Local\npm-cache\_npx\5164864a48bff686\node_modules\create-remix\cli.js:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 24956,
  stdout: null,
  stderr: null
}
```
I'll use v1.2.3 for now.

**Comment by kentcdodds** [comment]
I believe this has been fixed and released as 1.3.1. Let us know if not!

https://github.com/remix-run/remix/pull/2346

**Comment by kentcdodds** [comment]
Verified :)

```
~/Desktop 🥳
$ npx create-remix@1.3.1
Need to install the following packages:
  create-remix@1.3.1
Ok to proceed? (y) 
💿 Welcome to Remix! Let's get you set up with a new project.

npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
? Where would you like to create your app? test-remix
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? No
💿 That's it! `cd` into "/Users/kentcdodds/Desktop/test-remix" and check the README for development and deploy instructions!
~/Desktop 🥳
$ ls -l test-remix
total 40
-rw-r--r--  1 kentcdodds  staff  1057 Mar 16 16:05 README.md
drwxr-xr-x  6 kentcdodds  staff   192 Mar 16 16:33 app
-rw-r--r--  1 kentcdodds  staff   805 Mar 16 16:33 package.json
drwxr-xr-x  3 kentcdodds  staff    96 Mar 16 16:05 public
-rw-r--r--  1 kentcdodds  staff   242 Mar 16 16:05 remix.config.js
-rw-r--r--  1 kentcdodds  staff    91 Mar 16 16:05 remix.env.d.ts
-rw-r--r--  1 kentcdodds  staff   474 Mar 16 16:05 tsconfig.json
```

**Comment by coreyleelarson** [comment]
@kentcdodds Yep, it's fixed. Thanks!

**Comment by johanndev** [comment]
Still hitting this issue with both version `1.3.1` and `1.3.2`
Version `1.2.3` behaves as expected.

### System information
```
Windows 11 21H2
node 16.14.0
```
