### ISSUE TITLE
create-remix Error: Cannot find module '**\package.json'

### ISSUE THREAD

**Issue by qianjiachun** [remix-run/remix#2356]
### What version of Remix are you using?

v1.3.1 / lastest

### Steps to Reproduce

1. npx create-remix@latest remix-test
- Just the basics
- Remix App Server
- TypeScript
- No
2. and then error occured
```
E:\react>npx create-remix@latest remix-test
💿 Welcome to Remix! Let's get you set up with a new project.

? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? No
Error: Cannot find module 'E:\react\remix-test\package.json'
Require stack:
- C:\Users\hasee\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\create.js
- C:\Users\hasee\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli\commands.js
- C:\Users\hasee\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.createApp (C:\Users\hasee\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\create.js:156:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.create (C:\Users\hasee\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli\commands.js:68:3)
    at async run (C:\Users\hasee\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli.js:324:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\hasee\\AppData\\Local\\npm-cache\\_npx\\d12062682bcda260\\node_modules\\@remix-run\\dev\\create.js',
    'C:\\Users\\hasee\\AppData\\Local\\npm-cache\\_npx\\d12062682bcda260\\node_modules\\@remix-run\\dev\\cli\\commands.js',
    'C:\\Users\\hasee\\AppData\\Local\\npm-cache\\_npx\\d12062682bcda260\\node_modules\\@remix-run\\dev\\cli.js'
  ]
}
Error: Command failed: npx --yes @remix-run/dev@1.3.1 create remix-test
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at run (C:\Users\hasee\AppData\Local\npm-cache\_npx\5164864a48bff686\node_modules\create-remix\cli.js:30:17)
    at Object.<anonymous> (C:\Users\hasee\AppData\Local\npm-cache\_npx\5164864a48bff686\node_modules\create-remix\cli.js:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 8504,
  stdout: null,
  stderr: null
}
```

### Expected Behavior

successfully created project

### Actual Behavior

error

**Comment by pacexy** [comment]
It seems a bug since v1.3.0.

**Comment by khangprcvn** [comment]
Anyone know fix it, I'm getting it

**Comment by pacexy** [comment]
> Anyone know fix it, I'm getting it

```
npx create-remix@1.2.3 remix-test
```

**Comment by khangprcvn** [comment]
> > Anyone know fix it, I'm getting it
> 
> ```
> npx create-remix@1.2.3 remix-test
> ```

Thank you so much

**Comment by chaance** [comment]
Hmm, unable to reproduce but it could be a Windows thing. I'll boot the PC and investigate further. 
<img width="958" alt="terminal screenshot showing successful script" src="https://user-images.githubusercontent.com/3082153/158832434-e8fc77a9-570e-479f-9603-1e5610205cdf.png">

**Comment by alakbar97** [comment]
I have the same problem

**Comment by vicadam** [comment]
I get the same error on Windows 10 (21H2), node 16.13.2, yarn 1.22.17. Tried in multiple consoles: git bash, git zsh, conemu zsh, windows terminal, all end with the same error. Even when saying Y to running npm.

Launched using the following commands:
```
yarn create remix
yarn create remix@latest
npx create-remix
npx create-remix@latest
```

(Also note that arrow key navigation does not work in git bash (or git zsh). Just moves the cursor around.)

From Windows Terminal Command Prompt:
```
D:\Desktop>npx create-remix@latest remix-test
💿 Welcome to Remix! Let's get you set up with a new project.

? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? No
Error: Cannot find module 'D:\Desktop\remix-test\package.json'
Require stack:
- C:\Users\vadam\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\create.js
- C:\Users\vadam\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli\commands.js
- C:\Users\vadam\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.createApp (C:\Users\vadam\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\create.js:156:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.create (C:\Users\vadam\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli\commands.js:68:3)
    at async run (C:\Users\vadam\AppData\Local\npm-cache\_npx\d12062682bcda260\node_modules\@remix-run\dev\cli.js:324:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\vadam\\AppData\\Local\\npm-cache\\_npx\\d12062682bcda260\\node_modules\\@remix-run\\dev\\create.js',
    'C:\\Users\\vadam\\AppData\\Local\\npm-cache\\_npx\\d12062682bcda260\\node_modules\\@remix-run\\dev\\cli\\commands.js',
    'C:\\Users\\vadam\\AppData\\Local\\npm-cache\\_npx\\d12062682bcda260\\node_modules\\@remix-run\\dev\\cli.js'
  ]
}
Error: Command failed: npx --yes @remix-run/dev@1.3.1 create remix-test
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at run (C:\Users\vadam\AppData\Local\Yarn\Data\global\node_modules\create-remix\cli.js:30:17)
    at Object.<anonymous> (C:\Users\vadam\AppData\Local\Yarn\Data\global\node_modules\create-remix\cli.js:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 6704,
  stdout: null,
  stderr: null
}

D:\Desktop>
```
It **does** work when selecting one of the pre-configured stacks.

**Comment by chaance** [comment]
Can someone on Windows try again with `npx create-remix@0.0.0-experimental-f2df4787`?

**Comment by vicadam** [comment]
I think it might have something to do with the path separators. I've been messing around in the `@remix-rum\dev\create.js` file, in the `downloadAndExtractTemplateOrExample` function (line 190). When I force the path separators to be `/`, everything works as it should. Of note, `path__default["default"].sep` comes back as `\\` and templateDir uses `\\` while the rest of the variables (like header.name) use `/`. Hopefully this helps a bit.

**Comment by mcansh** [comment]
who wants to give `npx create-remix@0.0.0-experimental-5ddceecc` a shot? I've replaced all instances of `/` with `path.sep`

**Comment by mcansh** [comment]
> It does work when selecting one of the pre-configured stacks.

the "just the basics" templates live in this repo so they need to be extracted from here instead of just "give me the whole repo"

**Comment by vicadam** [comment]
Still fails, sorry, same error.

**Comment by vicadam** [comment]
Still a separator issue I think. templateDir uses `\\` while header.name uses `/`. Hacking as follows makes it work:
``` javascript
await pipeline(response.body.pipe(gunzip__default["default"]()), tar__default["default"].extract(cwd, {
    map(header) {
      let originalDirName = header.name.split('/')[0]; // changing path_default["default"].sep to '/'
      header.name = header.name.replace(originalDirName, desiredDir);
      templateDir = templateDir.replace('\\', '/');  // adding this line
      if (!header.name.startsWith(templateDir + '/')) { // changing path_default["default"].sep to '/'
        header.name = "__IGNORE__";
      } else {
        header.name = header.name.replace(templateDir, desiredDir);
      }

      return header;
    },
```

**Comment by mcansh** [comment]
the latest experimental uses path.sep for everything, weird

**Comment by mcansh** [comment]
OH! unless you mean the actual tarball header.name

**Comment by kiliman** [comment]
@mcansh Not sure if you're seeing this, but on the Mac, if I select "Just the basics", the CLI starts copying every folder in the current directory into the new project folder.

I have to kill it to stop the copy.
<img width="899" alt="image" src="https://user-images.githubusercontent.com/47168/158895497-41eb23c1-69e8-4171-a400-d0e9cb1cd333.png">

**Comment by mcansh** [comment]
@kiliman is that on latest or the latest experimental?

**Comment by vicadam** [comment]
On my Mac (Monterey 12.3) all seems good (using latest). Some alignment issues with the Welcome though...

<img width="1293" alt="Screen Shot 2022-03-17 at 2 13 11 PM" src="https://user-images.githubusercontent.com/2036925/158896262-f0a97271-bead-4859-8fe0-33d91ef1e212.png">

**Comment by kiliman** [comment]
Got it working... turns out I had some random GITHUB_TOKEN set which caused issues getting the template... not sure where it came from, but once I cleared it it worked just fine.

Doesn't explain why it was recursively copying folders... computers, what can you say? 😳

**Comment by chaance** [comment]
Really appreciate everyone's patience and help here! None of us are Windows users and while I have a PC, I'm not incredibly efficient on it 😅 (I literally googled/copy/pasted that emoji because I have no idea how to type one on Windows)

@vicadam I think your fix might be the ticket so I'm gonna release again in a few. FYI it does at least seem to be working with the latest experimental via WSL, but the separators were still a bugger w/ PowerShell.

**Comment by vicadam** [comment]
Boom!! `[v0.0.0-experimental-fde68a7](https://github.com/remix-run/remix/releases/tag/v0.0.0-experimental-fde68a7)` works correctly. Thanks @chaance !

**Comment by chaance** [comment]
Confirmed on WSL + PowerShell, woohoo! Patch coming shortly, thanks again everyone!

**Comment by chaance** [comment]
Stable patch should go out tomorrow morning. If anyone feels like running a few more stress tests for me, `npx create-remix@1.3.2-pre.0` is ready to roll.

**Comment by vicadam** [comment]
Success on Windows 11 (git bash) and MacOS Monterey 12.3 (iTerm2).

```
? Where would you like to create your app? app2
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? No
💿 That's it! `cd` into "/Users/vic/app2" and check the README for development and deploy instructions!
```

**Comment by chaance** [comment]
I think we're good here. Please upgrade to 1.3.2 for bootstrapping future apps, and thank you all again for the assist! ❤️

**Comment by pedrogius** [comment]
Still getting this error on Ubuntu 20.04 and node 14.18.2

**Comment by codthing** [comment]
> 在 Ubuntu 20.04 和节点 14.18.2 上仍然出现此错误

+1

**Comment by chaance** [comment]
We are tracking all Windows issues in https://github.com/remix-run/remix/issues/2714 and we have a [WIP branch](https://github.com/remix-run/remix/tree/chance/test-windows) that will resolve them. Follow #2714 for updates!
