### ISSUE TITLE
[Deno] [ERROR]: Property 'reason' does not exist on type 'AbortSignal'

### ISSUE THREAD

**Issue by CanRau** [remix-run/remix#2402]
### What version of Remix are you using?

1.3.2

### Steps to Reproduce

1. npx create-remix@latest --template deno-ts
2. npm i (if not run during first step)
3. npm run dev

```bash
$ deno --version
deno 1.20.1 (release, x86_64-apple-darwin)
v8 10.0.139.6
typescript 4.6.2
```

### Expected Behavior

Running dev server

### Actual Behavior

```bash
error: TS2339 [ERROR]: Property 'reason' does not exist on type 'AbortSignal'.
    return Promise.reject(createAbortError(signal.reason));
                                                  ~~~~~~
    at https://deno.land/std@0.130.0/async/abortable.ts:25:51

TS2339 [ERROR]: Property 'reason' does not exist on type 'AbortSignal'.
  const abort = () => waiter.reject(createAbortError(signal.reason));
                                                            ~~~~~~
    at https://deno.land/std@0.130.0/async/abortable.ts:28:61

TS2339 [ERROR]: Property 'reason' does not exist on type 'AbortSignal'.
    throw createAbortError(signal.reason);
                                  ~~~~~~
    at https://deno.land/std@0.130.0/async/abortable.ts:43:35

TS2339 [ERROR]: Property 'reason' does not exist on type 'AbortSignal'.
  const abort = () => waiter.reject(createAbortError(signal.reason));
                                                            ~~~~~~
    at https://deno.land/std@0.130.0/async/abortable.ts:46:61

Found 4 errors.
```

**Comment by machour** [comment]
Seeing the same thing

```
deno 1.19.3 (release, aarch64-apple-darwin)
v8 9.9.115.8
typescript 4.5.2
```

**Comment by F3n67u** [comment]
I think it's caused by `compilerOptions.lib`  option in `deno.json` which is come from `deno-ts` template, If I remove the `compilerOption.lib` in `deno.json`, then the TS ERROR is gone.

```json
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "dom.asynciterable", "deno.ns"]
  }
}
```

=>

```json
{}
```

**Comment by pcattori** [comment]
I'm unable to reproduce with:

```
deno 1.19.1 (release, aarch64-apple-darwin)
v8 9.9.115.7
typescript 4.5.2
```

The reason for including `lib` option is to for type checking support. E.g. in VS Code, if I remove the `lib` option I get:
<img width="744" alt="Screen Shot 2022-03-21 at 10 04 18 PM" src="https://user-images.githubusercontent.com/1477317/159399794-28b33406-91f8-4154-b297-b10532f025d7.png">

**Comment by pcattori** [comment]
Started running into this on Deno v1.20.5.
