### ISSUE TITLE
critical error: npx create-remix@latest wont install generates route error.

### ISSUE THREAD

**Issue by laurencefass** [remix-run/remix#2424]
### What version of Remix are you using?

create-remix@latest

### Steps to Reproduce

node version: 
v16.13.1
npx
v8.1.2
npm 
v8.1.2

execute 

```
npx create-remix@latest
```

see error below.

### Expected Behavior

install remix with no errors.

i have this running on a server alongside next and cra apps which all installed without error.

### Actual Behavior

<code>
bash-5.1# npx create-remix@latest
� Welcome to Remix! Let's get you set up with a new project.

/root/.npm/_npx/0936179b381f03f9/node_modules/@babel/highlight/node_modules/color-convert/index.js:67
        var routes = route(fromModel);
                     ^

TypeError: route is not a function
    at /root/.npm/_npx/0936179b381f03f9/node_modules/@babel/highlight/node_modules/color-convert/index.js:67:15
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/root/.npm/_npx/0936179b381f03f9/node_modules/@babel/highlight/node_modules/color-convert/index.js:61:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/.npm/_npx/0936179b381f03f9/node_modules/@babel/highlight/node_modules/ansi-styles/index.js:2:22)
Error: Command failed: npx --yes @remix-run/dev@1.3.2 create
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at run (/root/.npm/_npx/5164864a48bff686/node_modules/create-remix/cli.js:30:17)
    at Object.<anonymous> (/root/.npm/_npx/5164864a48bff686/node_modules/create-remix/cli.js:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 121,
  stdout: null,
  stderr: null
}
</code>

**Comment by TheRealFlyingCoder** [comment]
Confirming this is also occuring on Windows, I hadn't tried before the V1.3.2, but I assume the code to fix the create-remix bug left something out?

**Comment by chaance** [comment]
What options are you selecting at startup? Or is the failure occurring before the terminal prompts for the options?

**Comment by TheRealFlyingCoder** [comment]
> What options are you selecting at startup? Or is the failure occurring before the terminal prompts for the options?

No options selected, it fails immediately after installing the package to cache and trying to run

**Comment by mcansh** [comment]
> > What options are you selecting at startup? Or is the failure occurring before the terminal prompts for the options?
> 
> No options selected, it fails immediately after installing the package to cache and trying to run

does it also happen if you run `npx --yes @remix-run/dev@1.3.2 create` by chance?

**Comment by TheRealFlyingCoder** [comment]
Yeah that also fails

**Comment by TheRealFlyingCoder** [comment]
@chaance @mcansh A rollback to node V14.19.1 works, and rolling forward to V17.1.0 also works

The problem is somewhere in V16

**Comment by mcansh** [comment]
> @chaance @mcansh A rollback to node V14.19.1 works, and rolling forward to V17.1.0 also works
> 
> The problem is somewhere in V16, I've tested it on V16.14.2 (Last version before 17) and it still fails

interesting, thanks for the update! (works on macOS though, @chaance is gonna check it out some more tomorrow)

**Comment by chaance** [comment]
In our next release (tomorrow) we're no longer executing npx directly so I'm hoping that solves the issue. Will dig deeper otherwise. Just to confirm, this is running with PowerShell or WSL?

**Comment by laurencefass** [comment]
Thanks for feedback. After next commit will there be a new installation command or still

npx create-remix@latest?

Will you post a notification in this thread as potential fix? Im happy to retest and report as soon as its available.

**Comment by machour** [comment]
@laurencefass can you try again with latest release?

**Comment by laurencefass** [comment]
Installation worked seamlessly with ```npx create-remix@latest``` command. Installed 1.3.4. Thanks.
