### ISSUE TITLE
401 Unauthorized when running create-remix

### ISSUE THREAD

**Issue by coreylight** [remix-run/remix#2428]
### What version of Remix are you using?

dev@1.3.2

### Steps to Reproduce

`npx create-remix`
`./awesomeproject`
`Just the basics`
`Vercel`
`TypeScript`
`N` (npm install)
```
Error: Error fetching repo: 401 Unauthorized
    at isRemixTemplate (/Users/corey/.npm/_npx/0936179b381f03f9/node_modules/@remix-run/dev/create.js:378:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async detectTemplateType (/Users/corey/.npm/_npx/0936179b381f03f9/node_modules/@remix-run/dev/create.js:413:7)
    at async Object.createApp (/Users/corey/.npm/_npx/0936179b381f03f9/node_modules/@remix-run/dev/create.js:95:22)
    at async Object.create (/Users/corey/.npm/_npx/0936179b381f03f9/node_modules/@remix-run/dev/cli/commands.js:68:3)
    at async run (/Users/corey/.npm/_npx/0936179b381f03f9/node_modules/@remix-run/dev/cli.js:324:9)
```

### Expected Behavior

A new remix project is created.

### Actual Behavior

Remix project not created, errors with 401 Unauthorized.

**Comment by mcansh** [comment]
weird! we make a request to [GitHub's API](https://api.github.com/repos/remix-run/remix/contents/templates) for this, do you have a `GITHUB_TOKEN` environment variable in your shell?

**Comment by mcansh** [comment]
> Perhaps a better error message for the next person who runs into this?

definitely, filed an internal ticket, not sure we'll get it in for this upcoming release, but definitely the next one :)

**Comment by karaeren** [comment]
I'm running into the same problem. I don't have an environment variable for GITHUB_TOKEN, however, I use git store helper to save my valid token and somehow still get the error. I can use git just fine from the terminal...
