### ISSUE TITLE
ESM Module Error using react-flow-renderer@10.x.x

### ISSUE THREAD

**Issue by OFranke** [remix-run/remix#2429]
### What version of Remix are you using?

1.3.2

### Steps to Reproduce

See https://stackblitz.com/edit/node-jhtkf8?file=remix.config.js

### Expected Behavior

Correctly start the app and show a flow diagram.

I tried to import the module as described in the docs: https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages
Configured remix to bundle dependencies on server:
```
/**
 * @type {import('@remix-run/dev/config').AppConfig}
 */
module.exports = {
  appDirectory: 'app',
  browserBuildDirectory: 'public/build',
  publicPath: '/build/',
  serverBuildDirectory: 'build',
  devServerPort: 8002,
  serverDependenciesToBundle: [
    'react-flow-renderer',
    'd3-zoom',
    'd3-dispatch',
    'd3-drag',
    'd3-selection',
    'd3-interpolate',
    'd3-transition',
    'd3-color',
    'd3-timer',
    'd3-ease',
  ],
};
```

Not sure if it's a remix issue, there is already a bug report by [hgeldenhuys](https://github.com/hgeldenhuys) on react-flow-renderer: https://github.com/wbkd/react-flow/issues/1953 

### Actual Behavior

Displaying error message:
`TypeError: (0 , import_context.default) is not a function
    at Object.eval (/home/projects/node-jhtkf8/build/index.js:4170:49)
    at Object.function (https://node-jhtkf8.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:15:101746)
    at Module._compile (https://node-jhtkf8.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:6:196043)
    at Object.Module._extensions..js (https://node-jhtkf8.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:6:196398)
    at Module.load (https://node-jhtkf8.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:6:194488)
    at Function.Module._load (https://node-jhtkf8.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:6:192091)
    at Module.require (https://node-jhtkf8.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:6:194806)
    at i (https://node-jhtkf8.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:6:349630)
    at _0x186806 (https://node-jhtkf8.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:15:101391)
    at eval (/home/projects/node-jhtkf8/node_modules/@remix-run/serve/index.js:43:17)`

**Comment by machour** [comment]
Hi @OFranke, thank you for reporting this.
The issue is already tracked in #109 and you may find some workarounds there.

**Comment by hgeldenhuys** [comment]
Tried those workarounds without success. The solutions are horrible, first IDE doesn't like the esm.modules as js file on the route of the repo, then it's unclear how one treats named imports as opposed to just default imports, but after massaging the code with lots of @ts-ignores I get ERR_REQUIRE_ESM lower down in the package I'm trying to import, and adding those deeper packages to remix.config.js' serverDependenciesToBundle I just end up with another error that stumps me: ```TypeError: (0 , import_context.default) is not a function
    at Object.<anonymous> (/Users/hgeldenhuys/Emerge/flow/build/index.js:4175:49)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/hgeldenhuys/Emerge/flow/node_modules/.pnpm/@remix-run+serve@1.2.3_react-dom@17.0.2+react@17.0.2/node_modules/@remix-run/serve/index.js:40:17
    at Layer.handle [as handle_request] (/Users/hgeldenhuys/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/hgeldenhuys/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/route.js:137:13)```
    
This is perhaps way out of my comfort-zone to tackle and too big of an issue. I might just go back to SPAs for now until this is easy enough for the avg developer to troubleshoot
