### ISSUE TITLE
Create-Remix not working

### ISSUE THREAD

**Issue by ZetraDev** [remix-run/remix#2714]
### What version of Remix are you using?

/

### Steps to Reproduce

yarn create remix > YOUR_PATH > Just the basic > Cloudflare Pages > TypeScript > No
using npx still cause error
using other deploy target also cause error

### Expected Behavior

Work

### Actual Behavior

It returns an error:
```🚨 The provided template must be a Remix project with a `package.json` file, but that file does not exist in D:\Project\test-remix\package.json```

**Comment by anantoghosh** [comment]
https://github.com/remix-run/remix/discussions/2709#discussioncomment-2539300

Seems like it only affects windows. @kentcdodds.

**Comment by machour** [comment]
Tracked in #2691 
For now you can use `npx create-remix@1.3.4`

**Comment by anantoghosh** [comment]
@machour that looks like an unrelated issue. This issue is related to npx create-remix tar extraction skipping all files.

quote from the discussion
https://github.com/remix-run/remix/blob/7d799e2b6d71f5d7ff572addca623545f975af96/packages/remix-dev/cli/create.ts#L255-L271
At least on windows, header.name.startsWith(filePath) is always false causing all files to get ignored.

**Comment by machour** [comment]
ReOpening so that @mcansh can take a look

**Comment by SangeetAgarwal** [comment]
I'm seeing the same issue on my windows machine, strangely enough, the `pre-configured stack, ready for production` works just fine

**Comment by codthing** [comment]
> Tracked in #2691 For now you can use `npx create-remix@1.3.4`

I don't understand why it's not friendly to Window users, it seems that only Apple is you guys choice.

**Comment by kentcdodds** [comment]
> I don't understand why it's not friendly to Window users, it seems that only Apple is you guys choice.

This is a bug. It's not intentional. It will be fixed.

**Comment by mmattbtw** [comment]
> I don't understand why it's not friendly to Window users, it seems that only Apple is you guys choice.

I'd recommend just using WSL for the meantime.

**Comment by chaance** [comment]
Anyone on Windows able to give the latest pre-release a run and see if it fixes your issues?

```sh
npx create-remix@1.4.1-pre.1
```

**Comment by washedupdeveloper** [comment]
> Anyone on Windows able to give the latest pre-release a run and see if it fixes your issues?
> 
> ```shell
> npx create-remix@1.4.1-pre.1
> ```

I am able to get it working just fine, having created the remix app server deployment option.
![image](https://user-images.githubusercontent.com/31986015/163858457-d6de7efd-742b-4cd5-aa76-2ca2d276ab1f.png)

**Comment by leefisher** [comment]
I still have similar issue
C:\Code>npx create-remix@1.4.1-pre.1
Need to install the following packages:
  create-remix@1.4.1-pre.1
Ok to proceed? (y) Y
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
? Where would you like to create your app? remix-jokes
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure; it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
- Creating your app…🚨 The provided template must be a Remix project with a `package.json` file, but that file does not exist in C:\Code\remix-jokes\package.json.
npm notice
npm notice New minor version of npm available! 8.6.0 -> 8.7.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.7.0
npm notice Run npm install -g npm@8.7.0 to update!
npm notice

**Comment by chaance** [comment]
@leefisher Can you run it again with `1.4.1-pre.2` and this time pass the `--debug` flag? I want to see what kind of template it works out for you. If you select `Remix App Server` it should log this:

```sh
🔍 Using the remix template from the remix-run/remix repo
```

**Comment by leefisher** [comment]
It didn't seem to log that, but I did get this output

```
C:\Code>npx create-remix@1.4.1-pre.2 --debug
? Where would you like to create your app? remix-jokes
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure; it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
/ Creating your app…Error: 🚨 The provided template must be a Remix project with a `package.json` file, but that file does not exist in C:\Code\remix-jokes\package.json.
    at Object.createApp (C:\Users\USER\AppData\Roaming\npm\node_modules\create-remix\node_modules\@remix-run\dev\cli\create.js:160:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.create (C:\Users\USER\AppData\Roaming\npm\node_modules\create-remix\node_modules\@remix-run\dev\cli\commands.js:74:3)
    at async Object.run (C:\Users\USER\AppData\Roaming\npm\node_modules\create-remix\node_modules\@remix-run\dev\cli\run.js:377:9)
```

**Comment by chaance** [comment]
@leefisher Thanks a ton. Sorry to keep bugging you, but could you try once more with `1.4.1-pre.3`? None of us are able to reproduce the issue so your help is very much appreciated!

**Comment by leefisher** [comment]
I'm happy to help!
I don't really see any change here I'm afraid.
```
C:\Code>npx create-remix@1.4.1-pre.3 --debug
Need to install the following packages:
  create-remix@1.4.1-pre.3
Ok to proceed? (y) y
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
? Where would you like to create your app? remix-jokes
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure; it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
- Creating your app…Error: 🚨 The provided template must be a Remix project with a `package.json` file, but that file does not exist in C:\Code\remix-jokes\package.json.
    at Object.createApp (C:\Users\USER\AppData\Roaming\npm\node_modules\create-remix\node_modules\@remix-run\dev\cli\create.js:160:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.create (C:\Users\USER\AppData\Roaming\npm\node_modules\create-remix\node_modules\@remix-run\dev\cli\commands.js:74:3)
    at async Object.run (C:\Users\USER\AppData\Roaming\npm\node_modules\create-remix\node_modules\@remix-run\dev\cli\run.js:377:9)
```

**Comment by kiliman** [comment]
@leefisher Just to be sure, do you already have a folder named `remix-jokes`?

**Comment by mcansh** [comment]
hm these questions seem out of order/date, the "TypeScript or JavaScript?" question should come after the app is created 🤨

**Comment by mcansh** [comment]
> @leefisher Just to be sure, do you already have a folder named `remix-jokes`?

i think we changed our order of things to use a remote template before a local one

**Comment by chaance** [comment]
@leefisher Yeah the ordering of questions is fishy to me too. Wondering if you have an npx caching issue here. Maybe try clearing it? 

```
npx clear-npx-cache
```

If that doesn't work, you might need to nuke the `_npx` directory altogether (`<ROOT>/npm-cache/_npx` on Windows, I think)

**Comment by kiliman** [comment]
BTW: It's working for me on Windows
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/47168/163873450-4a7297a0-13a5-4a20-ba2f-f28327f1c1de.png">

**Comment by leefisher** [comment]
Thanks for the feedback. 
There is currently no remix-jokes folder.
I tried npx clearing cache but no real change.
I'll try deleting cache folder completely.

```
C:\Code>npx clear-npx-cache
Need to install the following packages:
  clear-npx-cache
Ok to proceed? (y) y

C:\Code>npx create-remix@1.4.1-pre.3 --debug
Need to install the following packages:
  create-remix@1.4.1-pre.3
Ok to proceed? (y) y
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
? Where would you like to create your app? remix-jokes
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure; it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
- Creating your app…Error: 🚨 The provided template must be a Remix project with a `package.json` file, but that file does not exist in C:\Code\remix-jokes\package.json.
    at Object.createApp (C:\Users\USER\AppData\Roaming\npm\node_modules\create-remix\node_modules\@remix-run\dev\cli\create.js:160:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.create (C:\Users\USER\AppData\Roaming\npm\node_modules\create-remix\node_modules\@remix-run\dev\cli\commands.js:74:3)
    at async Object.run (C:\Users\USER\AppData\Roaming\npm\node_modules\create-remix\node_modules\@remix-run\dev\cli\run.js:377:9)
```

**Comment by leefisher** [comment]
I clobbered the npm-cache directory.
It installed again but order of questions has not changed.
strange!
```
C:\Code>npx create-remix@1.4.1-pre.3 --debug
Need to install the following packages:
  create-remix@1.4.1-pre.3
Ok to proceed? (y) y
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
? Where would you like to create your app? remix-141p3
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure; it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
| Creating your app…Error: 🚨 The provided template must be a Remix project with a `package.json` file, but that file does not exist in C:\Code\remix-141p3\package.json.
    at Object.createApp (C:\Users\USER\AppData\Roaming\npm\node_modules\create-remix\node_modules\@remix-run\dev\cli\create.js:160:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.create (C:\Users\USER\AppData\Roaming\npm\node_modules\create-remix\node_modules\@remix-run\dev\cli\commands.js:74:3)
    at async Object.run (C:\Users\USER\AppData\Roaming\npm\node_modules\create-remix\node_modules\@remix-run\dev\cli\run.js:377:9)
npm notice
npm notice New minor version of npm available! 8.6.0 -> 8.7.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.7.0
npm notice Run npm install -g npm@8.7.0 to update!
npm notice
```

**Comment by chaance** [comment]
Thanks @leefisher, and very sorry for the frustration here! We may move forward with the release for others, but I'll keep this open until we can eliminate any issues on our end.

**Comment by chaance** [comment]
For everyone else who isn't having issues, I just released `v1.4.1` stable so `npx create-remix@latest` should work as expected moving forward. We also now have tests in place for this so hopefully we won't have any regressions moving forward 😬

**Comment by machour** [comment]
@chaance another error-case reported here for the pre-release: https://github.com/remix-run/remix/discussions/2709#discussioncomment-2588823

**Comment by ZetraDev** [comment]
I have tried `npx create-remix@latest` and it works for me

**Comment by chaance** [comment]
> @chaance another error-case reported here for the pre-release: [#2709 (reply in thread)](https://github.com/remix-run/remix/discussions/2709#discussioncomment-2588823)

This is because you're running an old version of Node that doesn't support `String.prototype.replaceAll`. We'll fix that in #2867 but I'd recommend using [at least] Node 14 if you can :)

**Comment by RATIU5** [comment]
I am getting the same error on Windows when using WSL with the latest release.

> Windows 11
> Ubuntu 18.04 LTS
> Node 16.14.2
> create-remix@latest and create-remix@1.4.1

```
? Where would you like to create your app? ./my-remix-app
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure; it's easy to change deployment targets. Remix App Server
? Do you want me to run `npm install`? No
⠼ Creating your app…🚨 There was a problem extracting the file from the provided template.
```

**Comment by th317erd** [comment]
I have another (possibly related issue) on Ubuntu 18.04. I selected "Javascript" instead of TS, which may be what the problem is here? I see the file `prisma/seed.js`, but the scripts are trying to find `prisma/seed.ts`... can anyone help?

```
wyatt@wyatt-home:~/Projects$ npx create-remix --template remix-run/indie-stack love.me
Need to install the following packages:
  create-remix
Ok to proceed? (y) y
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
? Do you want me to run `npm install`? Yes
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated

> postinstall
> remix setup node

Missing the "remix" package. Please run `npm install remix` before `remix setup`.
Successfully setup Remix for node.

added 1329 packages, and audited 1330 packages in 40s

228 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
? TypeScript or JavaScript? JavaScript
💿 Running remix.init script

> setup
> prisma migrate dev && prisma db seed

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "data.db" at "file:./data.db?connection_limit=1"

SQLite database data.db created at file:./data.db?connection_limit=1

Applying migration `20220307190657_init`

The following migration(s) have been applied:

migrations/
  └─ 20220307190657_init/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (3.11.1 | library) to ./node_modules/@prisma/client in 50ms


Running seed command `ts-node --require tsconfig-paths/register prisma/seed.ts` ...
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './seed.ts'
Require stack:
- /home/wyatt/Projects/love.me/prisma/imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at requireResolveNonCached (/home/wyatt/Projects/love.me/node_modules/ts-node/dist/bin.js:489:16)
    at getProjectSearchDir (/home/wyatt/Projects/love.me/node_modules/ts-node/dist/bin.js:459:40)
    at phase3 (/home/wyatt/Projects/love.me/node_modules/ts-node/dist/bin.js:263:27)
    at bootstrap (/home/wyatt/Projects/love.me/node_modules/ts-node/dist/bin.js:44:30)
    at main (/home/wyatt/Projects/love.me/node_modules/ts-node/dist/bin.js:32:12)
    at Object.<anonymous> (/home/wyatt/Projects/love.me/node_modules/ts-node/dist/bin.js:519:5)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/wyatt/Projects/love.me/prisma/imaginaryUncacheableRequireResolveScript'
  ]
}

An error occured while running the seed command:
Error: Command failed with exit code 1: ts-node --require tsconfig-paths/register prisma/seed.ts


Environment variables loaded from .env
Running seed command `ts-node --require tsconfig-paths/register prisma/seed.ts` ...
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './seed.ts'
Require stack:
- /home/wyatt/Projects/love.me/prisma/imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at requireResolveNonCached (/home/wyatt/Projects/love.me/node_modules/ts-node/dist/bin.js:489:16)
    at getProjectSearchDir (/home/wyatt/Projects/love.me/node_modules/ts-node/dist/bin.js:459:40)
    at phase3 (/home/wyatt/Projects/love.me/node_modules/ts-node/dist/bin.js:263:27)
    at bootstrap (/home/wyatt/Projects/love.me/node_modules/ts-node/dist/bin.js:44:30)
    at main (/home/wyatt/Projects/love.me/node_modules/ts-node/dist/bin.js:32:12)
    at Object.<anonymous> (/home/wyatt/Projects/love.me/node_modules/ts-node/dist/bin.js:519:5)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/wyatt/Projects/love.me/prisma/imaginaryUncacheableRequireResolveScript'
  ]
}

An error occured while running the seed command:
Error: Command failed with exit code 1: ts-node --require tsconfig-paths/register prisma/seed.ts
🚨 Oops, remix.init failed

Command failed: npm run setup
```

**Comment by mcansh** [comment]
> I have another (possibly related issue) on Ubuntu 18.04. I selected "Javascript" instead of TS, which may be what the problem is here? I see the file `prisma/seed.js`, but the scripts are trying to find `prisma/seed.ts`... can anyone help?

that's not so much related, but we need to tweak our remix.init on the stacks to update some scripts to point to `prisma/seed.js` (and other js files) instead of `prisma/seed.ts`

**Comment by RATIU5** [comment]
This version is now working for me on WSL in the Linux sub-system directory and on mounted device directories.

**Comment by 9mean2** [comment]
Remix previous version installation error

There was no error when installing the latest version of Remix, but if you proceed with npx create-remix@1.15.0 as shown below, the installation fails with the error below.

"Creating your app…🚨 The provided template must be a Remix project with a package.json file, but that file does not exist in /home/goomin/desktop/test/app/package.json."

What should I do and what is the problem? 😖

I tried it on Mac and Ubuntu, but it still shows the same error.
```
npx create-remix@1.15.0
? Where would you like to create your app? ./
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's 
easy to change deployment targets. Vercel
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
⠧ Creating your app…🚨 The provided template must be a Remix project with a `package.json` file, but that file does not exist in /home/goomin/바탕화면/test/package.json.
```

**Comment by 9mean2** [comment]
> 리믹스 이전 버전 설치 오류
> 
> 최신 버전의 Remix 설치 시 오류가 발생하지 않았으나, 아래와 같이 npx create-remix@1.15.0으로 진행하면 아래와 같은 오류가 발생하며 설치가 실패합니다.
> 
> "앱 만들기…🚨 제공된 템플릿은 package.json 파일이 있는 Remix 프로젝트여야 하지만 해당 파일이 /home/goomin/desktop/test/app/package.json에 존재하지 않습니다."
> 
> 어떻게 해야 하며 무엇이 문제입니까? 😖
> 
> Mac과 Ubuntu에서 시도했지만 여전히 동일한 오류가 표시됩니다.
> 
> ```
> npx create-remix@1.15.0
> ? Where would you like to create your app? ./
> ? What type of app do you want to create? Just the basics
> ? Where do you want to deploy? Choose Remix App Server if you're unsure; it's 
> easy to change deployment targets. Vercel
> ? TypeScript or JavaScript? TypeScript
> ? Do you want me to run `npm install`? Yes
> ⠧ Creating your app…🚨 The provided template must be a Remix project with a `package.json` file, but that file does not exist in /home/goomin/바탕화면/test/package.json.
> ```

If you select the vercel server, an error will appear.

Remix
When I selected App Server, the installation went well without any errors.

 But how can I get rid of this error if I need to use vercel server?
