### ISSUE TITLE
LiveReload breaks production with react 18

### ISSUE THREAD

**Issue by DAlperin** [remix-run/remix#2776]
### What version of Remix are you using?

1.3.4

### Steps to Reproduce

1. Have an app
2. Develop app in development mode
3. Switch to production (`cross-env NODE_ENV=production remix-serve build`)
4. LiveReload breaks the render resulting in a blank screen

### Expected Behavior

LiveReload should not break production

### Actual Behavior

The screen flashes the correct content (I think probably the server rendering) but then disappears. When looking at the dev tools, all children of `body` have disappeared. The console then logs several errors most notably:
```
Warning: Expected server HTML to contain a matching <script> in <body>.
    at script
    at LiveReload2 (http://localhost:3000/build/_shared/chunk-FMOYLMYS.js:2232:3)
    at body
    at html
    at App (http://localhost:3000/build/_shared/chunk-SFXPWZ4C.js:6143:18)
    at ThemeProvider2 (http://localhost:3000/build/_shared/chunk-SFXPWZ4C.js:93:31)
    at AppWithProviders (http://localhost:3000/build/_shared/chunk-SFXPWZ4C.js:6136:16)
    at RemixRoute (http://localhost:3000/build/_shared/chunk-FMOYLMYS.js:1639:3)
    at Routes (http://localhost:3000/build/_shared/chunk-FMOYLMYS.js:1622:7)
    at Router (http://localhost:3000/build/_shared/chunk-6E4C6WK5.js:686:15)
    at RemixCatchBoundary (http://localhost:3000/build/_shared/chunk-FMOYLMYS.js:132:10)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-FMOYLMYS.js:57:5)
    at RemixEntry (http://localhost:3000/build/_shared/chunk-FMOYLMYS.js:1519:12)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-FMOYLMYS.js:2280:27)
Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:14344:9)
    at tryToClaimNextHydratableInstance (react-dom.development.js:14357:7)
    at updateHostComponent$1 (react-dom.development.js:20636:5)
    at beginWork (react-dom.development.js:22373:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4157:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4206:16)
    at invokeGuardedCallback (react-dom.development.js:4270:31)
    at beginWork$1 (react-dom.development.js:27243:7)
    at performUnitOfWork (react-dom.development.js:26392:12)
    at workLoopSync (react-dom.development.js:26303:5)
```

**Comment by DAlperin** [comment]
Gating it with `{process.env.NODE_ENV === "development" ? <LiveReload /> : null}` works but the docs say that it is fine to leave in since it will only do anything in development. If that is no longer true, the docs should probably be updated to reflect that.

**Comment by machour** [comment]
You mean hydration right? LiveReload shouldn't be involved at all in production

**Comment by DAlperin** [comment]
> You mean hydration right? LiveReload shouldn't be involved at all in production

When hydrating in a production build the problem is present. When hydrating in a development build, there is no issue.

**Comment by pcattori** [comment]
Building and running a Remix app should be done using the same `NODE_ENV`.

@DAlperin feel free to reopen if you have a use-case for needing to build in `development` but run in `production`.
