### ISSUE TITLE
Multiple errors after upgrade to 1.3.5

### ISSUE THREAD

**Issue by jasonabullard** [remix-run/remix#2792]
### What version of Remix are you using?

1.3.5

### Steps to Reproduce

Note: You must have created a firebase application and downloaded the service account json file, as well as adding ```GOOGLE_APPLICATION_CREDENTIALS="serviceAccount.json"``` to a ```.env``` file

1. Create new remix package ```yarn create remix firebase-remix``` using the Remix App server
2. Install firebase-admin ```yarn add firebase-admin```
3. Add FirebaseAdmin.ts and insert the following:

```
import { applicationDefault, getApp, initializeApp } from 'firebase-admin/app';

import type { App } from 'firebase-admin/app';

// Admin app instance
let app: App;

try {
  app = getApp();
} catch {
  app = initializeApp({
    credential: applicationDefault(),
  });
}

export { app };
```

4. Import the app into ```routes/index.tsx``` 

```
import '~/utils/FirebaseAdmin';

export default function Index() {
  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', lineHeight: '1.4' }}>
      <h1>Welcome to Remix</h1>
      <ul>
        <li>
          <a
            target='_blank'
            href='https://remix.run/tutorials/blog'
            rel='noreferrer'
          >
            15m Quickstart Blog Tutorial
          </a>
        </li>
        <li>
          <a
            target='_blank'
            href='https://remix.run/tutorials/jokes'
            rel='noreferrer'
          >
            Deep Dive Jokes App Tutorial
          </a>
        </li>
        <li>
          <a target='_blank' href='https://remix.run/docs' rel='noreferrer'>
            Remix Docs
          </a>
        </li>
      </ul>
    </div>
  );
}
```

### Expected Behavior

Expected behavior is that no errors are thrown.

### Actual Behavior

The following is outputted:

```
➜  remix-firebase-admin yarn dev
yarn run v1.22.17
$ remix dev
Loading environment variables from .env
Watching Remix app in development mode...
▲ [WARNING] Ignoring this import because "app/utils/FirebaseAdmin.ts" was marked as having no side effects

    route:/Users/jason/Projects/remix-firebase-admin/app/routes/index.tsx:1:7:
      1 │ import '~/utils/FirebaseAdmin';
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~

  "sideEffects" is false in the enclosing "package.json" file

    package.json:6:2:
      6 │   "sideEffects": false,
        ╵   ~~~~~~~~~~~~~


✘ [ERROR] [plugin server-bare-modules] Package subpath './package.json' is not defined by "exports" in /Users/jason/Projects/remix-firebase-admin/node_modules/firebase-admin/package.json

    node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:125:32:
      125 │   let packageJsonFile = require.resolve(`${packageName}/package.j...
          ╵                                 ^

    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:453:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:729:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at warnOnceIfEsmOnlyPackage (/Users/jason/Projects/remix-firebase-admin/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:125:33)
    at /Users/jason/Projects/remix-firebase-admin/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:95:11
    at callback (/Users/jason/Projects/remix-firebase-admin/node_modules/esbuild/lib/main.js:920:34)

  This error came from the "onResolve" callback registered here:

    node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:46:12:
      46 │       build.onResolve({
         ╵             ~~~~~~~~~

    at setup (/Users/jason/Projects/remix-firebase-admin/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:46:13)
    at handlePlugins (/Users/jason/Projects/remix-firebase-admin/node_modules/esbuild/lib/main.js:842:23)

  The plugin "server-bare-modules" was triggered by this import

    app/utils/FirebaseAdmin.ts:1:58:
      1 │ ...licationDefault, getApp, initializeApp } from 'firebase-admin/app';
        ╵                                                  ~~~~~~~~~~~~~~~~~~~~


Build failed with 1 error:
node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:125:32: ERROR: [plugin: server-bare-modules] Package subpath './package.json' is not defined by "exports" in /Users/jason/Projects/remix-firebase-admin/node_modules/firebase-admin/package.json
💿 Built in 465ms
```

I have also tried to change package.json to include ```sideEffects: true``` but it just removes the error about that particular change and still produces the other errors.

The weird thing is that I've tried to install 1.3.4 and it produces the same error.  However, I've got another project that I started a week ago that uses 1.3.4 and doesn't produce any errors.

**Comment by jasonabullard** [comment]
So I was finally able to track this down and it all stems from firebase-admin not export package.json.

```
exports: {
....
"./package.json": "./package.json"
}
```

Doing this fixes the errors. However, I'm not sure why it all of sudden broke when the two have been working fine over the last few weeks.

**Comment by machour** [comment]
1.3.5 introduced a bug that should be fixed in the upcoming release. Can you try the experimental release mentioned in #2691 and tell us if it fixes your issue?

**Comment by jasonabullard** [comment]
Awesome, can confirm that the experimental fixes the issue for firebase-admin.
