### ISSUE TITLE
remix 1.4.0 breaks integration with turborepo & workspaces libraries

### ISSUE THREAD

**Issue by nareshbhatia** [remix-run/remix#2836]
### What version of Remix are you using?

1.4.0

### Steps to Reproduce

Here's my sample repo which is working with remix 1.3.5: https://github.com/nareshbhatia/custom-react-stack.

Build & run to make sure everything is working ok:

```bash
npm install
npm run dev
```

Point your browser to the remix app at http://localhost:3002/.

Now change remix dependencies to 1.4.0 in `apps/movie-magic-remix/package.json`. Do a clean build and run.

```bash
npm run clean
rm package-lock.json
npm install
npm run dev
```

### Expected Behavior

Build does not produce any errors and application runs.

### Actual Behavior

Build produces the following error and application does not run. Note that `packages/ui-lib` is a library package in the monorepo. The remix server is not able to resolve its path.

```
movie-magic-remix:dev: ✘ [ERROR] [plugin server-bare-modules] Couldn't resolve the base path of "ui-lib". Searched inside the resolved main file path "/Users/naresh/projects/custom-react-stack/packages/ui-lib/dist/index.js" using "node_modules/ui-lib"
movie-magic-remix:dev:
movie-magic-remix:dev:     ../../node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:181:10:
movie-magic-remix:dev:       181 │     throw new Error(`Couldn't resolve the base path of "${package...
movie-magic-remix:dev:           ╵           ^
movie-magic-remix:dev:
movie-magic-remix:dev:     at resolveModuleBasePath (/Users/naresh/projects/custom-react-stack/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:181:11)
movie-magic-remix:dev:     at warnOnceIfEsmOnlyPackage (/Users/naresh/projects/custom-react-stack/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:126:20)
movie-magic-remix:dev:     at /Users/naresh/projects/custom-react-stack/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:96:11
movie-magic-remix:dev:     at callback (/Users/naresh/projects/custom-react-stack/node_modules/esbuild/lib/main.js:920:34)
movie-magic-remix:dev:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
movie-magic-remix:dev:     at handleRequest (/Users/naresh/projects/custom-react-stack/node_modules/esbuild/lib/main.js:700:30)
movie-magic-remix:dev:
movie-magic-remix:dev:   This error came from the "onResolve" callback registered here:
movie-magic-remix:dev:
movie-magic-remix:dev:     ../../node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:47:12:
movie-magic-remix:dev:       47 │       build.onResolve({
movie-magic-remix:dev:          ╵             ~~~~~~~~~
movie-magic-remix:dev:
movie-magic-remix:dev:     at setup (/Users/naresh/projects/custom-react-stack/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:47:13)
movie-magic-remix:dev:     at handlePlugins (/Users/naresh/projects/custom-react-stack/node_modules/esbuild/lib/main.js:842:23)
movie-magic-remix:dev:
movie-magic-remix:dev:   The plugin "server-bare-modules" was triggered by this import
movie-magic-remix:dev:
movie-magic-remix:dev:     route:/Users/naresh/projects/custom-react-stack/apps/movie-magic-remix/app/routes/__layout/index.tsx:5:26:
movie-magic-remix:dev:       5 │ import { MovieList } from 'ui-lib';
movie-magic-remix:dev:         ╵                           ~~~~~~~~
movie-magic-remix:dev:
movie-magic-remix:dev:  ✘ [ERROR] [plugin server-bare-modules] Couldn't resolve the base path of "ui-lib". Searched inside the resolved main file path "/Users/naresh/projects/custom-react-stack/packages/ui-lib/dist/index.js" using "node_modules/ui-lib"
movie-magic-remix:dev:
movie-magic-remix:dev:     ../../node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:181:10:
movie-magic-remix:dev:       181 │     throw new Error(`Couldn't resolve the base path of "${package...
movie-magic-remix:dev:           ╵           ^
movie-magic-remix:dev:
movie-magic-remix:dev:     at resolveModuleBasePath (/Users/naresh/projects/custom-react-stack/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:181:11)
movie-magic-remix:dev:     at warnOnceIfEsmOnlyPackage (/Users/naresh/projects/custom-react-stack/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:126:20)
movie-magic-remix:dev:     at /Users/naresh/projects/custom-react-stack/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:96:11
movie-magic-remix:dev:     at callback (/Users/naresh/projects/custom-react-stack/node_modules/esbuild/lib/main.js:920:34)
movie-magic-remix:dev:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
movie-magic-remix:dev:     at handleRequest (/Users/naresh/projects/custom-react-stack/node_modules/esbuild/lib/main.js:700:30)
movie-magic-remix:dev:
movie-magic-remix:dev:   This error came from the "onResolve" callback registered here:
movie-magic-remix:dev:
movie-magic-remix:dev:     ../../node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:47:12:
movie-magic-remix:dev:       47 │       build.onResolve({
movie-magic-remix:dev:          ╵             ~~~~~~~~~
movie-magic-remix:dev:
movie-magic-remix:dev:     at setup (/Users/naresh/projects/custom-react-stack/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:47:13)
movie-magic-remix:dev:     at handlePlugins (/Users/naresh/projects/custom-react-stack/node_modules/esbuild/lib/main.js:842:23)
movie-magic-remix:dev:
movie-magic-remix:dev:   The plugin "server-bare-modules" was triggered by this import
movie-magic-remix:dev:
movie-magic-remix:dev:     route:/Users/naresh/projects/custom-react-stack/apps/movie-magic-remix/app/routes/__layout/settings.tsx:5:34:
movie-magic-remix:dev:       5 │ import { Button, MovieList } from 'ui-lib';
movie-magic-remix:dev:         ╵                                   ~~~~~~~~
```

**Comment by marwan38** [comment]
Same issue, I am installing a dependency using the fs resolution `package: "file:../../package"`. Pinning to 1.3.5 fixed it.

**Comment by deimyts** [comment]
I think this might be related to #2845, which I submitted as a separate issue since the use case is a little different, but it looks like the same bug.

**Comment by frago12** [comment]
I found this same issue using npm workspaces

**Comment by frago12** [comment]
> I found this same issue using npm workspaces

I upgraded Remix to `1.4.3`, and the issue was fixed for me. I just had to add this to my `remix.config.js` https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages
