### ISSUE TITLE
create-remix fails to download

### ISSUE THREAD

**Issue by ggascoigne** [remix-run/remix#3030]
### What version of Remix are you using?

1.4.3

### Steps to Reproduce

```
npx create-remix@latest
? Where would you like to create your app? ./remix-test1
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure; it's easy to change deployment targets. Remix App Server
? Do you want me to run `npm install`? Yes
⠹ Creating your app…🚨 There was a problem fetching the file from GitHub. The request responded with a 404 status. Please try again later.
```

with a bit of hacking, it's trying to download `https://codeload.github.com/remix-run/remix/tar.gz/main` and this is failing.

Every other config I've tries also fails.

### Expected Behavior

It should create a remix app.

### Actual Behavior

It fails at the first download and hasn't installed anything.

**Comment by ggascoigne** [comment]
Closing this.

I had a GITHUB_TOKEN environment var from our internal github enterprise and it was (not too surprisingly) breaking the downloads.

The only thing that would have made this easier to diagnose would have been if there'd been a 401 in the error rather than a 404.  The 404 made it look like a path issue rather than an auth error.

**Comment by cliffordfajardo** [comment]
Looks like this is happening here too: https://github.com/kentcdodds/onewheel-blog/issues/1

**Comment by Svish** [comment]
Ran into this myself right now:

```
D:\projects>npx create-remix@latest --debug --verbose
? Where would you like to create your app? ./my-remix-app
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
- Creating your app… 🔍  Using the remix template from the remix-run/remix repo
| Creating your app…Error: 🚨 There was a problem fetching the file from GitHub. The request responded with a 404 status. Please try again later.
    at downloadAndExtractTarball (C:\Users\u\AppData\Local\npm-cache\_npx\5164864a48bff686\node_modules\@remix-run\dev\cli\create.js:277:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async downloadAndExtractRepoTarball (C:\Users\u\AppData\Local\npm-cache\_npx\5164864a48bff686\node_modules\@remix-run\dev\cli\create.js:247:12)
    at async Object.createApp (C:\Users\u\AppData\Local\npm-cache\_npx\5164864a48bff686\node_modules\@remix-run\dev\cli\create.js:150:9)
    at async Object.create (C:\Users\u\AppData\Local\npm-cache\_npx\5164864a48bff686\node_modules\@remix-run\dev\cli\commands.js:76:3)
    at async Object.run (C:\Users\u\AppData\Local\npm-cache\_npx\5164864a48bff686\node_modules\@remix-run\dev\cli\run.js:415:9)
```

Workaround was indeed to remove `GITHUB_TOKEN` from my environment variables. 👍

**Comment by cliffordfajardo** [comment]
@Svish  - how commands in the terminal did you use to remove  the `GITHUB_TOKEN` environment variable?

**Comment by Svish** [comment]
@cliffordfajardo I just used the Environment Variables settings dialog in Windows.
