### ISSUE TITLE
Setting server in remix.config.js fails when using express adapter

### ISSUE THREAD

**Issue by edwin177** [remix-run/remix#3032]
### What version of Remix are you using?

1.4.3

### Steps to Reproduce

1. Create app using `create-remix` (express, just the basics, typescript)
2. Set `server` in `remix.config.js` to let remix produce one consolidated build.
3. `npm run build` works
4. `npm run dev` fails

Sample code here:
https://github.com/edwin177/remix-express/tree/express-server-build

### Expected Behavior

Server should load

### Actual Behavior

App crashes with the following error:

```
/home/xxx/remix-express/node_modules/@remix-run/server-runtime/routes.js:18
  return Object.entries(manifest).filter(([, route]) => route.parentId === parentId).map(([id, route]) => ({ ...route,
                ^
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Object.createRoutes (/home/xxx/remix-express/node_modules/@remix-run/server-runtime/routes.js:18:17)
    at Object.createRequestHandler (/home/xxx/remix-express/node_modules/@remix-run/server-runtime/server.js:26:25)
    at createRequestHandler (/home/xxx/remix-express/node_modules/@remix-run/express/server.js:35:28)
    at Object.<anonymous> (/home/xxx/remix-express/build/index.js:42:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
```

**Comment by edwin177** [comment]
This works fine on v1.3.3.

**Comment by kiliman** [comment]
If you're using the Express adapter, you shouldn't be running `remix dev`. You should be running `remix watch` and `node server.js`.

`remix dev` is basically `remix watch` plus `remix-serve`.

**Comment by edwin177** [comment]
@kiliman Thanks for being so active here and Discord.

You can see in the `package.json` that `npm run dev` only calls `remix watch`:

```
"scripts": {
    "build": "remix build",
    "dev": "remix build && run-p dev:*",
    "dev:node": "cross-env NODE_ENV=development nodemon ./build/index.js --watch ./build/index.js",
    "dev:remix": "remix watch",
    "start": "cross-env NODE_ENV=production node ./build/index.js"
  },
```

This was only slightly modified from the standard output from `create-remix` to call the remix build rather than the original express server.

**Comment by kiliman** [comment]
Sorry, I misread that. Thought you meant `remix dev` not `npm run dev`.

Anyway, tried setting up `server` in config and it doesn't appear to be working at all in 1.4.3.

**Comment by kiliman** [comment]
I never could get `server` config to work, so I punted and now use `esbuild` to bundle server.js. Here are my scripts. nodemon is running `run-s server:*`, so it runs the server build (esbuild) followed by `node build/server.js`. This way any changes you make to server.js will force the npm scripts to re-execute.

You'll see that esbuild outputs to `build/server.js`. `remix watch` generates the `app` files in `build/index.js`, which is imported by server.js. So any changes to route files will trigger a rebuild of `build/index.js` and server.js will pickup the changes after `<LiveReload/>`.

For production, just run `npm run build`. It will create the 2 files: index.js and server.js. Copy those to your host and then run `npm run start`. You won't need to install any node_modules.


```json
  "scripts": {
    "build": "cross-env NODE_ENV=production remix build && npm run server:build",
    "dev": "run-p dev:*",
    "dev:node": "cross-env NODE_ENV=development nodemon --exec \"run-s server:*\"  --watch ./server.js",
    "dev:remix": "remix watch",
    "server:build": "esbuild server.js --outfile=build/server.js --platform=node --format=cjs --bundle --sourcemap",
    "server:start": "node ./build/server.js",
    "start": "cross-env NODE_ENV=production node ./build/server.js"
  },
```

**Comment by edwin177** [comment]
Thanks for confirming that you can't get it to work either.

I'm currently on v1.3.3 which works fine with Express + setting `server` in config, but can't upgrade due to this issue.

I'll take a look at incorporating your example of handling the build directly.

**Comment by ZiiMakc** [comment]
In [fastify ](https://github.com/mcansh/remix-fastify) example `import * as serverBuild from '@remix-run/dev/server-build';` used and then `remix watch` + nodemon can run together

**Comment by CanRau** [comment]
Hmm from the docs

> A server entrypoint, relative to the root directory that becomes your server's main module. If specified, Remix will compile this file along with your application into a single file to be deployed to your server. This file can use either a .js or .ts file extension.

I thought I could just throw in a server.ts but running `node ./build/index.js` & `remix watch` errors

```
[..]/indie-stack/node_modules/@remix-run/express/node_modules/@remix-run/server-runtime/dist/routes.js:18
  return Object.entries(manifest).filter(([, route]) => route.parentId === parentId).map(([id, route]) => ({ ...route,
                ^
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Object.createRoutes ([..]/indie-stack/node_modules/@remix-run/express/node_modules/@remix-run/server-runtime/dist/routes.js:18:17)
    at Object.createRequestHandler ([..]/indie-stack/node_modules/@remix-run/express/node_modules/@remix-run/server-runtime/dist/server.js:26:25)
    at createRequestHandler ([..]/indie-stack/node_modules/@remix-run/express/dist/server.js:34:28)
    at Object.<anonymous> ([..]/indie-stack/build/index.js:42:79)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
```

**Comment by edwin177** [comment]
Btw, still getting the same error with 1.7.0.

Sample code:
https://github.com/edwin177/remix-express-1.7

**Comment by keoy7am** [comment]
This issue is still happening.
(try upgrading from 1.2.3 to 1.7.4 Today)

**Comment by Mando75** [comment]
After some debugging, I was able to determine that this error was happening for me because the default `require(BUILD_DIR)` calls were returning an empty object. Inside the remix request handler, it passes properties from the build object to various handlers. Since `require(BUILD_DIR)` is returning an empty object, those properties are undefined, which eventually manifests as the error message described in this issue. 
![image](https://user-images.githubusercontent.com/5854696/198902514-fd022f70-191b-4b41-bd4f-0b33e44a8a94.png)



I was able to fix this on my end by appending `index.js` (or whatever your remix build output file is) to the `require(BUILD_DIR)` found in `createRequestHandler`. As a note, I am doing an ESBuild setup for my server file, similar to what was described by @/kiliman above. I don't know if this will also fix it for setups using the default Remix 'server' configuration.

![image](https://user-images.githubusercontent.com/5854696/198902545-3638c208-957f-4e78-a08a-f94c8e9f008c.png)

I doubt this is probably an ideal fix, but I wanted to provide what may be a potential workaround for some people, since it seems to be a common issue.

Sample code:

### Original remix request handler

```typescript
const BUILD_DIR = path.join(process.cwd(), "build");

// ... A bunch of express setup stuff

app.all(
  "*",
  process.env.NODE_ENV === "development"
    ? (req, res, next) => {
        purgeRequireCache();

        return createRequestHandler({
          build: require(BUILD_DIR),
          mode: process.env.NODE_ENV,
          getLoadContext,
        })(req, res, next);
      }
    : createRequestHandler({
        build: require(BUILD_DIR),
        mode: process.env.NODE_ENV,
        getLoadContext,
      })
);

```

### A version that worked for me

```typescript
const BUILD_DIR = path.join(process.cwd(), "build");
const BUILD_FILE = path.join(BUILD_DIR, "index.js");

// ... A bunch of express setup stuff

app.all(
  "*",
  process.env.NODE_ENV === "development"
    ? (req, res, next) => {
        purgeRequireCache();

        return createRequestHandler({
          build: require(BUILD_FILE),
          mode: process.env.NODE_ENV,
          getLoadContext,
        })(req, res, next);
      }
    : createRequestHandler({
        build: require(BUILD_FILE),
        mode: process.env.NODE_ENV,
        getLoadContext,
      })
);

```

**Comment by haines** [comment]
I ran into this with Remix 1.8.2. It seems like the problem is twofold.

### Problem 1: overridden entrypoint to esbuild

Setting `server` in `remix.config.js` changes the esbuild config. I think the problem may be here?
  https://github.com/remix-run/remix/blob/8fb82b27bcf7174fcd83dd0fc63d99764ff264c1/packages/remix-dev/compiler/compilerServer.ts#L35-L43

As a result, `build/index.js` only includes things imported from the `server` file. As an extreme example, when the `server` file only includes

```typescript
console.log("wat");
```

then `build/index.js` only includes that:

```javascript
"use strict";

// server.ts
console.log("wat");
```

### Problem 2: cyclic dependencies

If the server is bundled into the same file as the application, this creates a cyclic dependency.

- You run `node build/index.js` to start the server
- `node` requires `build/index.js`
- While loading, it hits the `createRequestHandler` call, and attempts to require `build/index.js`
- `require` returns `{}` to avoid an infinite loop
- `createRoutes` throws because `manifest` is `undefined`

### A workaround that doesn't require creating a separate esbuild step

I worked around these issues by removing `server` from `remix.config.js` and putting the following code in `app/entry.server.tsx`

```typescript
import run from "./run.server";

if (require.main === module) {
  process.nextTick(run);
}
```

The `run` function creates the express app and calls `listen`. Because it runs in the next tick, requiring `build/index.js` does not create a loop.

### Solving the problems

I think if `server` is specified in the config, the compiler needs to produce two files. `build/index.js` would be produced from the `server` file and `build/app.js` would be the application code.

**Comment by mfadlyramadhan** [comment]
I'm relatively new to remix so please correct me if I wrong. I've somehow managed to run the remix with express adapter, setting the `server` in `remix.config.js` to `server.ts`. Then in the `server.ts` I just use the `import * as build from "@remix-run/dev/server-build"`. Here is what I did:
```js
// rest of imports
import * as build from "@remix-run/dev/server-build";

// rest of server.ts

app.all(
  "*",
  process.env.NODE_ENV === "development"
    ? (req, res, next) => {
        purgeRequireCache();

        return createRequestHandler({
          build, // removed the require to BUILD_DIR
          mode: process.env.NODE_ENV,
        })(req, res, next);
      }
    : createRequestHandler({
        build, // removed the require to BUILD_DIR
        mode: process.env.NODE_ENV,
      })
);

// rest of server.ts
```

I don't know if this is the correct way to do it. I have also looked on the other adapter templates and it shows the usage of the `import * as build from "@remix-run/dev/server-build"`.

I'm sorry if my english is bad cause it's not even my second language. Hopefully this helps as a workaround until we have the correct way to do it.

**Comment by brunojppb** [comment]
Hey folks,
for whoever is running into this issue, I've managed to circunvent this problem with a mix of the suggestion from @mfadlyramadhan above and some custom setup I did for running the Express server during local development, including support for hot-module replacement.

i've created a repo here that you can take a look or even use it in case you want to have Remix + Express + development with HMR + Docker builds.

https://github.com/brunojppb/remix-express-typescript

The secret is mostly in the `remix.config.js` to only add the `server` entry during production builds.

```ts
```

**Comment by brunojppb** [comment]
Hey folks,
for whoever is running into this issue, I've managed to circunvent this problem with a mix of the suggestion from @mfadlyramadhan above and some custom setup I did for running the Express server during local development, including support for hot-module replacement.

i've created a repo here that you can take a look or even use it in case you want to have Remix + Express + development with HMR + Docker builds.

https://github.com/brunojppb/remix-express-typescript

The secret is mostly in the `remix.config.js` to only add the `server` entry during production builds as you can see [here](https://github.com/brunojppb/remix-express-typescript/blob/d8151eb3206d1917cc1327d5bdeb20040aa15fbe/remix.config.js#L17C1-L22) which avoids this bug.

```ts
...(isProd
    ? {
        server: "server/prod.ts",
        serverBuildPath: "build/index.js",
      }
    : {}),
```

Then I customised the Express server to have a [dynamic entrypoint](https://github.com/brunojppb/remix-express-typescript/blob/d8151eb3206d1917cc1327d5bdeb20040aa15fbe/server/base.ts#L15-L26) where the development and production setup can be adjusted based on your needs.

1. In development, you have an entrypoint with Remix request handler and HMR replacement hooked up [here.](https://github.com/brunojppb/remix-express-typescript/blob/d8151eb3206d1917cc1327d5bdeb20040aa15fbe/server/dev.ts#L15-L23)
2. In production, you just read the build files generated by the compiler [here.](https://github.com/brunojppb/remix-express-typescript/blob/d8151eb3206d1917cc1327d5bdeb20040aa15fbe/server/prod.ts#L9-L12)

Ideally, would be great if the Remix team could make the `server` entry work smoothly with the entire Express Adapter + TypeScript compilation setup.

Last, but not least, thanks to the Remix team for the incredible work put on this framework! 👏 

CC: @raulfdm @leoweigand @dge808

**Comment by brookslybrand** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!  

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2.  If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.  

We plan to continue to address 2 types of issues in Remix v2:

* Bugs that pose security concerns
* Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new minimal reproduction against v7.

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
