### ISSUE TITLE
Error when trying to crate Remix app

### ISSUE THREAD

**Issue by gunzzblazzing** [remix-run/remix#3048]
### What version of Remix are you using?

Latest

### Steps to Reproduce

1. Create a new folder
2. Execute  nvm use 16.6.1 ( newer version of Node fails with a different error so reverting to a previous version )
3. Execute `npx create-remix@latest`

### Expected Behavior

Create a new remix app

### Actual Behavior

Need to install the following packages:
  create-remix@latest
Ok to proceed? (y) y
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
d:\app-data\node\cache\_npx\5164864a48bff686\node_modules\@remix-run\dev\cli\create.js:26
var sortPackageJSON = require('sort-package-json');
                      ^

Error [ERR_REQUIRE_ESM]: require() of ES Module d:\app-data\node\cache\_npx\5164864a48bff686\node_modules\sort-package-json\index.js from d:\app-data\node\cache\_npx\5164864a48bff686\node_modules\@remix-run\dev\cli\create.js not supported.
Instead change the require of index.js in d:\app-data\node\cache\_npx\5164864a48bff686\node_modules\@remix-run\dev\cli\create.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (d:\app-data\node\cache\_npx\5164864a48bff686\node_modules\@remix-run\dev\cli\create.js:26:23)
    at Object.<anonymous> (d:\app-data\node\cache\_npx\5164864a48bff686\node_modules\@remix-run\dev\cli\commands.js:29:16)
    at Object.<anonymous> (d:\app-data\node\cache\_npx\5164864a48bff686\node_modules\@remix-run\dev\cli\run.js:24:16)
    at Object.<anonymous> (d:\app-data\node\cache\_npx\5164864a48bff686\node_modules\@remix-run\dev\cli\index.js:15:11)
    at Object.<anonymous> (d:\app-data\node\cache\_npx\5164864a48bff686\node_modules\@remix-run\dev\index.js:15:13)
    at Object.<anonymous> (d:\app-data\node\cache\_npx\5164864a48bff686\node_modules\create-remix\cli.js:14:11) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by rabilrbl** [comment]
#3044

**Comment by kenlck** [comment]
Please refer to this issue #3044. There is a workaround for this.

**Comment by gunzzblazzing** [comment]
I've managed to get this working by adding the following in `package.json`

`  "resolutions": {
    "sort-package-json": "1.55.0"
  }
`
