### ISSUE TITLE
Documentation - Gotchas - fs-extra example does not work for typescript

### ISSUE THREAD

**Issue by gunzzblazzing** [remix-run/remix#3051]
### What version of Remix are you using?

Latest

### Steps to Reproduce

1. Create fs-extra.server.ts file in utils with the following content.
```
export * from "fs-extra";
```

2. In index.tsx
```
import fs from "../utils/fs-extra.server";
```

3. VS Code complains utils file has no default exports.

4. Executing the code produces the following error
```
Uncaught (in promise) TypeError: import_fs_extra.default.pathExistsSync is not a function
    at deleteFile (index.tsx:40:29)
    at onClick (index.tsx:62:34)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:25)
    at executeDispatch (react-dom.development.js:8243:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:7)
    at processDispatchQueue (react-dom.development.js:8288:5)
    at dispatchEventsForPlugins (react-dom.development.js:8299:3)
```

5. Update  fs-extra.server.ts to 
 ```
export * as default from "fs-extra";
```

6. VS Code warning goes away

7. Executing the code produces the same error as Step 4.

The line that produces the error:

```
const isFilePresent = await fs.pathExistsSync(path);
```

NOTE: I have installed the latest version @types/fs-extra package as well.

### Expected Behavior

Expecting the following code to return a Boolean value

```
const isFilePresent = await fs.pathExistsSync(path);
```

### Actual Behavior

Executing the code produces the following error
```
Uncaught (in promise) TypeError: import_fs_extra.default.pathExistsSync is not a function
    at deleteFile (index.tsx:40:29)
    at onClick (index.tsx:62:34)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:25)
    at executeDispatch (react-dom.development.js:8243:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:7)
    at processDispatchQueue (react-dom.development.js:8288:5)
    at dispatchEventsForPlugins (react-dom.development.js:8299:3)
```

**Comment by machour** [comment]
For reference, the concerned documentation section: https://remix.run/docs/en/v1/pages/gotchas#server-code-in-client-bundles
