### ISSUE TITLE
`serverDependenciesToBundle` fails in v1.5.1 with RegExps

### ISSUE THREAD

**Issue by ZipBrandon** [remix-run/remix#3251]
### What version of Remix are you using?

1.5.1

### Steps to Reproduce

Do something similar to https://remix.run/docs/en/v1/api/conventions#serverdependenciestobundle 
```js
module.exports = {
  appDirectory: "app",
  assetsBuildDirectory: "public/build",
  publicPath: "/build/",
  serverBuildDirectory: "build",
  ignoredRouteFiles: ["**/.*"],
  serverDependenciesToBundle: [
    /^rehype.*/,
    /^remark.*/,
    /^unified.*/,
    "@sindresorhus/slugify",
  ],
};
```

### Expected Behavior

Remix to accept RegExps for ESM exclusion.

### Actual Behavior

```
TypeError [ERR_INVALID_ARG_TYPE]: The "request" argument must be of type string. Received an instance of RegExp
   at Object.readConfig (/home/docker/code/app/node_modules/@remix-run/dev/config.js:67:11)
   at Object.build (/home/docker/code/app/node_modules/@remix-run/dev/cli/commands.js:146:31)
   at Object.run (/home/docker/code/app/node_modules/@remix-run/dev/cli/run.js:468:22)
   at Object.<anonymous> (/home/docker/code/app/node_modules/@remix-run/dev/cli.js:16:11)
   at Module._compile (node:internal/modules/cjs/loader:1103:14)
   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
   at Module.load (node:internal/modules/cjs/loader:981:32)
   at Function.Module._load (node:internal/modules/cjs/loader:822:12)
   at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
   at node:internal/main/run_main_module:17:47
```

**Comment by machour** [comment]
@ZipBrandon just upgraded my app that use RegExps for `serverDependenciesToBundle` and it's working as expected.
Could you setup a minimal reproduce case on a public repository so that we can see what's going on?

**Comment by ZipBrandon** [comment]
Following up on this, this was my error. I had the old API of 

```js
const { getDependenciesToBundle } = require(`@remix-run/dev`);
...

  serverDependenciesToBundle: [
    ...getDependenciesToBundle(
      /rehype.*/,
      /remark.*/,
      /unified.*/,
      /micromark.*/,
      /mdast.*/,
      /react-querybuilder.*/,
      /react-day-picker.*/,
      /react-dnd-html5-backend.*/,
      /@udecode\/plate-ui-dnd.*/,
      /@udecode\/plate.*/,
      /@udecode\/plate-serializer-md.*/,
      `@sindresorhus/slugify`,
      `react-markdown`,
      `micromark-util-symbol`,
      `zwitch`,
      `fault`,
      `ccount`,
      `react-dnd`,
      `parse-entities`,
      `stringify-entities`,
      `hastscript`,
      `ts-invariant`,
      `unist-util-map`,
      `markdown-table`,
      `longest-streak`,
      `vfile`,
      `vfile-message`,
      `@apollo/client`,
      `@sindresorhus/transliterate`,
    ),
  ],
```
