### ISSUE TITLE
Error: Invariant failed: SESSION_SECRET must be set

### ISSUE THREAD

**Issue by MiguelNiblock** [remix-run/remix#3363]
### What version of Remix are you using?

1.5.1

### Steps to Reproduce

npx create-remix
gave it a name
chose "a pre-configured stack ready for prod..."
chose "Grunge" stack
chose "Typescript"
do you want me to run npm install? no
cd into new project directory
yarn
yarn dev
visit localhost:3000
see error

---

  "dependencies": {
    "@architect/architect": "^10.3.3",
    "@architect/functions": "^5.1.0",
    "@remix-run/architect": "^1.5.1",
    "@remix-run/node": "^1.5.1",
    "@remix-run/react": "^1.5.1",
    "@remix-run/server-runtime": "^1.5.1",
    "bcryptjs": "2.4.3",
    "cuid": "^2.1.8",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "tiny-invariant": "^1.2.0"

### Expected Behavior

run dev should load the initial page

### Actual Behavior

getting this error:
```
Error

Process exited with 1

/home/user/MyProjects/remix-samples-rn/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14
    throw new Error(value);
          ^
/home/user/MyProjects/remix-samples-rn/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14
    throw new Error(value);
    ^

Error: Invariant failed: SESSION_SECRET must be set
    at invariant (/home/user/MyProjects/remix-samples-rn/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14:11)
    at Object. (/home/user/MyProjects/remix-samples-rn/app/session.server.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at [eval]:1:336
    at Script.runInThisContext (node:vm:131:12)
```

**Comment by MiguelNiblock** [comment]
this doesn't happen when you say "Yes" to "run npm install?"

**Comment by machour** [comment]
This should be moved to https://github.com/remix-run/grunge-stack/issues

**Comment by iampueroo** [comment]
I'm also having this issue, but for the indie-stack.

I said "no" to "run npm install?" because I wanted to use `yarn`. I ran `yarn setup` and then `yarn dev` and this occurred.

**Comment by machour** [comment]
Just fyi, to use yarn, create the project using `yarn create remix` instead of `npx ...`. The installer will use yarn for subsequent commands.
