### ISSUE TITLE
remix dev --port doesn't work

### ISSUE THREAD

**Issue by machour** [remix-run/remix#3693]
### What version of Remix are you using?

1.6.4

### Steps to Reproduce

./node_modules/.bin/remix dev  --port 3001

### Expected Behavior

App starts on port 3001

### Actual Behavior

```
ArgError: unknown or unexpected option: --port
    at Object.arg [as default] (/Users/didou/dev/machour/remix-yii2-stack/node_modules/arg/index.js:132:13)
    at Object.run (/Users/didou/dev/machour/remix-yii2-stack/node_modules/@remix-run/dev/dist/cli/run.js:200:37)
    at Object.<anonymous> (/Users/didou/dev/machour/remix-yii2-stack/node_modules/@remix-run/dev/dist/cli.js:16:11)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'ARG_UNKNOWN_OPTION'
}```

**Comment by MichaelDeBoey** [comment]
Closed by #3694
