### ISSUE TITLE
create-remix cli run into error when trying to run `npx remix init` 

### ISSUE THREAD

**Issue by Senbonzakura1234** [remix-run/remix#3991]
### What version of Remix are you using?

1.6.7

### Steps to Reproduce

Run create-remix cli with options below:

![image](https://user-images.githubusercontent.com/43206347/184470123-99a242ee-1129-42db-9aed-4efb03951808.png)
****

### Expected Behavior

The cli run remix.init script successfully

### Actual Behavior

The cli run remix.init script run into error

`🚨 Oops, remix.init failed`
`Cannot read properties of undefined (reading 'length')`

**Comment by BenSpencer** [comment]
I am hitting the same issue when running `npx create-remix --template remix-run/indie-stack remix-blog-tutorial`.

Trying to run remix init directly afterwards gives the trace:

```
% npx remix init
TypeError: 🚨 Oops, remix.init failed

Cannot read properties of undefined (reading 'length')
    at parseDocument (/Users/ben/Programming/remix-blog-tutorial/remix.init/node_modules/yaml/dist/public-api.js:45:80)
    at Object.parse (/Users/ben/Programming/remix-blog-tutorial/remix.init/node_modules/yaml/dist/public-api.js:67:17)
    at /Users/ben/Programming/remix-blog-tutorial/remix.init/index.js:142:12
    at async Promise.all (index 7)
    at async main (/Users/ben/Programming/remix-blog-tutorial/remix.init/index.js:133:7)
    at async Object.init (/Users/ben/Programming/remix-blog-tutorial/node_modules/@remix-run/dev/dist/cli/commands.js:129:5)
    at async Object.run (/Users/ben/Programming/remix-blog-tutorial/node_modules/@remix-run/dev/dist/cli/run.js:476:7)
```

I have tried 1.6.8 and 1.6.0 with the same result.

I'm on macOS 12.4 Monteray, with node 18.7.0 and npm/npx 8.15.0 installed via nvm.

When installing the blues stack this step runs ok. Without any stack this step doesn't run, which seems expected.

When running with JavaScript instead of TypeScript on the Indie stack it also works.

As best I can tell the error is coming from 

```
readFileIfNotTypeScript(isTypeScript, DEPLOY_WORKFLOW_PATH, (s) =>
  YAML.parse(s)
)
```

where `DEPLOY_WORKFLOW_PATH` is `.github/workflows/deploy.yml` which does exist and has contents.
