### ISSUE TITLE
Cypress no longer running application after upgrade from Remix 1.6.8 to 1.7.0

### ISSUE THREAD

**Issue by davidlukerice** [remix-run/remix#4073]
### What version of Remix are you using?

1.7.0

### Steps to Reproduce

Create a new indie stack remix application and try to run the cypress tests.
If this is more of an issue for the indie-stack and not a widespread remix issue, I'll recreate the bug there instead.

### Expected Behavior

Running `npm run test:e2e:dev` should be successful

### Actual Behavior

I get the following error and log when running
`npm run test:e2e:dev`
```
> test:e2e:dev
> start-server-and-test dev http://localhost:3000 "npx cypress open"

1: starting server using command "npm run dev"
and when url "[ 'http://localhost:3000' ]" is responding with HTTP status code 200
running tests using command "npx cypress open"


> dev
> run-p dev:*


> dev:css
> npm run generate:css -- --watch


> dev:remix
> cross-env NODE_ENV=development binode --require ./mocks -- @remix-run/dev:remix dev

🔶 Mock server running

> generate:css
> tailwindcss -o ./app/styles/tailwind.css


Rebuilding...
Done in 202ms.
Loading environment variables from .env
Watching Remix app in development mode...
marked is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
💿 Built in 385ms
Remix App Server started at http://localhost:3000 (http://192.168.50.243:3000)
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at entry.server.tsx:25.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at renderElement (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:6109:9)
    at renderNodeDestructiveImpl (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:6142:14)
    at retryTask (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:6594:5)
    at performWork (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:6642:7)
    at Immediate._onImmediate (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:6969:12)
    at processImmediate (node:internal/timers:466:21)
    ```

**Comment by davidlukerice** [comment]
Looks like a fresh install via `npx create-remix --template remix-run/indie-stack` is still working, so I'll have to dig in a bit more about how I've diverged from the indie-stack in my project.

**Comment by MichaelDeBoey** [comment]
I'll close this issue then. 👍

You should use `create-remix@latest` btw

**Comment by davidlukerice** [comment]
🤔 Interesting, it doesn't like spreading a blank object onto a tag
```
<a
    href={item.link}
    {...{}} // A simple case of the below line that breaks things
    // {...(item.external ? { target: '_blank' } : {})}
    key={item.link}
  >
    {item.label}
  </a>
  ```
  
  It's easy enough to work around, but it's odd that the previous Remix React shim supported it fine, but "esbuild's new automatic JSX transformation" does not.

**Comment by davidlukerice** [comment]
Actually, it looks like having a `key` attribute after a spread is breaking things (even when just running `npm run dev`. Which feels like a bug to me.
Builds fine:
```
<a href={item.link} key={item.link} {...{}} >
  {item.label}
</a>
```

Breaks:
```
<a href={item.link} {...{}} key={item.link}>
  {item.label}
</a>
```

**Comment by davidlukerice** [comment]
@MichaelDeBoey It's probably worth reopening in that case? Or is this more a bug on ESBuild's side?

**Comment by chaance** [comment]
@davidlukerice Feel free to open a new issue with a minimal reproduction, if you don't mind. This doesn't seem related at al to Cypress so I'd like to keep the issues clean as much as possible!

**Comment by davidlukerice** [comment]
Looks like someone beat me to it: https://github.com/remix-run/remix/issues/4080
