### ISSUE TITLE
@preact/signals-react causes Invalid hook call

### ISSUE THREAD

**Issue by valotas** [remix-run/remix#4164]
### What version of Remix are you using?

1.7.0

### Steps to Reproduce

Start with an indie stack and add `@preact/signals-react` as a dependency. On the index page make use of signals:

```jsx
import { useSignal } from "@preact/signals-react";

export default function Index() {
  const counter = useSignal(0);

  return (<button onClick={() => counter.value++}>Click {counter.value}</button>)
}
```

### Expected Behavior

Have the button rendered

### Actual Behavior

remix cannot render the route:

```
~/Projects/blog-tutorial/node_modules/react-dom/cjs/react-dom-server.node.development.js:4918
    throw new Error('Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for' + ' one of the following reasons:\n' + '1. You might have mismatching versions of React and the renderer (such as React DOM)\n' + '2. You might be breaking the Rules of Hooks\n' + '3. You might have more than one copy of React in the same app\n' + 'See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.');
          ^
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveCurrentlyRenderingComponent (~/Projects/blog-tutorial/node_modules/react-dom/cjs/react-dom-server.node.development.js:4918:11)
    at Object.useReducer (~/Projects/blog-tutorial/node_modules/react-dom/cjs/react-dom-server.node.development.js:5093:33)
    at Object.set [as current] (~/Projects/blog-tutorial/node_modules/@preact/signals-react/src/index.ts:116:25)
    at performWork (~/Projects/blog-tutorial/node_modules/react-dom/cjs/react-dom-server.node.development.js:6625:36)
    at Immediate.<anonymous> (~/Projects/blog-tutorial/node_modules/react-dom/cjs/react-dom-server.node.development.js:6969:12)
    at processImmediate (node:internal/timers:466:21)
```

**Comment by valotas** [comment]
Here is an [example repo](https://github.com/valotas/remix-with-signals)

**Comment by meetdave3** [comment]
+1 

Here's another [example repo](https://github.com/meetdave3/remix-react-signals). 

Doesn't use the hook but uses the `signal` import and gets the same error message.

**Comment by brophdawg11** [comment]
I think this needs top be opened with the Preact team since it's an error being fired from that library.  The library states:

> Note: The React integration plugs into some React internals and may break unexpectedly in future versions of React

So it doesn't sound like it's guaranteed to work seamlessly with React - let alone with React inside of a server-rendered meta framework.  The Remix team isn't familiar with the internals of this library to debug further.
