### ISSUE TITLE
ErrorBoundary crashes when an error is thrown from a route's action 

### ISSUE THREAD

**Issue by affanshahid** [remix-run/remix#4344]
### What version of Remix are you using?

1.7.2

### Steps to Reproduce

Export an error boundary from your `root.tsx` like:

```tsx
export const ErrorBoundary = function ({ error }) {
  return (
    <html>
      <head>
        <title>Oh no!</title>
        <Meta />
        <Links />
      </head>
      <body>
        {error.message}
        <Scripts />
      </body>
    </html>
  );
};
```

Create a route with an action that can fail, e.g:
```tsx
export const action: ActionFunction = async function ({ request }) {
  await axios.post(process.env.API_URL! + '/auth/logout');
  return destroyUserSession(request);
};

export default function Logout() {
  return <div>Hello</div>;
}
```

Trigger the action route using `useSubmit()`.

### Expected Behavior

If an error occurs in the action, the error boundary should render normally with the error message inside the body.

### Actual Behavior

I get an application error:
```
TypeError: Cannot read properties of undefined (reading 'links')
    at http://localhost:3000/build/_shared/chunk-MPUE4MGI.js:22158:37
    at Array.map (<anonymous>)
    at getLinksForMatches (http://localhost:3000/build/_shared/chunk-MPUE4MGI.js:22155:29)
    at http://localhost:3000/build/_shared/chunk-MPUE4MGI.js:23763:36
    at mountMemo (http://localhost:3000/build/_shared/chunk-MPUE4MGI.js:13333:27)
    at Object.useMemo (http://localhost:3000/build/_shared/chunk-MPUE4MGI.js:13657:24)
    at Object.useMemo (http://localhost:3000/build/_shared/chunk-BPQL3L3K.js:1014:29)
    at Links (http://localhost:3000/build/_shared/chunk-MPUE4MGI.js:23763:22)
    at renderWithHooks (http://localhost:3000/build/_shared/chunk-MPUE4MGI.js:12698:26)
    at mountIndeterminateComponent (http://localhost:3000/build/_shared/chunk-MPUE4MGI.js:15427:21)
```

**Comment by giuseppeg** [comment]
I stumbled upon the same issue, happening when there is an error in an action. I went with a custom html page that doesn't use any of the `Meta` or `Links` components but clearly that's not ideal.

**Comment by brophdawg11** [comment]
Hm, I'm unable to reproduce this.  If this is still an issue on current versions could you provide a reproduction and re-open?  Thanks!
