### ISSUE TITLE
Server crash on multipart file upload containing apostrophe or semicolon

### ISSUE THREAD

**Issue by elledienne** [remix-run/remix#4443]
### What version of Remix are you using?

1.7.2

### Steps to Reproduce

1. Create a file called `something ' something.png` or `something ; something.png` (file extension doesn't really matter
2. Upload the file to a Remix app - I've used the code in the official doc to create a simple `uploadHandler` leveraging `unstable_parseMultipartFormData`

### Expected Behavior

The file is successfully uploaded

### Actual Behavior

The server crashes with the following error

```
Error: malformed content-disposition header: mismatched quotations in `form-data; name="file-upload"; filename="something ' something.png"`
    at parseContentDisposition (/Users/[...]/remix/node_modules/@web3-storage/multipart-parser/cjs/src/index.js:28:13)
    at parsePartHeaders (/Users/[...]/remix/node_modules/@web3-storage/multipart-parser/cjs/src/index.js:50:38)
    at Object.streamMultipart (/Users/[...]/remix/node_modules/@web3-storage/multipart-parser/cjs/src/index.js:169:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at parseMultipartFormData (/Users/[...]/remix/node_modules/@remix-run/server-runtime/dist/formData.js:48:18)
    at action27 (/Users/[...]/remix/app/routes/api/content/index.ts:65:16)
    at /Users/[...]/remix/node_modules/@sentry/remix/cjs/utils/instrumentServer.js:140:13
    at Object.callRouteAction (/Users/[...]/remix/node_modules/@remix-run/server-runtime/dist/data.js:40:14)
    at handleDataRequest (/Users/[...]/remix/node_modules/@remix-run/server-runtime/dist/server.js:94:18)
    at requestHandler (/Users/[...]/remix/node_modules/@remix-run/server-runtime/dist/server.js:34:18)
    at /Users/[...]/remix/node_modules/@sentry/remix/cjs/utils/instrumentServer.js:345:18
    at /Users/[...]/remix/node_modules/@remix-run/express/dist/server.js:39:22
```

As you can see, the error comes from a dependency of Remix, `@web3-storage` but the repo seems quite dead, and [existing issues](https://github.com/web3-storage/multipart-parser/issues/2) are not being addressed.

**Comment by dmarkow** [comment]
Ran into the same issue (I actually created that issue over there). @web3-storage's header handling is pretty basic. I haven't had time to open a proper PR on this repo to use a different lib, but for now this diff with `patch-package` is working around it.

`patches/@web3-storage+multipart-parser+1.0.0.patch`:

```diff
diff --git a/node_modules/@web3-storage/multipart-parser/cjs/src/index.js b/node_modules/@web3-storage/multipart-parser/cjs/src/index.js
index 8be5ee9..311b48a 100644
--- a/node_modules/@web3-storage/multipart-parser/cjs/src/index.js
+++ b/node_modules/@web3-storage/multipart-parser/cjs/src/index.js
@@ -9,17 +9,24 @@ const mergeArrays2 = Function.prototype.apply.bind(utils.mergeArrays, undefined)
 const dash = utils.stringToArray('--');
 const CRLF = utils.stringToArray('\r\n');
 function parseContentDisposition(header) {
-  const parts = header.split(';').map(part => part.trim());
+  const parts = header.split(/;(?=(?:[^"]*"[^"]*")*[^"]*$)/).map(part => part.trim());
   if (parts.shift() !== 'form-data') {
     throw new Error('malformed content-disposition header: missing "form-data" in `' + JSON.stringify(parts) + '`');
   }
   const out = {};
   for (const part of parts) {
-    const kv = part.split('=', 2);
-    if (kv.length !== 2) {
-      throw new Error('malformed content-disposition header: key-value pair not found - ' + part + ' in `' + header + '`');
+    const equals = part.indexOf('=');
+    if (equals < 0) {
+      throw new Error('malformed key-value string: missing value in `' + part + '`');
     }
-    const [name, value] = kv;
+
+    const name = part.slice(0, equals);
+    const value = part.slice(equals + 1);
+    //const kv = part.split('=', 2);
+    //if (kv.length !== 2) {
+      // throw new Error('malformed content-disposition header: key-value pair not found - ' + part + ' in `' + header + '`');
+    // }
+    // const [name, value] = kv;
     if (value[0] === '"' && value[value.length - 1] === '"') {
       out[name] = value.slice(1, -1).replace(/\\"/g, '"');
     } else if (value[0] !== '"' && value[value.length - 1] !== '"') {
```

**Comment by kof** [comment]
We caught the same error https://github.com/webstudio-is/webstudio-designer/pull/483

**Comment by brophdawg11** [comment]
Going to mark this as `external` for now during this v2 bug sweep - but I agree it looks like that package may be abandoned so we may need to fork or inline that code prior to stabilizing `unstable_parseMultipartFormData`

**Comment by apaofficial** [comment]
This issue is still present in version 2.2

**Comment by zmillman** [comment]
Just ran into this on `remix-run@2.9.1` with `@web3-storage@1.0.0`

**Comment by kiliman** [comment]
You may want to switch to a new package that @mjackson has created: `@mjackson/form-data-parser`.

Here's a post+video from @jacobparis showing how to migrate from `unstable_parseMultipartFormData`

https://www.epicweb.dev/tips/replace-remix-s-unstable_parsemultipartformdata-with-mjackson-form-data-parser

**Comment by brookslybrand** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2.  If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.

We plan to continue to address 2 types of issues in Remix v2:

* Bugs that pose security concerns
* Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new minimal reproduction against v7.

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
