### ISSUE TITLE
`eslint-plugin-import` should be a peer dependency of `@remix-run/eslint-config`

### ISSUE THREAD

**Issue by lensbart** [remix-run/remix#4448]
### What version of Remix are you using?

0.0.0-experimental-aed5bfbf7

### Steps to Reproduce

Configure ESLint with `@remix-run/eslint-config` and any of the following
* ESLint configs:
  * `eslint-config-airbnb`
  * `eslint-config-airbnb-typescript`
  * `plugin:import/recommended` (via `eslint-plugin-import`)
* plugins:
  * `eslint-plugin-import`

### Expected Behavior

ESLint integration in VSCode doesn’t crash

### Actual Behavior

ESLint crashes with error (depending on which config/plugin clashes first):

```
Uncaught exception received.
Error: Plugin "import" was conflicted between ".eslintrc.js#overrides[11] » @remix-run/eslint-config" and ".eslintrc.js#overrides[5] » plugin:import/recommended".
    at mergePlugins (/something/.yarn/cache/@eslint-eslintrc-npm-1.3.3-9e3a462140-f03e9d6727.zip/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:598:19)
    at createConfig (/something/.yarn/cache/@eslint-eslintrc-npm-1.3.3-9e3a462140-f03e9d6727.zip/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:701:9)
    at ConfigArray.extractConfig (/something/.yarn/cache/@eslint-eslintrc-npm-1.3.3-9e3a462140-f03e9d6727.zip/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:877:33)
    at CLIEngine.isPathIgnored (/something/.yarn/cache/eslint-npm-8.26.0-c277e15ec0-a2aced939e.zip/node_modules/eslint/lib/cli-engine/cli-engine.js:990:18)
    at ESLint.isPathIgnored (/something/.yarn/cache/eslint-npm-8.26.0-c277e15ec0-a2aced939e.zip/node_modules/eslint/lib/eslint/eslint.js:681:26)
    at /something-else/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:22172
    at Object.E [as withClass] (/something-else/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:18310)
    at D.then.g.validate (/something-else/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:22143)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /something-else/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:210071
[Info  - 4:07:14 PM] ESLint server stopped.
```

I **think** this can be fixed by setting the import plugin as a peer dependency. That’s how it’s done by other configs:
* https://github.com/airbnb/javascript/blob/c6b1a43c489d2c242f9c6c6d12966c95d27d9dfa/packages/eslint-config-airbnb/package.json#L91
* https://github.com/iamturns/eslint-config-airbnb-typescript/blob/91fd090f6fdd8d598a6ac6e9bb2c2ba33014e425/package.json#L32

**Comment by brophdawg11** [comment]
Obsoleted by https://github.com/remix-run/remix/issues/7056 as we are going to simplify the eslint setups in v2
