### ISSUE TITLE
`npx @remix-run/dev migrate` Fails with an error

### ISSUE THREAD

**Issue by alexblack** [remix-run/remix#4525]
### What version of Remix are you using?

1.7.5

### Steps to Reproduce

On our project, I attempted to run `npx @remix-run/dev migrate` to migrate from imports using "remix" to "@remix-run/*"

### Expected Behavior

I hoped it would work and I'd have all our imports updated

### Actual Behavior

It generated a lot of logs and appears to have failed somehow.

https://gist.github.com/alexblack/ac355020ca13e01adb6dda0660369e5f

I see errors like:

```
@remix-run/react: No matching version found for @remix-run/react@1.7.5.
npm WARN old lockfile     at module.exports (/Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:681:9)
npm WARN old lockfile  Could not fetch metadata for @remix-run/react@1.7.5 @remix-run/react: No matching version found for @remix-run/react@1.7.5.
npm WARN old lockfile     at module.exports (/Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:681:9) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '1.7.5',
```

```
pm WARN old lockfile TypeError: Cannot convert undefined or null to object
npm WARN old lockfile     at Function.keys (<anonymous>)
npm WARN old lockfile     at module.exports (/Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:213:22)
npm WARN old lockfile     at /Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:681:9)
npm WARN old lockfile  Could not fetch metadata for @remix-run/web-form-data@3.0.3 TypeError: Cannot convert undefined or null to object
npm WARN old lockfile     at Function.keys (<anonymous>)
npm WARN old lockfile     at module.exports (/Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:213:22)
npm WARN old lockfile     at /Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:681:9)
npm WARN old lockfile TypeError: Cannot convert undefined or null to object
npm WARN old lockfile     at Function.keys (<anonymous>)
npm WARN old lockfile     at module.exports (/Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:213:22)
npm WARN old lockfile     at /Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:681:9)
npm WARN old lockfile  Could not fetch metadata for @remix-run/web-fetch@4.3.1 TypeError: Cannot convert undefined or null to object
npm WARN old lockfile     at Function.keys (<anonymous>)
```

```
npm WARN old lockfile @remix-run/dev: No matching version found for @remix-run/dev@1.7.5.
npm WARN old lockfile     at module.exports (/Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:681:9)
npm WARN old lockfile  Could not fetch metadata for @remix-run/dev@1.7.5 @remix-run/dev: No matching version found for @remix-run/dev@1.7.5.
npm WARN old lockfile     at module.exports (/Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/Users/alex/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:681:9) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '1.7.5',
```

**Comment by MichaelDeBoey** [comment]
It seems like this is a problem with `npm` not finding v1.7.5.
Could you please try again & see if this is still failing?

**Comment by MichaelDeBoey** [comment]
It seems like this was a problem with `npm` not finding v1.7.5.

Closing this as I tried it locally & it worked like it should now

**Comment by alexblack** [comment]
Ok I'll try again thx

**Comment by alexblack** [comment]
Its still failing for me, but not the same error(s): https://gist.github.com/alexblack/b1f09359c0c44857e83f5debfb409ced

Am I permitted to re-open? doesn't look like it
