### ISSUE TITLE
Error in AWS/Architect deploy: TypeError: Cannot read property 'v2_meta' of undefined

### ISSUE THREAD

**Issue by KerryRitter** [remix-run/remix#4812]
### What version of Remix are you using?

^1.6.7, resolving to 1.8.2

### Steps to Reproduce

Deploy to AWS using Remix and Architect version 1.8.2.

### Expected Behavior

The web app should function as expected. 

### Actual Behavior

I have had a working deployment using Architect for a few months. Today I deployed new changes, and I get the following exception:

```
Application Error
TypeError: Cannot read property 'v2_meta' of undefined
    at Meta (/var/task/node_modules/@remix-run/react/dist/components.js:685:17)
    at renderWithHooks (/var/task/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5662:16)
    at renderIndeterminateComponent (/var/task/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5735:15)
    at renderElement (/var/task/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5950:7)
    at renderNodeDestructiveImpl (/var/task/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/var/task/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderNode (/var/task/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6263:12)
    at renderChildrenArray (/var/task/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6215:7)
    at renderNodeDestructiveImpl (/var/task/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6145:7)
    at renderNodeDestructive (/var/task/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
```

Please note that forcing the package resolution to 1.6.7 instead of ^1.6.7 corrects this behavior.

**Comment by machour** [comment]
Did you bump all your remix dependencies to 1.8.2 ?

**Comment by r007** [comment]
I'm having the same issue. But I'm using AWS CDK instead of ARC + Edge Lambda + Cloudfront. Tried everything from https://github.com/remix-run/remix/issues/4759 nothing helps.
- Tried upgrading Remix to 1.9.0 - didn't help.
- Tried to use V2_MetaFunction instead of MetaFunction - didn't help.
- Tried to remove favicon meta - didn't help.
- Tried to remove all metas - didn't help.

![FireShot Capture 152 - Application Error! - d13vtf5roml6b9 cloudfront net](https://user-images.githubusercontent.com/78280/208317450-b5b1396d-192b-410c-a847-f86694ea932d.png)

The problem started to occur after dependencies upgrade I think. Before that it worked. Also, on the localhost, everything works as usual, after ```npm run build; npm run start```. I'm trying to roll back all the commits to figure out the root reason. 

```
"@remix-run/node": "^1.9.0",
"@remix-run/react": "^1.9.0",
"@remix-run/serve": "^1.9.0",
```
```
AWS Lambda NodeJS Version: v18.
Localhost NodeJS Version: v18.8.0
```

**Comment by KerryRitter** [comment]
I forced 1.6.2 and everything worked as expected.

**Comment by r007** [comment]
>I forced 1.6.2 and everything worked as expected.

No this didn't help at all.

I tracked the exact error down to this. The problem is inside the `@remix-run/react` package. This file: [remix-react/components.tsx](https://github.com/remix-run/remix/blob/main/packages/remix-react/components.tsx), when you destructure `useRemixEntryContext()` the `future` can be undefined. So `future.v2_meta` throws an error. Need to add an additional check to prevent it from happening. Something like

```ts
return future && future.v2_meta ? <V2Meta> : <V1Meta>;
```

You get the idea.

![v2_meta](https://user-images.githubusercontent.com/78280/208469832-6b880dfc-30bd-4655-b482-a3a5d10daa35.png)

**Comment by r007** [comment]
Finally, found the root of the problem. It was inside the [remix-aws-edge](https://github.com/ctrlplusb/remix-aws-edge), dist file embedded an outdated `ServerBuild()`  function from remix version 1.5.x. Because of that, an incomplete context is passed to the frontend (without `future` variable). That's why `@remix-run/react` throws an error.

Please avoid using **remix-aws-edge**, because it's incompatible with newest versions. It's better to copy the main typescript file only.

**Comment by machour** [comment]
Turns out in both case, problem was unaligned remix versions
