### ISSUE TITLE
process is not defined when using a package that depends on it (in client)

### ISSUE THREAD

**Issue by chang-ryan** [remix-run/remix#4834]
### What version of Remix are you using?

1.8.2

### Steps to Reproduce

1. install remix indie stack
2. install `@paperxyz/react-client-sdk`
3. use package `import { PaperSDKProvider, LoginWithPaper } from "@paperxyz/react-client-sdk";`
4. `npm run dev`
5. bug occurs

### Expected Behavior

I expect us to be able to pull in this package `@paperxyz/react-client-sdk`

### Actual Behavior

```
Uncaught ReferenceError: process is not defined
    at node_modules/@paperxyz/js-client-sdk/dist/index.js (index.js:5:1534)
```

This is because the client dependency `@paperxyz/react-client-sdk` has references to `process.env` in its source code. I can monkey patch this by directly going into the outputted `index.js` file from `@paperxyz` and setting the following

```
// inside `node_modules/@paperxyz/js-client-sdk/dist/index.js`

var process = {
  env: {}
};
```

Is there any way I can globally inject this fake variable into remix's client environment? I anticipate that other packages that utilize a reference to `process.env` in its source code will break with remix.

**Comment by convcha** [comment]
`"@playwright/test": "1.29.0"` (devDependencies) also cause the same error.
Remix packages version is 1.9.0.

```
index.js:17 Uncaught ReferenceError: process is not defined
    at ../../node_modules/.pnpm/playwright-core@1.29.0/node_modules/playwright-core/index.js (index.js:17:28)
    at __require2 (chunk-CUPSZOF3.js:18:50)
    at ../../node_modules/.pnpm/@playwright+test@1.29.0/node_modules/@playwright/test/lib/index.js (index.js:26:49)
    at __require2 (chunk-CUPSZOF3.js:18:50)
    at ../../node_modules/.pnpm/@playwright+test@1.29.0/node_modules/@playwright/test/index.js (index.js:17:13)
    at __require2 (chunk-CUPSZOF3.js:18:50)
    at index.mjs:16:24
```

<img width="792" alt="image" src="https://user-images.githubusercontent.com/3993599/208284519-8c1f6fa3-67c3-4109-995d-60e8d14002ff.png">
