### ISSUE TITLE
Many "queryRoute() call aborted" error messages in logs

### ISSUE THREAD

**Issue by maximilize** [remix-run/remix#5280]
### What version of Remix are you using?

v1.11.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Deploy your app on a server
2. Let users use it
3. This error messages seem to randomly appear

### Expected Behavior

No errors in the logs.

### Actual Behavior

The server logs get polluted with such messages.

**Comment by mkikets99** [comment]
Hey everyone.
I actually find one way to reproduce it.

**Steps of Code:**
Make a _[long polling](https://en.wikipedia.org/wiki/Push_technology#Long_polling)_ path...
Somathing like this will do:
```javascript
    let wait = (ms: number) =>
        new Promise((resolve) => setTimeout(resolve, ms));

    return new Promise((res, rej) => {
        wait(50 * 1000).then(() => res({ result: [] }));
    });
```

**Steps to reproduce:**
If you just make a request - everything looks fine: after 50 seconds you receiving a json result.
But if client interrups in a middle of process - `queryRoute() call aborted`

**Comment by kevin1193** [comment]
Is there any resolution for this issue?

**Comment by nabeelpkl** [comment]
getting same issue on remix server

`{
    "requestArgs": "{\n  \"context\": {},\n  \"params\": {\n    \"ticketId\": \"vxKELABCOEccO\"\n  },\n  \"request\": {\n    \"size\": 0,\n    \"follow\": 20,\n    \"compress\": true,\n    \"counter\": 0,\n    \"highWaterMark\": 16384,\n    \"insecureHTTPParser\": false\n  }\n}",
    "error": "{\n  \"stack\": \"Error: queryRoute() call aborted\\n    at loadRouteData (/home/node/app/node_modules/@remix-run/router/router.ts:3010:13)\\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at queryImpl (/home/node/app/node_modules/@remix-run/router/router.ts:2774:20)\\n    at Object.queryRoute (/home/node/app/node_modules/@remix-run/router/router.ts:2714:18)\\n    at handleDataRequestRR (/home/node/app/node_modules/@remix-run/server-runtime/dist/server.js:75:20)\\n    at requestHandler (/home/node/app/node_modules/@remix-run/server-runtime/dist/server.js:49:18)\\n    at /home/node/app/node_modules/@sentry/src/utils/instrumentServer.ts:363:1\\n    at /home/node/app/node_modules/@remix-run/express/dist/server.js:39:22\",\n  \"message\": \"queryRoute() call aborted\"\n}"
}`

any solution or work around for this?

Sometimes see `Failed to fetch` error message if the tab is kept idle for sometime. are these issues related ?

**Comment by zolzaya** [comment]
any updates?

**Comment by ZipBrandon** [comment]
My Sentry is full of these. Is it best practice to just ignore or silence these?

![image](https://github.com/remix-run/remix/assets/68867795/d3926b4a-fd00-4b40-8815-d39e0fd5acdd)

**Comment by lildesert** [comment]
You can skip sending aborted request to Sentry with `handleError`, see https://remix.run/docs/en/main/file-conventions/entry.server#handleerror

**Comment by sergiodxa** [comment]
This is what I do on my `handleError` function.
```ts
export function handleError(error: unknown, { request }: LoaderArgs): void {
  // ignore aborted requests
  if (request.signal.aborted) return;

  // ignore throw responses, or report `error.error`
  if (isRouteErrorResponse(error)) return;

  // report to Sentry (or another service or just log them) any other value
  reportToSentry(error);
}
```
