### ISSUE TITLE
codemod is not working when version is `latest` in package.json

### ISSUE THREAD

**Issue by phoenixcoded20** [remix-run/remix#5321]
### What version of Remix are you using?

latest

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Cloned the project from MUI: https://github.com/mui/material-ui/tree/master/examples/remix-with-typescript
2. Run command: **npx @remix-run/dev@latest codemod replace-remix-magic-imports**

P.S. Since it's using codemod from the remix, it seems the issue is not with MUI but with remix.

### Expected Behavior

It should run and update the code and packages

### Actual Behavior

It gives the error as follows:

```
✔ Found codemod: replace-remix-magic-imports
✔ No Remix server adapter detected
✔ Detected Remix server runtime: node
⠋ Removing magic `remix` package from dependenciesTypeError: Invalid comparator: latest
    at Comparator.parse (D:\Development\Phoenix\git-others\material-ui\examples\remix-with-typescript\node_modules\@remix-run\dev\node_modules\semver\classes\comparator.js:38:13)
    at new Comparator (D:\Development\Phoenix\git-others\material-ui\examples\remix-with-typescript\node_modules\@remix-run\dev\node_modules\semver\classes\comparator.js:22:10)
    at D:\Development\Phoenix\git-others\material-ui\examples\remix-with-typescript\node_modules\@remix-run\dev\node_modules\semver\classes\range.js:133:47
    at Array.map (<anonymous>)
    at Range.parseRange (D:\Development\Phoenix\git-others\material-ui\examples\remix-with-typescript\node_modules\@remix-run\dev\node_modules\semver\classes\range.js:133:35)
    at D:\Development\Phoenix\git-others\material-ui\examples\remix-with-typescript\node_modules\@remix-run\dev\node_modules\semver\classes\range.js:34:22
    at Array.map (<anonymous>)
    at new Range (D:\Development\Phoenix\git-others\material-ui\examples\remix-with-typescript\node_modules\@remix-run\dev\node_modules\semver\classes\range.js:34:8)
    at Object.minVersion (D:\Development\Phoenix\git-others\material-ui\examples\remix-with-typescript\node_modules\@remix-run\dev\node_modules\semver\ranges\min-version.js:6:11)
    at D:\Development\Phoenix\git-others\material-ui\examples\remix-with-typescript\node_modules\@remix-run\dev\dist\codemod\replace-remix-magic-imports\index.js:41:72
```

**Comment by machour** [comment]
It seems that our codemod can't run if it can't detect the exact version running by reading the package.json file.
In the template you're using, it's specifying `latest`.

For now, you could simply change `latest` to `1.12.0` in the package.json file, update your deps, then run the codemod again.
