### ISSUE TITLE
Cloudflare & v2_routeConvention - [plugin browser-route-module] ENOENT: no such file or directory

### ISSUE THREAD

**Issue by uxbert-fe** [remix-run/remix#5323]
### What version of Remix are you using?

 "@remix-run/cloudflare": "^1.12.0",     "@remix-run/cloudflare-pages": "^1.12.0",   "@remix-run/react": "^1.12.0"

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- `npx create-remix@latest` (basic setup/cloudflare pages)
- Add `v2_routeConvention: true` in `remix.config.js` `future`
- `yarn dev` or `yarn build`

### Expected Behavior

Build/Run successfully.

### Actual Behavior

```js
Building Remix app in production mode...

✘ [ERROR] [plugin browser-route-module] ENOENT: no such file or directory, open '...../app/outes/_index.tsx'


Build failed with 1 error:
error: ENOENT: no such file or directory, open '..../app/outes/_index.tsx'
Error
    at Object.onCompileFailure (..../node_modules/@remix-run/dev/dist/cli/commands.js:180:13)
    at Object.compile (..../node_modules/@remix-run/dev/dist/compiler/remixCompiler.js:34:134)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.build (..../node_modules/@remix-run/dev/dist/compiler/build.js:33:3)
    at async Object.build (..../node_modules/@remix-run/dev/dist/cli/commands.js:175:3)
    at async Object.run (..../node_modules/@remix-run/dev/dist/cli/run.js:449:7)
```

Is there a missing `r` in the path `open '...../app/outes/_index.tsx'`

**Comment by sockthedev** [comment]
Duplicate of #5322

**Comment by uxbert-fe** [comment]
closed 👍
