### ISSUE TITLE
Remix 1.12.0 : Error: ENOTEMPTY: directory not empty, rmdir

### ISSUE THREAD

**Issue by raskyer** [remix-run/remix#5364]
### What version of Remix are you using?

1.12.0°

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- Launch dev server on windows (npm run dev)
- Edit multiples files
- Sometimes get this error : 
```
Error: ENOTEMPTY: directory not empty, rmdir '\\?\C:\{ pathname }\public\build\routes\{ route }'
    at Object.rmdirSync (node:fs:1226:10)
    at _rmdirSync (node:internal/fs/rimraf:260:21)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at Object.rmSync (node:fs:1275:10)
      throw err;
```

and

```
Error: EBUSY: resource busy or locked, unlink '\\?\C:\{ pathname }\public\build\routes\{ route }\index-3UB5F7DH.js'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at Object.rmSync (node:fs:1275:10)
    at Object.removeSync (C:\node_modules\fs-extra\lib\remove\index.js:15:28)
    at C:\dev\repos\raskyer\la-plateforme\web\node_modules\fs-extra\lib\empty\index.js:30:12
    at Array.forEach (<anonymous>)
    at Object.emptyDirSync (C:\node_modules\fs-extra\lib\empty\index.js:28:9) {
  errno: -4082,
  syscall: 'unlink',
  code: 'EBUSY',
  path: '\\\\?\\C:\\{ pathname }\\public\\build\\routes\\{ route }\\index-3UB5F7DH.js'
}
```
- It crash the server 

### Expected Behavior

No bug while developping

### Actual Behavior

It crash the server with the error mentioned earlier

**Comment by dmarkow** [comment]
Getting a similar issue on 1.12.0 running on macOS (error stack is a little different but I think that's due to Windows vs macOS).

For me, it seems to happen when a second rebuild gets triggered while the first one is still running. In the example below, I'm saving `thumbs.tsx` which triggers a rebuild. But I also have a sass/postcss/tailwind process running that updates the CSS file as well based on the new classes I added to the file. Sometimes it works (first rebuild in the example below) and sometimes it doesn't (second rebuild).

```
💿 File changed: app/routes/projects.$id.files/thumbs.tsx
💿 Rebuilding...
💿 File changed: app/styles/app.css.css
💿 Rebuilding...
💿 Rebuilt in 257ms
💿 Rebuilt in 263ms
GET /projects/00-035/files?mode=thumbs - - - - ms
GET /projects/00-035/files?mode=thumbs 200 - - 1568.608 ms
💿 File changed: app/routes/projects.$id.files/thumbs.tsx
💿 Rebuilding...
💿 File changed: app/styles/app.css.css
Error: ENOTEMPTY: directory not empty, rmdir '/Users/dylan/dev/access-remix/public/build/_shared'
    at Object.rmdirSync (node:fs:1226:10)
    at _rmdirSync (node:internal/fs/rimraf:260:21)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at Object.rmSync (node:fs:1275:10)
    at Object.removeSync (/Users/dylan/dev/access-remix/node_modules/fs-extra/lib/remove/index.js:15:28)
    at /Users/dylan/dev/access-remix/node_modules/fs-extra/lib/empty/index.js:30:12
    at Array.forEach (<anonymous>)
    at Object.emptyDirSync (/Users/dylan/dev/access-remix/node_modules/fs-extra/lib/empty/index.js:28:9)
    at clean (/Users/dylan/dev/access-remix/node_modules/@remix-run/dev/dist/devServer/liveReload.js:46:27)
    at onRebuildStart (/Users/dylan/dev/access-remix/node_modules/@remix-run/dev/dist/devServer/liveReload.js:74:7)
error Command failed with exit code 1.
```

**Comment by johanbaath** [comment]
Same issue, crashes the process. It happens after editing a few files, not sure why exactly. Downgraded to 1.11.0 in the meantime.
