### ISSUE TITLE
Support for `import.meta.url` in ESM

### ISSUE THREAD

**Issue by angelinekwan** [remix-run/remix#5588]
### What version of Remix are you using?

1.7.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

The fix for this Remix issue [Unable to import from libs using ESM](https://github.com/remix-run/remix/issues/109) by add the [ESM package ](https://remix.run/docs/en/v1/pages/gotchas#importing-esm-packages)to the `serverDependenciesToBundle` option in `remix.config.js` file didn't resolve the issue of `import.meta.url` return undefined, probably caused by an incorrect transpilation to CJS.

A use case with [remark-mermaidjs](https://github.com/remcohaszing/remark-mermaidjs/issues/20#issuecomment-1446262690) with the following setup will cause the app stop working.

**package.json**
```
"@remix-run/node": "1.7.0",
"@remix-run/react": "1.7.0",
"@remix-run/serve": "1.7.0",

"react-markdown": "^8.0.3",
"remark-mermaidjs": "^4.1.1",
```

**component.tsx**
```
import React from "react";
import ReactMarkdown from "react-markdown";
import remarkMermaid from "remark-mermaidjs";

interface Props {
	content: string;
}

export function MarkDown({ content }: Props) {
	return (
        <ReactMarkdown
            components={{
                p: ({ children }) => {
                    return (
                        <p>
                            {children}
                        </p>
                    );
                },
            }}
            children={content}
            remarkPlugins={[
                remarkMermaid,
            ]}
        />
	);
}
```

### Expected Behavior

No error on build time and the `remark-mermaidjs` package works as expected rendering [mermaid diagram in markdown](https://github.com/remcohaszing/remark-mermaidjs).

### Actual Behavior

`import remarkMermaid from "remark-mermaidjs"` cause the app stop working with the following error:

```
TypeError: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at createRequire (node:internal/modules/cjs/loader:1224:11)
    at Object.<anonymous> (/my-app/node_modules/remark-mermaidjs/index.js:8:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /my-app/node_modules/@remix-run/serve/dist/index.js:43:17
    at Layer.handle [as handle_request] (/my-app/node_modules/express/lib/router/layer.js:95:5)
    at next (/my-app/node_modules/express/lib/router/route.js:144:13)
    at next (/my-app/node_modules/express/lib/router/route.js:140:7)
    at next (/my-app/node_modules/express/lib/router/route.js:140:7)
    at next (/my-app/node_modules/express/lib/router/route.js:140:7)
    at next (/my-app/node_modules/express/lib/router/route.js:140:7)
```

**Comment by aerojeyenth** [comment]
I had a similar issue it could be due this issue https://github.com/remix-run/remix/issues/5644#issue-1608430048

As a quick fix you can downgrade your remix version 
to v1.13.0 

Please refer https://github.com/clerkinc/javascript/issues/952#issuecomment-1478051204

**Comment by convcha** [comment]
![CleanShot 2023-04-19 at 20 36 27@2x](https://user-images.githubusercontent.com/3993599/233062984-470459f1-5e65-491a-9c4d-7ede273e5e9f.png)
https://github.com/remix-run/remix/issues/5644#issuecomment-1493975962

This problem still seems to occur in Remix v1.15.0.

Repro steps:

```shell
$ git clone git@github.com:convcha/remix-issue-5644.git
$ cd remix-issue-5644
$ npm install
$ npm run dev
```

```
[mf:err] /private/tmp/remix-issue-5644/build/index.js:15734
  (import.meta.env && import.meta.env.MODE) !== "production" && (stateListeners = /* @__PURE__ */ new Set(), storeListeners = /* @__PURE__ */ new Set(), mountedAtoms = /* @__PURE__ */ new Set());
          ^^^^

SyntaxError: Cannot use 'import.meta' outside a module
    at new Script (node:vm:100:7)
    at VMScriptRunner.runAsScript (/private/tmp/remix-issue-5644/node_modules/@miniflare/runner-vm/src/index.ts:23:20)
    at VMScriptRunner.run (/private/tmp/remix-issue-5644/node_modules/@miniflare/runner-vm/src/index.ts:88:12)
    at Miniflare.#reload (/private/tmp/remix-issue-5644/node_modules/@miniflare/core/src/index.ts:790:42)
    at Miniflare.getPlugins (/private/tmp/remix-issue-5644/node_modules/@miniflare/core/src/index.ts:1033:5)
    at createServer (/private/tmp/remix-issue-5644/node_modules/@miniflare/http-server/src/index.ts:362:19)
    at startServer (/private/tmp/remix-issue-5644/node_modules/@miniflare/http-server/src/index.ts:469:18)
    at main (/private/tmp/remix-issue-5644/node_modules/miniflare/src/cli.ts:111:7)
[mf:err] Unhandled Promise Rejection: /private/tmp/remix-issue-5644/build/index.js:15734
  (import.meta.env && import.meta.env.MODE) !== "production" && (stateListeners = /* @__PURE__ */ new Set(), storeListeners = /* @__PURE__ */ new Set(), mountedAtoms = /* @__PURE__ */ new Set());
          ^^^^

SyntaxError: Cannot use 'import.meta' outside a module
    at new Script (node:vm:100:7)
    at VMScriptRunner.runAsScript (/private/tmp/remix-issue-5644/node_modules/@miniflare/runner-vm/src/index.ts:23:20)
    at VMScriptRunner.run (/private/tmp/remix-issue-5644/node_modules/@miniflare/runner-vm/src/index.ts:88:12)
    at Miniflare.#reload (/private/tmp/remix-issue-5644/node_modules/@miniflare/core/src/index.ts:790:42)
    at Miniflare.getPlugins (/private/tmp/remix-issue-5644/node_modules/@miniflare/core/src/index.ts:1033:5)
    at createServer (/private/tmp/remix-issue-5644/node_modules/@miniflare/http-server/src/index.ts:362:19)
    at startServer (/private/tmp/remix-issue-5644/node_modules/@miniflare/http-server/src/index.ts:469:18)
    at main (/private/tmp/remix-issue-5644/node_modules/miniflare/src/cli.ts:111:7)
```

The changes I made to the Cloudflare Workers template are as follows.  
https://github.com/convcha/remix-issue-5644/commit/a0a3ea454c1f14a0f0eb6b671bd2a4d018078084

**Comment by TomerAberbach** [comment]
Specifically for `rehype-mermaidjs`, I solved it for now by patching `isomorphic-mermaid` and adding it to `serverDependenciesToBundle`:
```patch
diff --git a/index.js b/index.js
index b5eb1205c318cdc6861a56329e31296b898dc952..bdc3ba579130450ceb64041170fc189c490c5be1 100644
--- a/index.js
+++ b/index.js
@@ -1,8 +1,10 @@
 import { createRequire } from 'node:module';
 import { pathToFileURL } from 'node:url';
+import { dirname, join } from 'node:path';
 import { chromium } from 'playwright-core';
-const require = createRequire(import.meta.url);
-const html = String(new URL('index.html', import.meta.url));
+
+const require = createRequire(String(pathToFileURL(__filename)));
+const html = String(pathToFileURL(join(dirname(require.resolve('mermaid-isomorphic')), 'index.html')));
 const mermaidScript = { path: require.resolve('mermaid/dist/mermaid.js') };
 const faStyle = {
     // We use url, not path. If we use path, the fonts can’t be resolved.
```

**Comment by pcattori** [comment]
`esbuild` transpiles `import.meta` to an empty object for CJS or [when target is below es2020](https://esbuild.github.io/content-types/#javascript).

Remix V2 is defaulting to ESM and es2022. You can try it now on `nightly`.
