### ISSUE TITLE
Uncaught Error: Dynamic require of "fs/promises" is not supported

### ISSUE THREAD

**Issue by thomasverleye** [remix-run/remix#5628]
### What version of Remix are you using?

1.14.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

When reusing routes in other routes this error is happening consistently.

I have a similar folder structure like this:
```
app
└── routes/
    ├── companies/
    │   └── $companyId/
    │       └── users.tsx
    └── users.tsx
```

The `/users` route exports a `loader` function which we import & export as well in the `/companies/<some-id>/users` like this:

```
import Users from 'app/routes/users';
import { loader } from 'app/routes/users';

export { loader };
export default Users;
```

### Expected Behavior

Not throw an error.

### Actual Behavior

The error output is:

```
Uncaught Error: Dynamic require of "fs/promises" is not supported
    at chunk-CUPSZOF3.js:12:9
    at node_modules/@remix-run/node/dist/upload/fileUploadHandler.js (fileUploadHandler.js:17:16)
    at __require2 (chunk-CUPSZOF3.js:18:50)
    at node_modules/@remix-run/node/dist/index.js (index.js:20:25)
    at __require2 (chunk-CUPSZOF3.js:18:50)
    at users.tsx:2:22
```

**Comment by thomasverleye** [comment]
[this](https://github.com/remix-run/remix/issues/4236#issuecomment-1264444539) seems to be fixing it

**Comment by jacargentina** [comment]
Reverting to 1.13 was the solution for me. Maybe there is something on 1.14

**Comment by thomasverleye** [comment]
@jacargentina
Yeah same for me. Ended up reverting as well.

Thanks! 🙏

**Comment by zifahm** [comment]
Facing the same issue, revented back to 1.13. This bug is interesting

**Comment by thomasverleye** [comment]
Very interesting find @rrgomide I'll try this out tomorrow. Thanks!

**Comment by jacargentina** [comment]
@rrgomide if that's the case, then it is a breaking change for 1.1.4 which requires to be noted on the release notes.

**Comment by suciptoid** [comment]
I don't see this issue anymore after upgrade to 1.14.1.

Note: previously facing same issue after upgrade 1.13 to 1.14.0, then temporary revert back to 1.13.

**Comment by jacargentina** [comment]
Updating to 1.14.1 solved this. Maybe it should be closed

**Comment by roj1512** [comment]
I’m on 1.15.0 and it’s there.
