### ISSUE TITLE
Importing assets that exist in public folder fails when using the css module

### ISSUE THREAD

**Issue by eunseo9808** [remix-run/remix#5739]
### What version of Remix are you using?

1.14.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Set 'unstable_cssModules: true' in remix.config.js
2. Create styles.module.css file
3. Add asset files in public folder
4. Importing an asset in styles.module.css

```javascript
// remix.config.js
module.exports = {
  ...
  future: {
    unstable_cssModules: true,
  },
  ...
}
```

```css
background-image: url("/images/carousel1.jpeg");
```

### Expected Behavior

The asset in public folder is loaded successfully.

### Actual Behavior

The following error is produced:
```
Error: Build failed with 1 error:
css-modules-plugin-ns:app/styles/styles.module.css?css-modules-plugin-compiled-css:81:24: ERROR: Could not resolve "/images/carousel1.jpeg"
    at failureErrorWithLog (/workspaces/node_modules/esbuild/lib/main.js:1591:15)
    at /workspaces/node_modules/esbuild/lib/main.js:1047:28
    at runOnEndCallbacks (/workspaces/node_modules/esbuild/lib/main.js:1463:61)
    at buildResponseToResult (/workspaces/node_modules/esbuild/lib/main.js:1045:7)
    at /workspaces/node_modules/esbuild/lib/main.js:1157:14
    at responseCallbacks.<computed> (/workspaces-frontend/node_modules/esbuild/lib/main.js:694:9)
    at handleIncomingPacket (/workspaces/node_modules/esbuild/lib/main.js:749:9)
    at Socket.readFromStdout (/workspaces/node_modules/esbuild/lib/main.js:670:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
error Command failed with exit code 1.
```

Failed to get an asset that is inside the public folder but If url is set as follows, it works normally
```css
background-image: url("../../public/images/carousel1.jpeg");
```

**Comment by markdalgleish** [comment]
Thanks for the bug report! I realised the same issue impacts other CSS bundling methods. I've opened a PR that addresses all of them: #5788 

By the way, why are you referencing images in the public directory rather than bundling them and fingerprinting with a hash in the file name like other assets?

**Comment by eunseo9808** [comment]
@markdalgleish 
Thank you for handling it!
It's a background image that doesn't change much, so I put it in the public folder so that each user's browser can cache it
