### ISSUE TITLE
Building fails in v1.15.0 with v2_routeConvention enabled (Cannot read properties of undefined (reading 'filter'))

### ISSUE THREAD

**Issue by ronnylt** [remix-run/remix#5996]
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

`npm run build`

### Expected Behavior

Build sucess.

### Actual Behavior

```
> build
> run-s build:*


> build:remix
> remix build

Building Remix app in production mode...
⚠️ REMIX FUTURE CHANGE: The behaviors of `CatchBoundary` and `ErrorBoundary` are changing in v2. You can prepare for this change at your convenience with the `v2_errorBoundary` future fflag. For instructions on making this change see https://remix.run/docs/en/v1.15.0/pages/v2#catchboundary-and-errorboundary
⚠️ REMIX FUTURE CHANGE: APIs that provide `formMethod` will be changing in v2. All values will be uppercase (GET, POST, etc.) instead of lowercase (get, post, etc.) You can prepare for  this change at your convenience with the `v2_normalizeFormMethod` future flag. For instructions on making this change see https://remix.run/docs/en/v1.15.0/pages/v2#formMethod
⚠️ REMIX FUTURE CHANGE: The route `meta` export signature is changing in v2You can prepare for this change at your convenience with the `v2_meta` future flag. For instructions on makingg this change see https://remix.run/docs/en/v1.15.0/pages/v2#meta

X [ERROR] [plugin browser-route-module] Cannot read properties of undefined (reading 'filter')

 X [ERROR] [plugin browser-route-module] Cannot read properties of undefined (reading 'filter')


Build failed with 2 errors:
error: Cannot read properties of undefined (reading 'filter')
error: Cannot read properties of undefined (reading 'filter')
Error
    at Object.onCompileFailure (C:\Users\replaced\node_modules\@remix-run\dev\dist\cli\commands.js:195:13)
    at Object.compile (C:\Users\replaced\node_modules\@remix-run\dev\dist\compiler\remixCompiler.js:45:134)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.build (C:\Users\replaced\node_modules\@remix-run\dev\dist\compiler\build.js:33:3)
    at async Object.build (C:\Users\replaced\node_modules\@remix-run\dev\dist\cli\commands.js:190:3)
    at async Object.run (C:\Users\replaced\node_modules\@remix-run\dev\dist\cli\run.js:456:7)
ERROR: "build:remix" exited with 1.
```

**Comment by hannesj** [comment]
I had a similar problem, which was caused by having css modules together with the routes. It was solving by modifying `ignoredRouteFiles` to contain also `*.css`
