### ISSUE TITLE
[Bug]: ant.design: Cannot read properties of undefined (reading 'csp')  when i build project

### ISSUE THREAD

**Issue by ginyatov** [remix-run/remix#632]
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [X] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [X] `@remix-run/react`
- [X] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

1 - install Ant.design `npm install antd`
2 - **root.tsx**:

 ```
  import antd from 'antd/dist/antd.css';
  
  export let links: LinksFunction = () => {
    return [
      { rel: "stylesheet", href: antd },
      { rel: "stylesheet", href: globalStylesUrl }
   ];
  };
```

3 - **routes/index.tsx**:
```
import { Button } from 'antd';


// https://remix.run/guides/routing#index-routes
export default function Index() {

  return (
    <div className="remix__page">
      <main>
        <Button type="primary">Primary Button</Button>
      </main>
    </div>
  );
}

```

4 - `npm run build && npm run start`
5 - see localhost:3000, you get error

### Expected Behavior

View ant.design component `Button` in index page

### Actual Behavior

Getting error when i visit localhost:3000:
```
There was an error
Cannot read properties of undefined (reading 'csp')

Hey, developer, you should replace this with what you want your users to see.
```

### console logging when i visit localhost:3000:
```
TypeError: Cannot read properties of undefined (reading 'csp')
    at Object.Wave._this.renderWave [as children] (./node_modules/antd/lib/_util/wave.js:177:22)
    at a.b.render (./node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:213)
    at a.b.read (./node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (./node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at `<RemixServer context={remixContext} url={request.url} />` (./app/entry.server.tsx:12:4)
    at handleDocumentRequest (./node_modules/@remix-run/server-runtime/server.js:385:47)
    at async ./node_modules/@remix-run/server-runtime/server.js:71:20
    at async ./node_modules/@remix-run/express/server.js:44:22
TypeError: Cannot read properties of undefined (reading 'csp')
    at Object.Wave._this.renderWave [as children] (./node_modules/antd/lib/_util/wave.js:177:22)
    at a.b.render (./node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:213)
    at a.b.read (./node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (./node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at `<RemixServer context={remixContext} url={request.url} />` (./app/entry.server.tsx:12:4)
    at handleDocumentRequest (./node_modules/@remix-run/server-runtime/server.js:385:47)
    at async ./node_modules/@remix-run/server-runtime/server.js:71:20
    at async ./node_modules/@remix-run/express/server.js:44:22
GET / 500 - - 26.646 ms

```

**Comment by yesmeck** [comment]
`NODE_ENV=production npm run start` would fix the error.
