### ISSUE TITLE
[Bug]: PrismaClient execution fails on @remix-run/cloudflare-workers

### ISSUE THREAD

**Issue by aiji42** [remix-run/remix#667]
### What version of Remix are you using?

1.0.4

### Steps to Reproduce

1. Use create-remix to create a project. Select Cloudflare Workers at that time.
2. Install and build prisma.
3. Write `new PrismaClient()` in the `loader` or in [app/utils/db.server.ts](https://remix.run/docs/en/v1/tutorials/jokes#connect-to-the-database).
4. Start up miniflare with `yarn start`.

### Expected Behavior

`new PrismaClient()` should run without problems.

### Actual Behavior

```
$ yarn start
yarn run v1.22.17
$ miniflare --build-command "npm run dev:worker" --watch

> dev:worker
> esbuild --define:process.env.NODE_ENV='"development"' --bundle --sourcemap --outdir=dist ./worker


  dist/worker.js      609.5kb
  dist/worker.js.map  903.5kb

[mf:inf] Build succeeded
true
[mf:err] /Users/myusername/git/remix-tutorial-cloudflare/dist/worker.js:13428
          throw new Error(`PrismaClient is unable to be run in the browser.
          ^

Error: PrismaClient is unable to be run in the browser.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/Users/myusername/git/remix-tutorial-cloudflare/node_modules/.prisma/client/index-browser.js:153:11)
    at build/index.js (/Users/myusername/git/remix-tutorial-cloudflare/build/index.js:76:21)
    at __require (/Users/myusername/git/remix-tutorial-cloudflare/dist/worker.js:13:46)
    at /Users/myusername/git/remix-tutorial-cloudflare/worker/index.js:3:24
    at /Users/myusername/git/remix-tutorial-cloudflare/dist/worker.js:14682:3
    at Script.runInContext (node:vm:139:12)
    at VMScriptRunner.runAsScript (file:///Users/myusername/git/remix-tutorial-cloudflare/node_modules/@miniflare/runner-vm/src/index.ts:21:12)
    at VMScriptRunner.run (file:///Users/myusername/git/remix-tutorial-cloudflare/node_modules/@miniflare/runner-vm/src/index.ts:71:12)
    at EventTarget.#reload (file:///Users/myusername/git/remix-tutorial-cloudflare/node_modules/@miniflare/core/src/index.ts:437:38)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

- I have confirmed that this problem does not occur in `remix-run/node`.
- I have read the official Prisma [documentation](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-cloudflare-workers). I tried to change the alias, but the build fails.

**Comment by aiji42** [comment]
I was able to avoid this problem by creating `worker.build.js` and changing the alias.  
(When I name the esbuild script file `build.js`, it fails to start up miniflare. The cause is not known.)

```js
// worker.build.js
const alias = require('esbuild-plugin-alias');

const isProd = process.env.NODE_ENV === 'production'

require('esbuild')
  .build({
    entryPoints: ['./worker'],
    bundle: true,
    sourcemap: true,
    minify: isProd,
    outdir: 'dist',
    define: {
      "process.env.NODE_ENV": `"${process.env.NODE_ENV ?? 'development'}"`,
    },
    plugins: [
      alias({
        '@prisma/client': require.resolve('@prisma/client'),
      }),
    ],
  })
  .catch(() => process.exit(1));
```

```
# package.json

  "scripts": {
    ...
    "build:worker": "NODE_ENV=production node worker.build.js",
    "dev:worker": "node worker.build.js",
    "start": "miniflare --build-command \"npm run dev:worker\" --watch",
    ...
  },
```

---

```
$ yarn start                                                                                                                                           
yarn run v1.22.17
$ miniflare --build-command "npm run dev:worker" --watch

> dev:worker
> node worker.build.js

[mf:inf] Build succeeded
[mf:inf] Worker reloaded! (0.93MiB)
[mf:inf] Listening on :8787
[mf:inf] - http://127.0.0.1:8787
[mf:inf] - http://172.20.249.97:8787

```

**Comment by noga-aviator** [comment]
would be good to be fixed soon

**Comment by kettui** [comment]
> (When I name the script file for esbuild build.js, it fails to build. The reason is not known.)

this is due to the fact that remix compiles the server-side javascript under `<root>/build/` and worker.js then references said built files via `import * as build from "../build"`
-> the worker.js ends up importing your build.js file and will obviously not do what's intended

**Comment by bduff9** [comment]
Using the fix [here](https://github.com/remix-run/remix/issues/667#issuecomment-979773342) and adding the worker.build.js and updating the scripts doesn't resolve this for me.  I still get other errors when trying to start the project:

```bash
❯ npmst

> start
> miniflare --build-command "npm run dev:worker" --watch


> dev:worker
> node worker.build.js

✘ [ERROR] Could not resolve "path"

    node_modules/.prisma/client/index.js:57:21:
      57 │ const path = require('path')
         ╵                      ~~~~~~

  The package "path" wasn't found on the file system but is
  built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "events"

    node_modules/@prisma/client/runtime/index.js:50:40:
      50 │ ...mport_events = __toModule2(require("events"));
         ╵                                       ~~~~~~~~

  The package "events" wasn't found on the file system but
  is built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "fs"

    node_modules/@prisma/client/runtime/index.js:51:36:
      51 │ var import_fs = __toModule2(require("fs"));
         ╵                                     ~~~~

  The package "fs" wasn't found on the file system but is
  built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "path"

    node_modules/@prisma/client/runtime/index.js:52:39:
      52 │ var import_path2 = __toModule2(require("path"));
         ╵                                        ~~~~~~

  The package "path" wasn't found on the file system but is
  built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "crypto"

    node_modules/@prisma/client/runtime/index.js:54:40:
      54 │ ...mport_crypto = __toModule2(require("crypto"));
         ╵                                       ~~~~~~~~

  The package "crypto" wasn't found on the file system but
  is built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "child_process"

    node_modules/@prisma/client/runtime/index.js:55:47:
      55 │ ...ocess = __toModule2(require("child_process"));
         ╵                                ~~~~~~~~~~~~~~~

  The package "child_process" wasn't found on the file
  system but is built into node. Are you trying to bundle
  for node? You can use "platform: 'node'" to do that, which
  will remove this error.

✘ [ERROR] Could not resolve "net"

    node_modules/@prisma/client/runtime/index.js:58:37:
      58 │ var import_net = __toModule2(require("net"));
         ╵                                      ~~~~~

  The package "net" wasn't found on the file system but is
  built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "url"

    node_modules/@prisma/client/runtime/index.js:60:37:
      60 │ var import_url = __toModule2(require("url"));
         ╵                                      ~~~~~

  The package "url" wasn't found on the file system but is
  built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "util"

    node_modules/@prisma/client/runtime/index.js:61:38:
      61 │ var import_util = __toModule2(require("util"));
         ╵                                       ~~~~~~

  The package "util" wasn't found on the file system but is
  built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "stream"

    node_modules/@prisma/client/runtime/index.js:62:40:
      62 │ ...mport_stream = __toModule2(require("stream"));
         ╵                                       ~~~~~~~~

  The package "stream" wasn't found on the file system but
  is built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "async_hooks"

    node_modules/@prisma/client/runtime/index.js:67:45:
      67 │ ...c_hooks = __toModule2(require("async_hooks"));
         ╵                                  ~~~~~~~~~~~~~

  The package "async_hooks" wasn't found on the file system
  but is built into node. Are you trying to bundle for node?
  You can use "platform: 'node'" to do that, which will
  remove this error.

✘ [ERROR] Could not resolve "os"

    node_modules/@prisma/client/runtime/index.js:1733:22:
      1733 │     var os2 = require("os");
           ╵                       ~~~~

  The package "os" wasn't found on the file system but is
  built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "tty"

    node_modules/@prisma/client/runtime/index.js:1734:22:
      1734 │     var tty = require("tty");
           ╵                       ~~~~~

  The package "tty" wasn't found on the file system but is
  built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "assert"

    node_modules/@prisma/client/runtime/index.js:6400:27:
      6400 │       var assert = require("assert");
           ╵                            ~~~~~~~~

  The package "assert" wasn't found on the file system but
  is built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "buffer"

    node_modules/@prisma/client/runtime/index.js:6667:51:
      6667 │ ...ants: BufferConstants } = require("buffer");
           ╵                                      ~~~~~~~~

  The package "buffer" wasn't found on the file system but
  is built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "http"

    node_modules/@prisma/client/runtime/index.js:14867:41:
      14867 │ ...ar http = _interopDefault(require("http"));
            ╵                                      ~~~~~~

  The package "http" wasn't found on the file system but is
  built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "https"

    node_modules/@prisma/client/runtime/index.js:14870:43:
      14870 │ ...https2 = _interopDefault(require("https"));
            ╵                                     ~~~~~~~

  The package "https" wasn't found on the file system but is
  built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "zlib"

    node_modules/@prisma/client/runtime/index.js:14871:41:
      14871 │ ...ar zlib = _interopDefault(require("zlib"));
            ╵                                      ~~~~~~

  The package "zlib" wasn't found on the file system but is
  built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "tls"

    node_modules/@prisma/client/runtime/index.js:16816:43:
      16816 │ ...r tls_1 = __importDefault2(require("tls"));
            ╵                                       ~~~~~

  The package "tls" wasn't found on the file system but is
  built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

✘ [ERROR] Could not resolve "constants"

    node_modules/@prisma/client/runtime/index.js:22922:30:
      22922 │       var constants = require("constants");
            ╵                               ~~~~~~~~~~~

  The package "constants" wasn't found on the file system
  but is built into node. Are you trying to bundle for node?
  You can use "platform: 'node'" to do that, which will
  remove this error.

✘ [ERROR] Could not resolve "_http_common"

    node_modules/@prisma/client/runtime/index.js:27212:25:
      27212 │     var common = require("_http_common");
            ╵                          ~~~~~~~~~~~~~~

  The package "_http_common" wasn't found on the file system
  but is built into node. Are you trying to bundle for node?
  You can use "platform: 'node'" to do that, which will
  remove this error.

✘ [ERROR] Could not resolve "console"

    node_modules/@prisma/client/runtime/index.js:29146:29:
      29146 │     var { assert } = require("console");
            ╵                              ~~~~~~~~~

  The package "console" wasn't found on the file system but
  is built into node. Are you trying to bundle for node? You
  can use "platform: 'node'" to do that, which will remove
  this error.

[mf:err] BuildError [1]: Build failed with exit code 1
    at ChildProcess.<anonymous> (/Users/bduffey2/projects/movies-remix/node_modules/@miniflare/core/src/plugins/build.ts:73:25)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

**Comment by aiji42** [comment]
@bduff9 Have you built the Prisma client with `dataProxy` set to `previewFeatures` in the Prisma schema?

[Deploying to Cloudflare Workers#5. Set up Prisma](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-cloudflare-workers#5-set-up-prisma)
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb", "dataProxy"]
}
```

Cloudflare Workers is not running in pure Node, but in a sandboxed environment on the V8 engine, so you cannot run code that depends on Node's native API.

If you build the Prisma client with `dataProxy` set in `previewFeatures`, the code of Prisma client will automatically be designed to run in a browser or V8 engine and should be able to run on Cloudflare Workers.
https://www.prisma.io/docs/concepts/components/prisma-data-platform

**Comment by bduff9** [comment]
@aiji42 I had not seen that link so thanks for sharing.  I will review it more closely but I did just try to add the dataProxy previewFeature and rebuilt it.  Alas, it gives me the same error as above.

**Comment by aiji42** [comment]
@bduff9 Did you run the build command for the Prisma client?

```
npm prisma generate
```

**Comment by bduff9** [comment]
@aiji42 Yep, sure did.

**Comment by willin** [comment]
how about cloudflare pages?

**Comment by Brookke** [comment]
Has anyone managed to resolve this for cloudflare pages?

**Comment by yelban** [comment]
`npm run dev` can be started normally using [remix-cf-buffer](https://github.com/aiji42/remix-cf-buffer) with Prisma Data Proxy, but there will be a warning message

![截圖 2022-04-14 下午12 10 39](https://user-images.githubusercontent.com/981381/163312749-f08d9dbd-d8fe-4fee-870e-c4ec65dc2b6f.png)

**Comment by aiji42** [comment]
https://github.com/aiji42/remix-esbuild-override/tree/main/examples/prisma-cloudflare

**Comment by yelban** [comment]
Thank you @aiji42 
I used this method on remix cloudflare-pages and unfortunately the run still has error messages

1. Add patches to the project directory
2. npm i patch-package
3. npm i remix-esbuild-override esbuild-plugin-alias @esbuild-plugins/node-globals-polyfill
4. npm i @prisma/client 
5. npm i -D prisma

update prisma/schema.prisma
`
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["dataProxy", "referentialIntegrity"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model posts {
  id       String @id @default(auto()) @map("_id") @db.ObjectId
  markdown String
  slug     String
  title    String
}
`

add `"postinstall": "patch-package && remix-esbuild-override"` to package.json




![截圖 2022-04-18 下午2 41 12](https://user-images.githubusercontent.com/981381/163767126-120e039c-3ba3-46c3-8155-f44d3f5ade3f.png)

**Comment by aiji42** [comment]
@yelban 
I have read the prisma implementation and these codes are bundled but never actually executed. So you can ignore these warnings.

https://github.com/prisma/prisma/blob/c1d4f6ea4a0499759dcc1e43cc6c846ccb8051a8/packages/engine-core/src/data-proxy/utils/request.ts#L83
https://github.com/prisma/prisma/blob/c1d4f6ea4a0499759dcc1e43cc6c846ccb8051a8/packages/engine-core/src/data-proxy/utils/request.ts#L28
https://github.com/prisma/prisma/blob/c1d4f6ea4a0499759dcc1e43cc6c846ccb8051a8/packages/engine-core/src/data-proxy/utils/getJSRuntimeName.ts#L6

If it still bothers you, a patch to the `nodeFetch` code would be good.

**Comment by yelban** [comment]
@aiji42 
This is great news, thank you for taking the time to confirm the code and have a great day!

**Comment by millsp** [comment]
Hey everyone. We have released some changes a few minutes ago in [prisma@3.15.0](https://github.com/prisma/prisma/releases). tl;dr;
* Instead of `PRISMA_CLIENT_ENGINE_TYPE`, use `prisma generate --data-proxy` to enable the Data Proxy
* `import { PrismaClient } from '@prisma/client/edge'` for a Workers-compatible Prisma Client
* Please be aware that `.env` aren't bundled into the generated Prisma Client any longer ([see docs](https://www.prisma.io/docs/concepts/data-platform/data-proxy#edge-runtimes))
* You can also remove any package location aliasing in your build scripts
* Warnings around `eval` are now also fixed

Thanks everyone, and your feedback is welcome.

**Comment by raymclee** [comment]
> Hey everyone. We have released some changes a few minutes ago in [prisma@3.15.0](https://github.com/prisma/prisma/releases). tl;dr;
> 
> * Instead of `PRISMA_CLIENT_ENGINE_TYPE`, use `prisma generate --data-proxy` to enable the Data Proxy
> * `import { PrismaClient } from '@prisma/client/edge'` for a Workers-compatible Prisma Client
> * Please be aware that `.env` aren't bundled into the generated Prisma Client any longer ([see docs](https://www.prisma.io/docs/concepts/data-platform/data-proxy#edge-runtimes))
> * You can also remove any package location aliasing from your build scripts
> * Warnings around `eval` are now also fixed
> 
> Thanks everyone, and your feedback is welcome.

I got [pages:err] ReferenceError: process is not defined error with @prisma/client/edge with 3.15.0 and 3.15.1

**Comment by raymclee** [comment]
Ok i fixed the process is not defined error with the following code in remix.config.js

```js
const { withEsbuildOverride } = require("remix-esbuild-override");

withEsbuildOverride((option) => {
  option.define = {
    process: JSON.stringify({
      env: {
        DATABASE_URL:
          "prisma://your-data-proxy-url",
      },
    }),
  };

  return option;
});
```

**Comment by millsp** [comment]
Hey @raymclee, I think this is an issue since that seems to have happened at runtime.
