### ISSUE TITLE
`postcss-discard-duplicates` error when using NPM package that exports Vanilla Extract sprinkles

### ISSUE THREAD

**Issue by brandonpittman** [remix-run/remix#6687]
### What version of Remix are you using?

1.17.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Install a design system package that exports its own sprinkles
2. Start Remix app

### Expected Behavior

Should build without error and use imported sprinkles.

### Actual Behavior

This error occurs during `npm run dev`:

```
my-app/node_modules/postcss-discard-duplicates/src/index.js:72
    if (a.nodes.length !== b.nodes.length) {
                                   ^
TypeError: Cannot read properties of undefined (reading 'length')
    at equals (my-app/node_modules/postcss-discard-duplicates/src/index.js:72:36)
    at dedupeNode (my-app/node_modules/postcss-discard-duplicates/src/index.js:118:17)
    at dedupe (my-app/node_modules/postcss-discard-duplicates/src/index.js:148:7)
    at OnceExit (my-app/node_modules/postcss-discard-duplicates/src/index.js:161:7)
    at LazyResult.runAsync (my-app/node_modules/postcss/lib/lazy-result.js:433:21)
    at LazyResult.async (my-app/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (my-app/node_modules/postcss/lib/lazy-result.js:206:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

If I include the same code that the package exports, the build succeeds, the components use the imported styles from the package, but the CSS bundle contains two sets of sprinkles (with different random IDs).

**Comment by brandonpittman** [comment]
Seems like patching the postcss plugin like this:

`if (a.nodes?.length !== b.nodes?.length) {`

fixes this, but this feels really dirty.

**Comment by markdalgleish** [comment]
Just confirming, does everything work for you once you've applied your fix? If so, do you mind opening a PR upstream? https://github.com/cssnano/cssnano/issues/1510#issuecomment-1668067244

I'm closing this issue for now since it seems to be out of our control, but feel free to re-open if you're still experiencing issues.

>This is also kind of unexpected. Even if you pass an explicit postcss: false flag in remix.config.js, this plugin still seems to be running.

That's because we're using PostCSS internally to dedupe CSS generated by CSS Modules + `composes`. This step is run across the entire CSS bundle output and doesn't use the consumer's PostCSS config.
