### ISSUE TITLE
Remix is not compatible with updated fetch spec yet

### ISSUE THREAD

**Issue by MarkusWendorf** [remix-run/remix#6940]
### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Due to a recent change in the whatwg/fetch spec, the request constructor now requires the option `duplex` to be set when sending a body.

RequestInit: duplex option is required when sending a body
https://github.com/nodejs/node/issues/46221

Remix currently fails when using the Node.js provided fetch implementation (undici). Right now this only happens when you **do not** install the Web API polyfills via `installGlobals`.

Example (without `installGlobals`, fastify adapter):
https://github.com/MarkusWendorf/remix-request-duplex/blob/main/server.mjs

Steps:

1. `npm run dev`
2. Go to `/`
3. Type something in the input and **submit**
4. you'll see an error

### Expected Behavior

The form submission should work.

Remix should be compliant with the `fetch` spec. Right now nothing is really broken when using `installGlobals`, this is just a heads up.

### Actual Behavior

```
TypeError: RequestInit: duplex option is required when sending a body.
    at new Request (node:internal/deps/undici/undici:7323:19)
    at stripIndexParam (/remix-fastify/example/node_modules/@remix-run/server-runtime/dist/data.js:87:10)
    at Object.callRouteActionRR (/remix-fastify/example/node_modules/@remix-run/server-runtime/dist/data.js:36:29)
    at handler (/remix-fastify/example/node_modules/@remix-run/server-runtime/dist/routes.js:59:50)
    at runHandler (/remix-fastify/example/node_modules/@remix-run/router/router.ts:3620:7)
    at callLoaderOrAction (/remix-fastify/example/node_modules/@remix-run/router/router.ts:3671:22)
    at submit (/remix-fastify/example/node_modules/@remix-run/router/router.ts:2829:22)
    at queryImpl (/remix-fastify/example/node_modules/@remix-run/router/router.ts:2764:28)
    at Object.queryRoute (/remix-fastify/example/node_modules/@remix-run/router/router.ts:2714:24)
    at handleDataRequestRR (/remix-fastify/example/node_modules/@remix-run/server-runtime/dist/server.js:75:40)
```

**Comment by beerose** [comment]
Hey @jacob-ebey and @brophdawg11!

What are your thoughts on using [@whatwg-node/fetch](https://fetch.spec.whatwg.org/) in Remix? It's a **pony**fill for the fetch standard, so it could solve this issue and maybe others related to `fetch`.

Of course, if you guys are already working on a better solution, just ignore my comment.

**Comment by jacob-ebey** [comment]
@MarkusWendorf applying similar changes found in this PR to the fastly adapter should address your issue: https://github.com/remix-run/remix/pull/7234

**Comment by mcansh** [comment]
fastify* - got a prerelease of it up under the `pre` tag on npm
