### ISSUE TITLE
experimentalDecorators seems to have broken in v1.19.2, worked in v1.18.1

### ISSUE THREAD

**Issue by wollardj** [remix-run/remix#7066]
### What version of Remix are you using?

1.19.2

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. start a new project with `npx create-remix@latest` using the default options when prompted
2. set `compilerOptions.experimentalDecorators` to `true` in `tsconfig.json`
3. add the following code to `app/routes/_index.tsx`:
    ```tsx
    function exampleDecorator(_: Function) {
      console.log("Decorator called");
    }
    
    @exampleDecorator
    class Foo {
      sayHi() {
        console.log("Hello");
      }
    }
    
    export function loader() {
      const foo = new Foo();
      foo.sayHi();
      return null;
    }
    ```
4. run `npm run dev`

### Expected Behavior

This output is seen when using `v1.18.1`:

```
 💿  remix dev

 info  building...
 info  built (515ms)
Decorator called
Remix App Server started at http://localhost:3000 (http://192.168.86.24:3000)

Hello
GET / 200 - - 50.052 ms
```

### Actual Behavior

This output is seen when using `v1.19.2`
```

> dev
> remix dev


 💿  remix dev

 info  building...
✘ [ERROR] /Users/jwollard/Projects/reproductions/remix-with-decorators/app/routes/_index.tsx: Support for the experimental syntax 'decorators' isn't currently enabled (17:1):

  15 | }
  16 |
> 17 | @exampleDecorator
     | ^
  18 | class Foo {
  19 |   sayHi() {
  20 |     console.log("Hello");

Add @babel/plugin-proposal-decorators (https://github.com/babel/babel/tree/main/packages/babel-plugin-proposal-decorators) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-decorators (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-decorators) to the 'plugins' section to enable parsing. [plugin remix-hmr]

    browser-route-module:routes/_index.tsx?browser:1:30:
      1 │ export { default, meta } from "./routes/_index.tsx";
        ╵                               ~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onLoad" callback registered here:

    node_modules/@remix-run/dev/dist/compiler/js/plugins/hmr.js:149:12:
      149 │       build.onLoad({
          ╵             ~~~~~~

    at setup (/Users/jwollard/Projects/reproductions/remix-with-decorators/node_modules/@remix-run/dev/dist/compiler/js/plugins/hmr.js:149:13)
    at handlePlugins (/Users/jwollard/Projects/reproductions/remix-with-decorators/node_modules/esbuild/lib/main.js:1279:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by wollardj** [comment]
This seems like it might be related to https://github.com/remix-run/remix/issues/2208

**Comment by wollardj** [comment]
I didn't see this before, but it might be a dupe of https://github.com/remix-run/remix/issues/7011
