### ISSUE TITLE
v2 dev server `findPort` happens too early, can't run app on port 3001

### ISSUE THREAD

**Issue by rossipedia** [remix-run/remix#7143]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. `npx create-remix@latest`
2. select: "Just the basics", "express", "npm install"
3. cd into the project
4. run `PORT=3001 npm run dev`

### Expected Behavior

Application runs and is accessible at http://localhost:3001

### Actual Behavior

An error is reported:

```
$ PORT=3001 npm run dev

> dev
> remix dev --manual -c "node server.js"


 💿  remix dev

 info  building...
 info  built (195ms)
Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at Function.listen (~/src/remix/port-3001/node_modules/express/lib/application.js:635:24)
    at ~/src/remix/port-3001/server.js:50:5
```

---
Additional context in Discord thread here: https://discord.com/channels/770287896669978684/770287896669978687/1139666796392239205

**Comment by cliffordfajardo** [comment]
Yep also got this same error message today too
I was upgrading another team's remix app at work from version 1.8 to 1.9 and hit this error.
They were using port 3001 before I upgraded

**Comment by guilhermecomum** [comment]
Same here =\

**Comment by pcattori** [comment]
Currently, `remix dev` is structured to decide what port it'll use _before_ the app server is booted. That way it can send its origin (via `REMIX_DEV_ORIGIN` env var) to the app server when its spun up. To fix this, need to restructure how the port is communicated to the app server so that it can happen _after_ the app server is spun up.

**Comment by ahmedreza1** [comment]
is it something that is being worked on

**Comment by brophdawg11** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!  

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2.  If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.  

We plan to continue to address 2 types of issues in Remix v2:

* Bugs that pose security concerns
* Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so:

* If this is a bug, please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new [minimal reproduction](https://reactrouter.com/new) against v7
* If this is a feature request, please open a new [Proposal Discussion](https://github.com/remix-run/react-router/discussions/new?category=proposals) in React Router, and if it gets enough community support it can be considered for implementation

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
