### ISSUE TITLE
process is not defined after updating package from 1.17 to 1.19

### ISSUE THREAD

**Issue by pullmann4rent** [remix-run/remix#7201]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

€: if I remove LiveReload  component in root then it works but it should not be removed

I have installed my packages remix-run/node remix-run/react remix-run/express from 1.17 to 1.19.3 now I got this error:
```

ReferenceError: process is not defined
    at LiveReload2 (http://localhost:3002/build/_shared/chunk-DKDPPR2Q.js:5956:59)
    at renderWithHooks (http://localhost:3002/build/_shared/chunk-OKBCQ2CQ.js:12171:26)
    at mountIndeterminateComponent (http://localhost:3002/build/_shared/chunk-OKBCQ2CQ.js:14921:21)
    at beginWork (http://localhost:3002/build/_shared/chunk-OKBCQ2CQ.js:15902:22)
    at beginWork$1 (http://localhost:3002/build/_shared/chunk-OKBCQ2CQ.js:19749:22)
    at performUnitOfWork (http://localhost:3002/build/_shared/chunk-OKBCQ2CQ.js:19197:20)
    at workLoopSync (http://localhost:3002/build/_shared/chunk-OKBCQ2CQ.js:19133:13)
    at renderRootSync (http://localhost:3002/build/_shared/chunk-OKBCQ2CQ.js:19112:15)
    at recoverFromConcurrentError (http://localhost:3002/build/_shared/chunk-OKBCQ2CQ.js:18732:28)
    at performConcurrentWorkOnRoot (http://localhost:3002/build/_shared/chunk-OKBCQ2CQ.js:18680:30)
```

### Expected Behavior

if it was at version 1.17 all works fine

### Actual Behavior

package.json
```
{
  "private": true,
  "sideEffects": false,
  "scripts": {
    "build": "remix build",
    "dev": "npm-run-all build --parallel \"dev:*\"",
    "dev:node": "cross-env NODE_ENV=development nodemon --require dotenv/config ./server.js --watch ./server.js",
    "dev:remix": "remix watch",
    "start": "cross-env NODE_ENV=production node ./server.js",
    "typecheck": "tsc"
  },
  "dependencies": {
    "@clerk/remix": "^2.5.5",
    "@fullcalendar/core": "^6.1.8",
    "@fullcalendar/daygrid": "^6.1.8",
    "@fullcalendar/interaction": "^6.1.8",
    "@fullcalendar/moment": "^6.1.8",
    "@fullcalendar/react": "^6.1.8",
    "@fullcalendar/resource": "^6.1.8",
    "@fullcalendar/resource-timeline": "^6.1.8",
    "@fullcalendar/scrollgrid": "^6.1.8",
    "@fullcalendar/timegrid": "^6.1.8",
    "@react-pdf/renderer": "^3.1.9",
    "@react-spring/web": "^9.7.1",
    "@remix-run/css-bundle": "^1.16.0",
    "@remix-run/express": "^1.19.3",
    "@remix-run/node": "^1.19.3",
    "@remix-run/react": "^1.19.3",
    "@stripe/react-stripe-js": "^2.1.0",
    "@stripe/stripe-js": "^1.52.1",
    "@vercel/remix": "^1.19.2",
    "adm-zip": "^0.5.10",
    "cloudinary": "^1.35.0",
    "compression": "^1.7.4",
    "cross-env": "^7.0.3",
    "dayjs": "^1.11.7",
    "dragscroll": "^0.0.8",
    "express": "^4.18.2",
    "file-saver": "^2.0.5",
    "helmet": "^6.1.5",
    "inngest": "^2.5.1",
    "ioredis": "^5.3.2",
    "isbot": "^3.6.5",
    "jszip": "^3.10.1",
    "jwt-decode": "^3.1.2",
    "microinvoice": "^1.0.6",
    "moment": "^2.29.4",
    "morgan": "^1.10.0",
    "node-downloader-helper": "^2.1.6",
    "nodemailer": "^6.9.1",
    "paypal-rest-sdk": "^1.8.1",
    "pdf-creator-node": "^2.3.5",
    "pg": "^8.10.0",
    "puppeteer": "^19.7.5",
    "react": "^18.2.0",
    "react-confirm-alert": "^3.0.6",
    "react-dom": "^18.2.0",
    "react-icons": "^4.8.0",
    "react-indiana-drag-scroll": "^2.2.0",
    "react-loader-spinner": "^5.3.4",
    "react-select": "^5.7.0",
    "react-table": "^7.8.0",
    "redis": "^4.6.6",
    "remix-auth": "^3.4.0",
    "remix-auth-auth0": "^1.7.0",
    "remix-utils": "^6.1.0",
    "stripe": "^12.1.1",
    "style-it": "^2.1.4",
    "uuid": "^9.0.0",
    "yup": "^1.1.1"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.17.1",
    "@remix-run/eslint-config": "^1.14.2",
    "@types/adm-zip": "^0.5.0",
    "@types/file-saver": "^2.0.5",
    "@types/node": "^20.2.3",
    "@types/react": "^18.0.25",
    "@types/react-dom": "^18.0.8",
    "@types/uuid": "^9.0.1",
    "dotenv": "^16.0.3",
    "eslint": "^8.27.0",
    "nodemon": "^2.0.20",
    "npm-run-all": "^4.1.5",
    "typescript": "^4.8.4"
  },
  "engines": {
    "node": ">=14"
  }
}
```

**Comment by sampolahtinen** [comment]
@pullmann4rent did you resolve this? I am encountering the same when upgrading to Remix 2.0.1
