### ISSUE TITLE
Remix with Apollo Crashes with Cannot cancel a stream that already has a reader

### ISSUE THREAD

**Issue by justinhandley** [remix-run/remix#7266]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I am using remix with Apollo Client.  I have an issue that the dev server crashes on a regular basis, usually if I try to change routes too quickly (I'm assuming while a query is happening) but also now when I try to modify a query, for example by adding a search variable to the query that is dynamically controlled.  When I start to search, the dev server crashes with this error:

/Users/justinhandley/IdeaProjects/biztobiznow/node_modules/.pnpm/web-streams-polyfill@3.2.1/node_modules/web-streams-polyfill/src/lib/readable-stream.ts:149
      return promiseRejectedWith(new TypeError('Cannot cancel a stream that already has a reader'));
                                 ^
TypeError: Cannot cancel a stream that already has a reader
    at ReadableStream.cancel (/Users/justinhandley/IdeaProjects/biztobiznow/node_modules/.pnpm/web-streams-polyfill@3.2.1/node_modules/web-streams-polyfill/src/lib/readable-stream.ts:149:34)
    at abort (/Users/justinhandley/IdeaProjects/biztobiznow/node_modules/.pnpm/@remix-run+web-fetch@4.3.6/node_modules/@remix-run/web-fetch/src/fetch.js:75:18)
    at AbortSignal.abortAndFinalize (/Users/justinhandley/IdeaProjects/biztobiznow/node_modules/.pnpm/@remix-run+web-fetch@4.3.6/node_modules/@remix-run/web-fetch/src/fetch.js:91:4)
    at AbortSignal.dispatchEvent (/Users/justinhandley/IdeaProjects/biztobiznow/node_modules/.pnpm/event-target-shim@5.0.1/node_modules/event-target-shim/src/event-target.mjs:337:35)
    at abortSignal (/Users/justinhandley/IdeaProjects/biztobiznow/node_modules/.pnpm/abort-controller@3.0.0/node_modules/abort-controller/src/abort-signal.ts:68:12)
    at AbortController.abort (/Users/justinhandley/IdeaProjects/biztobiznow/node_modules/.pnpm/abort-controller@3.0.0/node_modules/abort-controller/src/abort-controller.ts:26:9)
    at ServerResponse.<anonymous> (/Users/justinhandley/IdeaProjects/biztobiznow/node_modules/.pnpm/@remix-run+express@1.19.3_express@4.18.2/node_modules/@remix-run/express/dist/server.js:68:36)
    at ServerResponse.emit (node:events:513:28)
    at emitCloseNT (node:_http_server:927:10)
    at Socket.onServerResponseClose (node:_http_server:274:5)
    at Socket.emit (node:events:525:35)
    at TCP.<anonymous> (node:net:313:12)
Warning: run-commands command "remix dev --port=4200" exited with non-zero status code

### Expected Behavior

I can change routes and modify queries and the dev server keeps running.

### Actual Behavior

Any time a query is loading and something changes, it crashes.

**Comment by jtparrett** [comment]
hey @justinhandley , just wondering if you ever found a solution for this?

**Comment by justinhandley** [comment]
Yes, although to be honest I can't remember exactly what it was.  This is my entry.client

`import { ApolloProvider } from '@apollo/client'
import { RemixBrowser } from '@remix-run/react'
import Cookie from 'js-cookie'
import { hydrateRoot } from 'react-dom/client'

function Client() {
  const apolloClient = createApolloClient(
    `${getApiUrl(window.location.host)}/graphql`,
    Cookie.get('__session') || '',
    false,
  )

  return (
    <ApolloProvider client={apolloClient.client}>
      <RemixBrowser />
    </ApolloProvider>
  )
}

hydrateRoot(document, <Client />)
`

and this is my entry.server

`import type { EntryContext } from '@remix-run/node'
import { RemixServer } from '@remix-run/react'
import { renderToString } from 'react-dom/server'
import { ApolloProvider } from '@apollo/client'
import { getDataFromTree } from '@apollo/client/react/ssr'
import { getStringCookie } from './utils'
import { createSitemapGenerator } from 'remix-sitemap'


const { isSitemapUrl, sitemap } = createSitemapGenerator({
  siteUrl: '',
  generateRobotsTxt: true,
  robotsTxtOptions: {
    policies: [
    
    ],
  },
})

export default async function handleRequest(
  request: Request,
  responseStatusCode: number,
  responseHeaders: Headers,
  remixContext: EntryContext,
) {
  if (isSitemapUrl(request)) return sitemap(request, remixContext)

  const environment = process.env.ENVIRONMENT || 'production'
  const cookie = getStringCookie(request.headers, '__session')
  const client = createApolloClient(`${getApiUrl(environment)}/graphql`, cookie)

  const App = (
    <ApolloProvider client={client.client}>
      <RemixServer context={remixContext} url={request.url} />
    </ApolloProvider>
  )

  return getDataFromTree(App).then(() => {
    const initialState = client.client.extract()

    const markup = renderToString(
      <ApolloContext.Provider value={initialState}>
        {App}
        <script
          dangerouslySetInnerHTML={{
            __html: `window.__INITIAL_STATE__=${JSON.stringify(initialState).replace(/</g, '\\u003c')};`,
          }}
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `window.process = ${JSON.stringify({
              env: { ENVIRONMENT: environment },
            })}`,
          }}
        />
      </ApolloContext.Provider>,
    )

    responseHeaders.set('Content-Type', 'text/html')
    if (environment === 'test') {
      responseHeaders.set('X-Robots-Tag', 'noindex')
    }


    return new Response('<!DOCTYPE html>' + markup, {
      status: responseStatusCode,
      headers: responseHeaders,
    })
  })
}
`

I think maybe this specific error is resolved with the dangerouslySetInnerHTMLs in the server code, but it's been a while since I've seen it and I don't remember exactly which changes fixed it.

**Comment by brophdawg11** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!  

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2.  If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.  

We plan to continue to address 2 types of issues in Remix v2:

* Bugs that pose security concerns
* Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so:

* If this is a bug, please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new [minimal reproduction](https://reactrouter.com/new) against v7
* If this is a feature request, please open a new [Proposal Discussion](https://github.com/remix-run/react-router/discussions/new?category=proposals) in React Router, and if it gets enough community support it can be considered for implementation

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
