### ISSUE TITLE
Node modules not imported in Vercel build after upgrading to v2

### ISSUE THREAD

**Issue by Klingefjord** [remix-run/remix#7350]
### What version of Remix are you using?

v2.0-pre

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Deploy Remix template on Vercel: https://github.com/vercel/vercel/tree/main/examples/remix
2. Upgrade to v2: `npx upgrade-remix pre` and remove the `vercel/remix` dependency.
3. Build now fails on Vercel, even though it works perfectly in a local env.

### Expected Behavior

Possible to migrate to Remix v2 on Vercel as per https://remix.run/docs/en/main/pages/v2

### Actual Behavior

Node modules are not imported:

```
✘ [ERROR] Could not resolve "node:crypto"
--
12:47:50.104 |  
12:47:50.104 | node_modules/@remix-run/node/dist/sessions/fileStorage.js:15:21:
12:47:50.104 | 15 │ var crypto = require('node:crypto');
12:47:50.104 | ╵                      ~~~~~~~~~~~~~
12:47:50.104 |  
12:47:50.105 | The package "node:crypto" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
12:47:50.105 |  
12:47:50.105 | ✘ [ERROR] Could not resolve "node:fs"
12:47:50.105 |  
12:47:50.105 | node_modules/@remix-run/node/dist/sessions/fileStorage.js:16:22:
12:47:50.105 | 16 │ var node_fs = require('node:fs');
12:47:50.105 | ╵                       ~~~~~~~~~
12:47:50.105 |  
12:47:50.105 | The package "node:fs" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
12:47:50.105 |  
12:47:50.105 | ✘ [ERROR] Could not resolve "node:path"
12:47:50.105 |  
12:47:50.105 | node_modules/@remix-run/node/dist/sessions/fileStorage.js:17:19:
12:47:50.105 | 17 │ var path = require('node:path');
12:47:50.106 | ╵                    ~~~~~~~~~~~
12:47:50.106 |  
12:47:50.106 | The package "node:path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
12:47:50.106 |  
12:47:50.106 | ✘ [ERROR] Could not resolve "node:stream"
12:47:50.106 |  
12:47:50.106 | node_modules/@remix-run/node/dist/stream.js:15:26:
12:47:50.106 | 15 │ var node_stream = require('node:stream');
12:47:50.106 | ╵                           ~~~~~~~~~~~~~
12:47:50.106 |  
12:47:50.106 | The package "node:stream" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
12:47:50.106 |  
12:47:50.106 | ✘ [ERROR] Could not resolve "node:crypto"
12:47:50.107 |  
12:47:50.107 | node_modules/@remix-run/node/dist/upload/fileUploadHandler.js:15:21:
12:47:50.107 | 15 │ var crypto = require('node:crypto');
12:47:50.107 | ╵                      ~~~~~~~~~~~~~
12:47:50.107 |  
12:47:50.107 | The package "node:crypto" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
12:47:50.107 |  
12:47:50.107 | ✘ [ERROR] Could not resolve "node:fs"
12:47:50.107 |  
12:47:50.107 | node_modules/@remix-run/node/dist/upload/fileUploadHandler.js:16:22:
12:47:50.107 | 16 │ var node_fs = require('node:fs');
12:47:50.107 | ╵                       ~~~~~~~~~
12:47:50.107 |  
12:47:50.107 | The package "node:fs" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
12:47:50.108 |  
12:47:50.108 | ✘ [ERROR] Could not resolve "node:fs/promises"
12:47:50.108 |  
12:47:50.108 | node_modules/@remix-run/node/dist/upload/fileUploadHandler.js:17:23:
12:47:50.108 | 17 │ var promises = require('node:fs/promises');
12:47:50.108 | ╵                        ~~~~~~~~~~~~~~~~~~
12:47:50.108 |  
12:47:50.108 | The package "node:fs/promises" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
12:47:50.108 |  
12:47:50.108 | ✘ [ERROR] Could not resolve "node:os"
12:47:50.108 |  
12:47:50.108 | node_modules/@remix-run/node/dist/upload/fileUploadHandler.js:18:22:
12:47:50.108 | 18 │ var node_os = require('node:os');
12:47:50.108 | ╵                       ~~~~~~~~~
12:47:50.108 |  
12:47:50.108 | The package "node:os" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
12:47:50.109 |  
12:47:50.109 | ✘ [ERROR] Could not resolve "node:path"
12:47:50.109 |  
12:47:50.109 | node_modules/@remix-run/node/dist/upload/fileUploadHandler.js:19:19:
12:47:50.109 | 19 │ var path = require('node:path');
12:47:50.109 | ╵                    ~~~~~~~~~~~
12:47:50.109 |  
12:47:50.109 | The package "node:path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
12:47:50.109 |  
12:47:50.109 | ✘ [ERROR] Could not resolve "node:stream"
12:47:50.109 |  
12:47:50.110 | node_modules/@remix-run/node/dist/upload/fileUploadHandler.js:20:26:
12:47:50.110 | 20 │ var node_stream = require('node:stream');
12:47:50.110 | ╵                           ~~~~~~~~~~~~~
12:47:50.110 |  
12:47:50.110 | The package "node:stream" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
12:47:50.110 |  
12:47:50.110 | ✘ [ERROR] Could not resolve "node:util"
12:47:50.110 |  
12:47:50.110 | node_modules/@remix-run/node/dist/upload/fileUploadHandler.js:21:24:
12:47:50.111 | 21 │ var node_util = require('node:util');
12:47:50.111 | ╵                         ~~~~~~~~~~~
12:47:50.111 |  
12:47:50.111 | The package "node:util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
12:47:50.111 |  
12:47:50.111 |  
12:47:50.111 | Build failed with 11 errors:
12:47:50.111 | node_modules/@remix-run/node/dist/sessions/fileStorage.js:15:21: ERROR: Could not resolve "node:crypto"
12:47:50.111 | node_modules/@remix-run/node/dist/sessions/fileStorage.js:16:22: ERROR: Could not resolve "node:fs"
12:47:50.112 | node_modules/@remix-run/node/dist/sessions/fileStorage.js:17:19: ERROR: Could not resolve "node:path"
12:47:50.112 | node_modules/@remix-run/node/dist/stream.js:15:26: ERROR: Could not resolve "node:stream"
12:47:50.112 | node_modules/@remix-run/node/dist/upload/fileUploadHandler.js:15:21: ERROR: Could not resolve "node:crypto"
12:47:50.112 | ...
12:47:50.113 | Error
12:47:50.113 | at Object.onCompileFailure (/vercel/path0/node_modules/@remix-run/dev/dist/cli/commands.js:195:13)
12:47:50.113 | at Object.compile (/vercel/path0/node_modules/@remix-run/dev/dist/compiler/remixCompiler.js:45:134)
12:47:50.113 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
12:47:50.113 | at async Object.build (/vercel/path0/node_modules/@remix-run/dev/dist/compiler/build.js:33:3)
12:47:50.113 | at async Object.build (/vercel/path0/node_modules/@remix-run/dev/dist/cli/commands.js:190:3)
12:47:50.114 | at async Object.run (/vercel/path0/node_modules/@remix-run/dev/dist/cli/run.js:456:7)
12:47:50.134 | error Command failed with exit code 1.
12:47:50.135 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
12:47:50.160 | Error: Command "yarn run build" exited with 1
```

**Comment by brophdawg11** [comment]
I'm not super familiar with Vercel's underlying architecture, but this seems like a server polyfill issue.  In Remix v2, nothing is polyfilled by default so you need to manually specify node polyfills if your app requires them: https://remix.run/docs/en/main/pages/v2#servernodebuiltinspolyfill.

Can you see if adding the proper polyfills resolves your issue?

**Comment by jxe** [comment]
We've tried with the following in remix.config. No luck.

```
  serverNodeBuiltinsPolyfill: {
    modules: {
      crypto: true,
      stream: true,
      fs: true,
      path: true,
      "fs/promises": true,
      os: true,
      util: true,
    }
  },
```

**Comment by pcattori** [comment]
Vercel maintains a fork of the Remix compiler that modifies the internals to work with per-route splitting of the server bundle. In essence, [their fork includes this PR](https://github.com/remix-run/remix/pull/7118). But that means that often times their fork lags behind Remix's compiler when a new version is just released or about to be released.

Not sure if this is related to that, but I could imagine a case where their fork doesn't yet support the polyfill options that our compiler supports. Or could be anything else in the v2 prerelease that isn't yet merged into their fork.

**Comment by TooTallNate** [comment]
We just shipped support for Remix v2 when deploying to Vercel. Can you all who were having issues here please try again and let us know if it's working for you now? Thanks!

**Comment by Gbuomprisco** [comment]
> We just shipped support for Remix v2 when deploying to Vercel. Can you all who were having issues here please try again and let us know if it's working for you now? Thanks!

Just tried and worked for me - thank you!
