### ISSUE TITLE
Architect adapter sends 500 response for missing action/loader instead of 400

### ISSUE THREAD

**Issue by shamsup** [remix-run/remix#7410]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Use the architect adapter (grunge stack or architect template) to initialize an app
2. create a resource route (uncertain if this happens for regular routes) that has only a loader or an action
3. send the opposite type of request to the route

### Expected Behavior

The response is a 400 status code like the express adapter (and probably others)

### Actual Behavior

```ts
// routes/action.ts
export const action = () => {
  return new Response(null, { status: 200 });
}
```
Go to `/action` in your browser, and get a 500 error (this is the response from API Gateway in production):
```json
{
  "statusCode": 500,
  "headers": {
    "content-type": "application/json; charset=utf-8",
    "x-remix-error": "yes"
  },
  "cookies": [],
  "body": "{\"message\":\"Unexpected Server Error\",\"stack\":\"Error: Unexpected Server Error\\n    at handleDataRequest (/node_modules/@remix-run/server-runtime/server.js:167:31)\\n    at requestHandler (/node_modules/@remix-run/server-runtime/server.js:45:20)\\n    at <anonymous> (/node_modules/@remix-run/architect/server.js:35:20)\"}"
}
```

**Comment by shamsup** [comment]
I have compared the source of the express adapter and architect adapter, but it appears they are both using the status code from `createRequestHandler` from `@remix-run/node` in the same way.

Here's my actual server entry, which has some minimal logging around the request and response which might affect it:
```ts
import { createRequestHandler } from '@remix-run/architect/dist/server';
import { installGlobals } from '@remix-run/node';
import type { APIGatewayProxyHandlerV2 } from 'aws-lambda';
import { createLogger, format, transports } from 'winston';

import { LOG_LEVEL } from './app/constants.server';
// @ts-ignore Build is probably not available yet
// eslint-disable-next-line import/no-unresolved
import * as build from './server';

installGlobals();

const logger = createLogger({
  level: LOG_LEVEL,
  format: format.combine(format.errors({ stack: true }), format.timestamp(), format.json()),
  transports: [new transports.Console()],
});

const remix = createRequestHandler({
  build,
  mode: process.env.NODE_ENV === 'production' ? 'production' : 'development',
  getLoadContext: (event) => {
    return {
      event,
    };
  },
});

const handler: APIGatewayProxyHandlerV2 = (event, context, callback) => {
  logger.debug('event', { event });
  logger.info(`start ${event.requestContext.http.method} ${event.rawPath}`);
  let remixResponse = remix(event, context, callback);
  if (remixResponse) {
    return remixResponse.then((response) => {
      logger.info('request end');
      if (typeof response !== 'string') {
        logger.info(
          `${response.statusCode} ${event.requestContext.http.method} ${event.rawPath}`
        );
        logger.debug('response', {
          response: {
            statusCode: response.statusCode,
            headers: response.headers,
            body: (response.body?.length || 0) > 1000 ? '[string > 1000]' : response.body,
          },
        });
      }
      return response;
    });
  }
};

// We need to use module.exports for tracing in production
module.exports = { handler };
```

**Comment by shamsup** [comment]
A fresh Architect template does correctly return a 400 in development and production, so it must be something in our own code that is doing this. I'd still appreciate it if anyone could spot the error in the above code.
