### ISSUE TITLE
Failed to create esm bundled application

### ISSUE THREAD

**Issue by KnisterPeter** [remix-run/remix#7467]
### What version of Remix are you using?

2.0.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- Create a new app with `pnpx create-remix@latest test`.
- In `remix.config.js` add `serverDependenciesToBundle: [/.*/]`
- Run `pnpm run dev`.

### Expected Behavior

The application should start.

### Actual Behavior

The application actually fails while trying to `require` 'http' from node.
It looks like the package `@remix-run/node` does not contain any valid esm export. I assume it does fallback to commonjs instead and from there it takes `@remix-run/web-fetch` in commonjs as well.

Not sure if this is the correct assumption.

```
markusw@xxx:/tmp/test (main)$ pnpm run dev

> test@ dev /tmp/test
> remix dev --manual


 💿  remix dev

 info  building...
 info  built (797ms)
Error: Dynamic require of "http" is not supported
    at file:///tmp/test/build/index.js?t=1695049617985.849:11:9
    at node_modules/.pnpm/@remix-run+web-fetch@4.4.0/node_modules/@remix-run/web-fetch/dist/lib.node.cjs (file:///tmp/test/build/index.js?t=1695049617985.849:4452:16)
    at file:///tmp/test/build/index.js?t=1695049617985.849:17:50
    at node_modules/.pnpm/@remix-run+node@2.0.0_typescript@5.2.2/node_modules/@remix-run/node/dist/globals.js (file:///tmp/test/build/index.js?t=1695049617985.849:5476:20)
    at file:///tmp/test/build/index.js?t=1695049617985.849:17:50
    at node_modules/.pnpm/@remix-run+node@2.0.0_typescript@5.2.2/node_modules/@remix-run/node/dist/index.js (file:///tmp/test/build/index.js?t=1695049617985.849:9751:20)
    at file:///tmp/test/build/index.js?t=1695049617985.849:17:50
    at file:///tmp/test/build/index.js?t=1695049617985.849:20675:27
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
^C ELIFECYCLE  Command failed.
```

**Comment by KnisterPeter** [comment]
If the assumption above is correct (ESM exports missing) I will try to create a PR which addresses the issue.
Other than that I have no clue why we see commonjs for this in the server bundle if the output is set (and defaults) to ESM.

**Comment by mao437303994** [comment]
The 'serverDependenciesToBundle' attribute should not match all.

**Comment by Mxs2019** [comment]
Was anyone able to figure this out? I'm facing the same issue.

**Comment by KnisterPeter** [comment]
Not yet

**Comment by brettdh** [comment]
Also ran into this on Remix 2.0.1 when building to deploy to AWS Lambda, using either @remix-run/architect or [remix-aws](https://github.com/wingleung/remix-aws). This error occurred when using remix-aws:

```
2023-10-23T13:31:32.103Z	undefined	ERROR	Uncaught Exception 	{
    "errorType":"Error",
    "errorMessage":"Dynamic require of \"path\" is not supported",
    "stack":[
        "Error: Dynamic require of \"path\" is not supported",
        "    at file:///var/task/ui/build/index.mjs:11:9",
        "    at node_modules/source-map-support/source-map-support.js (file:///var/task/ui/build/index.mjs:1082:76)",
        "    at file:///var/task/ui/build/index.mjs:17:50",
        "    at node_modules/remix-aws/node_modules/@remix-run/node/dist/index.js (file:///var/task/ui/build/index.mjs:9592:29)",
        "    at file:///var/task/ui/build/index.mjs:17:50",
        "    at file:///var/task/ui/build/index.mjs:31229:27",
        "    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)"
    ]
}
```

or this one when using @remix-run/architect:

```
2023-10-21T02:21:26.578Z	undefined	ERROR	Uncaught Exception 	{
    "errorType":"Error",
    "errorMessage":"Dynamic require of \"node:crypto\" is not supported",
    "stack":[
        "Error: Dynamic require of \"node:crypto\" is not supported",
        "    at file:///var/task/ui/build/index.mjs:11:9",
        "    at node_modules/@remix-run/architect/dist/sessions/arcTableSessionStorage.js (file:///var/task/ui/build/index.mjs:87308:19)",
        "    at file:///var/task/ui/build/index.mjs:17:50",
        "    at node_modules/@remix-run/architect/dist/index.js (file:///var/task/ui/build/index.mjs:87510:34)",
        "    at file:///var/task/ui/build/index.mjs:17:50",
        "    at file:///var/task/ui/build/index.mjs:107950:32",
        "    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)"
    ]
}
```

Workaround was to bundle the server module as CommonJS by removing `"type": "module"` from `package.json` and modifying `remix.config.js`:

```
module.exports = {
  ...
  serverBuildPath: "build/index.cjs",
  serverModuleFormat: "cjs",
}
```

which is not ideal, but works for us for now.

**Comment by brettdh** [comment]
...that is, I thought it worked for us, but instead it results in the issue described here: https://github.com/remix-run/remix/discussions/7761

**Comment by brettdh** [comment]
This PR repros the bug with a failing integration test: #7779 

What else needs to happen for a https://github.com/remix-run/remix/labels/bug%3Aunverified to become a https://github.com/remix-run/remix/labels/bug, and what can I do next to help the PR move along?

**Comment by fullstackwebdev** [comment]
I tried working on it for a few more hours, I was able to hack remix.run to run in CJS mode but it has issues. Will keep trying.


I found this site:
https://arethetypeswrong.github.io/?p=%40copilotkit%2Freact-core%400.14.0

![Screenshot from 2023-12-07 21-41-24](https://github.com/remix-run/remix/assets/10137946/c66e41c8-a149-4e10-85ed-46d80e342983)

**Comment by bartekus** [comment]
The solution to this is as @mao437303994 mentioned, **do not use** `serverDependenciesToBundle: 'all'` and instead explicitly define it as and array of specific packages to bundle: `serverDependenciesToBundle: ['some-package', 'another-package']`

**Comment by brophdawg11** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2. If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.

We plan to continue to address 2 types of issues in Remix v2:

- Bugs that pose security concerns
- Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so:

- If this is a bug, please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new [minimal reproduction](https://reactrouter.com/new) against v7
- If this is a feature request, please open a new [Proposal Discussion](https://github.com/remix-run/react-router/discussions/new?category=proposals) in React Router, and if it gets enough community support it can be considered for implementation

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
