### ISSUE TITLE
Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.

### ISSUE THREAD

**Issue by ric980** [remix-run/remix#7517]
### What version of Remix are you using?

2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I've upgraded to Remix 2.0 and my production site no longer runs. When executing `yarn start`, I got the following error:

```
yarn remix-serve build

/opt/app/.pnp.cjs:12680
  return Object.defineProperties(new Error(message), {
                                 ^
Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.

Source path: /opt/app/build
Not found: /opt/app/build

    at makeError (/opt/app/.pnp.cjs:12680:34)
    at resolveUnqualified (/opt/app/.pnp.cjs:14452:13)
    at resolveRequest (/opt/app/.pnp.cjs:14493:14)
    at Object.resolveRequest (/opt/app/.pnp.cjs:14549:26)
    at resolve$1 (file:///opt/app/.pnp.loader.mjs:1989:21)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:524:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1188:29)
```

I have no idea how to troubleshoot this one. For now, I've reverted back to Remix 1, but would be nice to upgrade to latest.

### Expected Behavior

My site runs.

### Actual Behavior

My site fails to run with this error:

> Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.

**Comment by brophdawg11** [comment]
Can you provide a minimal reproduction?

**Comment by ric980** [comment]
It seems to be related to Yarn PnP. But still, Yarn PnP is quite popular. Remix team should have tested v2 on it.

**Comment by ric980** [comment]
I've switched to "node-modules" linker and now it works with a tweak to the "start" script (I have to explicitly add the "index.js" file name to remix-serve). But my Docker image is 50 MB larger. Not good.

**Comment by brophdawg11** [comment]
> It seems to be related to Yarn PnP. But still, Yarn PnP is quite popular. Remix team should have tested v2 on it.

Remix does it's best to support popular package managers, but it's impossible to validate every single setup out there (npm, yarn 1/2/3, yarn pnp, pnpm, bun, etc.).  The base support is npm and yarn classic as those are by far the most popular.  

As requested, if you can provide a minimal reproduction repo we'd be happy to look into it.
