### ISSUE TITLE
TypeError: (0 , import_jsx_dev_runtime53.jsxDEV) is not a function

### ISSUE THREAD

**Issue by EvgeniyBudaev** [remix-run/remix#7530]
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

https://github.com/EvgeniyBudaev/marketplace/blob/main/frontend/package.json  Step 1: ```npm run dev``` Step 2: ```npm start```

### Expected Behavior

no errors

### Actual Behavior

TypeError: (0 , import_jsx_dev_runtime53.jsxDEV) is not a function
    at Object.<anonymous> (/home/ebudaev/Documents/Others/marketplace/frontend/app/uikit/components/Icon/IconType.tsx:113:24)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ebudaev/Documents/Others/marketplace/frontend/node_modules/@remix-run/serve/dist/cli.js:34:13)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)

**Comment by numbersmatter** [comment]
I have this exact same problem and it is killing my ability to push any new releases. This bug means all of my docker images built with Remix v.2 are no longer working. I cannot upload new Docker images to my Google Cloud Run and therefore cannot make changes to my application. 

I am searching for how to mark this as verified. I have reproduced it on a clean install of Remix on Friday, Nov 10, 2023.

**Comment by numbersmatter** [comment]
Okay, here is what found. I am now able to load this in Docker and not get the issue to occur. Here is what I did:

1. Deleted node_modules, build, and public folder 
2. updated from 18.15.0 -bullseye-slim image to 20.9.0-bulleye-slim image
3. moved  "ENV NODE_ENV=production" before the build step in my Docker file 

Not sure which of these things fixed the issue but the combination of them got my app back online after a gruelingly long night. 

Hope it helps the next person.

**Comment by brophdawg11** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2. If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.

We plan to continue to address 2 types of issues in Remix v2:

- Bugs that pose security concerns
- Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so:

- If this is a bug, please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new [minimal reproduction](https://reactrouter.com/new) against v7
- If this is a feature request, please open a new [Proposal Discussion](https://github.com/remix-run/react-router/discussions/new?category=proposals) in React Router, and if it gets enough community support it can be considered for implementation

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
