### ISSUE TITLE
Bootstrapping a 1.x Remix project using express is not working

### ISSUE THREAD

**Issue by keul** [remix-run/remix#7557]
### What version of Remix are you using?

1.19.13

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I'm using *node 18* and I just want to run the create-remix CLI, but using express instead of default server.

```
npx create-remix@1
? Where would you like to create your app? ./my-remix-app-2
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment targets. Express Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
```

### Expected Behavior

The dev server documented should work! 

### Actual Behavior

First problem: the server will not start running `npm run dev`:

```
Error: Could not locate @remix-run/serve. Verify that you have it installed to use the dev command.
    at tryImport (/private/tmp/test-remix/my-remix-app-2/node_modules/@remix-run/dev/dist/devServer/serve.js:36:11)
    at Object.serve (/private/tmp/test-remix/my-remix-app-2/node_modules/@remix-run/dev/dist/devServer/serve.js:45:7)
    at Object.dev (/private/tmp/test-remix/my-remix-app-2/node_modules/@remix-run/dev/dist/cli/commands.js:232:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (/private/tmp/test-remix/my-remix-app-2/node_modules/@remix-run/dev/dist/cli/run.js:515:7)
```

I found some closed issues with this error, I fixed installing `@remix-run/serve` manually (verified is still version 1.19.13):

```
npm install @remix-run/serve@1.19
```

Now the server starts with `npm run dev`, but accessing the app I get:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /private/tmp/test-remix/my-remix-app-2/build/index.js from /private/tmp/test-remix/my-remix-app-2/node_modules/@remix-run/serve/dist/index.js not supported.
Instead change the require of /private/tmp/test-remix/my-remix-app-2/build/index.js in /private/tmp/test-remix/my-remix-app-2/node_modules/@remix-run/serve/dist/index.js to a dynamic import() which is available in all CommonJS modules.
    at /private/tmp/test-remix/my-remix-app-2/node_modules/@remix-run/serve/dist/index.js:43:17
    at Layer.handle [as handle_request] (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/layer.js:95:5)
    at next (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/route.js:144:13)
    at next (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/route.js:140:7)
    at next (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/route.js:140:7)
    at next (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/route.js:140:7)
    at next (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/route.js:140:7)
    at next (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/route.js:140:7)
    at next (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/route.js:140:7)
    at Route.dispatch (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/layer.js:95:5)
    at /private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/index.js:284:15
    at param (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/index.js:365:14)
    at param (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/index.js:421:3)
    at next (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/index.js:280:10)
    at logger (/private/tmp/test-remix/my-remix-app-2/node_modules/morgan/index.js:144:5)
    at Layer.handle [as handle_request] (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/index.js:328:13)
    at /private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/index.js:346:12)
    at next (/private/tmp/test-remix/my-remix-app-2/node_modules/express/lib/router/index.js:280:10)
    at SendStream.error (/private/tmp/test-remix/my-remix-app-2/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:513:28)
    at SendStream.error (/private/tmp/test-remix/my-remix-app-2/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/private/tmp/test-remix/my-remix-app-2/node_modules/send/index.js:417:12)
    at next (/private/tmp/test-remix/my-remix-app-2/node_modules/send/index.js:759:28)
    at /private/tmp/test-remix/my-remix-app-2/node_modules/send/index.js:767:23
    at FSReqCallback.oncomplete (node:fs:208:21)
```

**Comment by brophdawg11** [comment]
Is there a reason you're using `npx create-remix@1`?  That's the root cause of the issue here as the CLI pulls templates from the `main` branch - and now that v2 has been released, those templates are all designed to work with Remix v2.  So you are ending up with a v2 Express template but v1 Remix dependencies.

I would suggest installing a v2 app using the v2 template (in v2 the CLI dropdown was removed, so you just use the [--template](https://remix.run/docs/en/main/guides/templates#official-templates) flag now):

```sh
npx create-remix --template remix-run/remix/templates/express
```

However, if there's a specific reason you need to use v1, you will need to point at the template from a v1 tag:

```sh
npx create-remix@1 --template https://github.com/remix-run/remix/tree/remix%401.19.3/templates/express
```

Or, you could clone the remix repo, checkout that `remix@1.19.13` tag, and install from the local repo:

```sh
npx create-remix@1 --template ../path/to/remix/templates/express
```

**Comment by keul** [comment]
OK so what a user has to do if he goes on the old documentation _today_?

No one of these informations can be found there: https://remix.run/docs/en/1.19.3/tutorials/jokes#generating-a-new-remix-project

**Comment by brophdawg11** [comment]
Unfortunately, we cannot update `1.19.3` docs since they are a snapshot of the docs from a tagged Git release.  This is a bit of an edge case though, since we expect the vast majority of users to use the _current_ Remix version when running `create-remix`.  We could potentially add a section in the current docs about what to do for older versions, so if you wanted to PR a proposed update there we may be able to get that included - but I don't think this will generally be a big surface area for issues.

**Comment by dwjohnston** [comment]
@brophdawg11  I've just run into this issue. 

The reason I'm using remix@1 is because my existing project is using that, I'm trying to diagnose an issue. I haven't been able to reproduce this issue on remix@2 so I'm wondering if it's something specific to remix@1.

**Comment by brophdawg11** [comment]
You can bootstrap a new v1 app using a manual template specification ([see above](https://github.com/remix-run/remix/issues/7557#issuecomment-1743212116)).  That should be enough to get you a fresh v1 app to triage your issue.

```
npx create-remix@1.19.3 --template https://github.com/remix-run/remix/tree/remix%401.19.3/templates/express
```
