### ISSUE TITLE
First parameter has member 'readable' that is not a ReadableStream (with @vercel/blob)

### ISSUE THREAD

**Issue by jorisre** [remix-run/remix#7614]
### What version of Remix are you using?

2 and 1.19

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Start a new project using Remix
2. Add `@vercel/blob` package
3. Call the `list` function of `@vercel/blob` from a Remix loader
4. 💥 Error happen: 
> throw new TypeError(`${context} is not a ReadableStream.`);
>         ^
>TypeError: First parameter has member 'readable' that is not a ReadableStream.

This CodeSandbox shows the error, does anyone know a workaround?

https://codesandbox.io/p/sandbox/sparkling-flower-hmrkj4

### Expected Behavior

Should not throw an error and return the blobs

### Actual Behavior

It throws the following error:

>  info  building...
> info  built (537ms)
> [remix-serve] http://localhost:3000 (http://192.168.1.102:3000)

> /Users/joris/w/blob/node_modules/web-streams-polyfill/src/lib/validators/readable-stream.ts:5
>    throw new TypeError(`${context} is not a ReadableStream.`);
>          ^
>TypeError: First parameter has member 'readable' that is not a ReadableStream.
>    at assertReadableStream (/Users/joris/w/blob/node_modules/web-streams-polyfill/src/lib/validators/readable-stream.ts:5:11)
>    at convertReadableWritablePair (/Users/joris/w/blob/node_modules/web-streams-polyfill/src/lib/validators/readable-writable-pair.ts:15:3)
>    at ReadableStream.pipeThrough (/Users/joris/w/blob/node_modules/web-streams-polyfill/src/lib/readable-stream.ts:211:23)
>    at fetchFinale (/Users/joris/w/blob/node_modules/undici/lib/fetch/index.js:973:52)
>    at mainFetch (/Users/joris/w/blob/node_modules/undici/lib/fetch/index.js:773:5)
>    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by nakleiderer** [comment]
I ran into this issue as well when enqueuing a job with BullMQ. Since this was occurring in the Node-side of my application (I'm running a custom server), I removed the `installGlobals()` call. After this, my BullMQ jobs enqueued successfully. 

```
  System:
    OS: macOS 14.1.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.77 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.asdf/installs/nodejs/20.10.0/bin/node
    npm: 10.2.3 - ~/.asdf/plugins/nodejs/shims/npm
  npmPackages:
    @remix-run/dev: ^2.3.1 => 2.3.1 
    @remix-run/eslint-config: ^2.3.1 => 2.3.1 
    @remix-run/express: ^2.3.1 => 2.3.1 
    @remix-run/node: ^2.3.1 => 2.3.1 
    @remix-run/react: ^2.3.1 => 2.3.1 
    bullmq: ^4.15.0 => 4.15.0 
```

```js
module.exports = {
  appDirectory: "src",
  cacheDirectory: "./node_modules/.cache/remix",
  ignoredRouteFiles: ["**/.*", "**/*.css", "**/*.test.{js,jsx,ts,tsx}"],
  serverModuleFormat: "esm",
  serverPlatform: "node",
  watchPaths: ["./tailwind.config.cjs"],
};
```

**Comment by maxfi** [comment]
Possibly related: https://github.com/vercel/remix/issues/62#issuecomment-2041038392

**Comment by brophdawg11** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2. If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.

We plan to continue to address 2 types of issues in Remix v2:

- Bugs that pose security concerns
- Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so:

- If this is a bug, please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new [minimal reproduction](https://reactrouter.com/new) against v7
- If this is a feature request, please open a new [Proposal Discussion](https://github.com/remix-run/react-router/discussions/new?category=proposals) in React Router, and if it gets enough community support it can be considered for implementation

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
