### ISSUE TITLE
can be used with video.js ?

### ISSUE THREAD

**Issue by MaeThird** [remix-run/remix#7662]
### What version of Remix are you using?

v2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I'm adding the video player into my code as introduced here https://videojs.com/guides/react/ in both Functional Component and Class Component ways. **In both of the two ways the player can play videos with errors logged in console.**

If i commented out the video player there was no error in the console and if i use react not remix the player can work without errors.

### Expected Behavior

no error logged 

### Actual Behavior

```
react-dom.development.js:19849 Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
    at updateHostRoot (react-dom.development.js:19849:57)
    at beginWork (react-dom.development.js:21615:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:22)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)


Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:12507:9)
    at tryToClaimNextHydratableInstance (react-dom.development.js:12535:7)
    at updateHostComponent (react-dom.development.js:19902:5)
    at beginWork (react-dom.development.js:21618:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopConcurrent (react-dom.development.js:26543:5)
    at renderRootConcurrent (react-dom.development.js:26505:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:38)
    at workLoop (scheduler.development.js:266:34)

react-dom.development.js:86 Warning: Expected server HTML to contain a matching <link> in <head>.
    at link
    at head
    at html
    at App
    at RenderedRoute (http://localhost:3000/build/_shared/chunk-ZNNPKVHX.js:3678:5)
    at RenderErrorBoundary (http://localhost:3000/build/_shared/chunk-ZNNPKVHX.js:4250:9)
    at DataRoutes (http://localhost:3000/build/_shared/chunk-ZNNPKVHX.js:3964:5)
    at Router (http://localhost:3000/build/_shared/chunk-ZNNPKVHX.js:4043:15)
    at RouterProvider (http://localhost:3000/build/_shared/chunk-ZNNPKVHX.js:3913:5)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-ZNNPKVHX.js:6542:5)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-ZNNPKVHX.js:7134:40)

```

**Comment by MaeThird** [comment]
if i use use this player https://www.npmjs.com/package/react-player  + remix the error(if just react there is no error):
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at renderElement (/home/mae/UI/proj1/node_modules/react-dom/cjs/react-dom-server.node.development.js:6109:9)
    at renderNodeDestructiveImpl (/home/mae/UI/proj1/node_modules/react-dom/cjs/react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (/home/mae/UI/proj1/node_modules/react-dom/cjs/react-dom-server.node.development.js:6142:14)
    at renderNode (/home/mae/UI/proj1/node_modules/react-dom/cjs/react-dom-server.node.development.js:6325:12)
    at renderHostElement (/home/mae/UI/proj1/node_modules/react-dom/cjs/react-dom-server.node.development.js:5708:3)
    at renderElement (/home/mae/UI/proj1/node_modules/react-dom/cjs/react-dom-server.node.development.js:6018:5)
    at renderNodeDestructiveImpl (/home/mae/UI/proj1/node_modules/react-dom/cjs/react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (/home/mae/UI/proj1/node_modules/react-dom/cjs/react-dom-server.node.development.js:6142:14)
    at renderNode (/home/mae/UI/proj1/node_modules/react-dom/cjs/react-dom-server.node.development.js:6325:12)
    at renderChildrenArray (/home/mae/UI/proj1/node_modules/react-dom/cjs/react-dom-server.node.development.js:6277:7)
```
It looks like reat-dom conflict with remix ?

**Comment by sergiodxa** [comment]
The error on the original message is a hydration warning from React.

A hydration warning doesn’t mean you app won’t work, it will just ditch the server side rendered html and generate the whole DOM again client side, which may be a few ms slower as much.

The hydration happens because what your server rendered as html and what React rendered while hydrating the app differs, most likely is because the video player is rendering something different on SSR and on CSR.

One quick way to solve it could be to use the ClientOnly component from remix-utils to delay the rendering of your video player until after hydration happened, this way it will not cause a hydration issue.

**Comment by MaeThird** [comment]
I tried with "remix-utils": "^7.1.0 but it does't work with the same error. I changed it to the raw ```video ```tag it's clean now.
