### ISSUE TITLE
HMR plugin does not support import attributes/Babel configuration

### ISSUE THREAD

**Issue by luzat** [remix-run/remix#7764]
### What version of Remix are you using?

2.1.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

When trying to import JSON files in an ESM build on Node 17.5+, import assertions are required:

```
import x from './foo.json' assert { type: 'json' }
// Or, for Node 21+: import x from './foo.json' with { type: 'json' }
```

An error does occur with a plain import:

```
import x from './foo.json'
```

```
TypeError: Module "file:///.../foo.json" needs an import assertion of type "json"
```

Adding `assert { type: 'json' }` fails when serving the app (`binode --import ./mocks/index.js -- @remix-run/serve:remix-serve ./build/index.js`) with the HMR compiler plugin:

```
✘ [ERROR] /home/.../app/foo.ts: Support for the experimental syntax 'importAttributes' isn't currently enabled (13:60)
…
Add @babel/plugin-syntax-import-attributes (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-import-attributes) to the 'plugins' section of your Babel config to enable parsing. [plugin remix-hmr]
…
This error came from the "onLoad" callback registered here:

    node_modules/@remix-run/dev/dist/compiler/js/plugins/hmr.js:149:12:
      149 │       build.onLoad({
          ╵             ~~~~~~

    at setup (/home/tom/Projects/…/node_modules/@remix-run/dev/dist/compiler/js/plugins/hmr.js:149:13)
    at handlePlugins (/home/tom/Projects/…/node_modules/esbuild/lib/main.js:1279:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Expected Behavior

I would like to see the code work with HMR, either by having the Babel plugin included or an option to allow extending the hard-coded Babel options. Support for the deprecated `assert` (vs. `with`) syntax should preferably [be enabled](https://babeljs.io/docs/babel-plugin-syntax-import-attributes#deprecatedassertsyntax) to allow working with different Node versions and ease migration to ESM.

### Actual Behavior

Serving with HMR is not possible and it's hard to work around that: Some modules hardly work with CJS currently (like `remix-utils`).

**Comment by renaatdemuynck** [comment]
I can conform this bug.
Switched from Remix v1.19 to v2.4 and using ESM as default instead of CJS.

**Comment by brookslybrand** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!  

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2.  If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.  

We plan to continue to address 2 types of issues in Remix v2:

* Bugs that pose security concerns
* Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new minimal reproduction against v7.

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
