### ISSUE TITLE
Docs incorrectly suggest `remix-serve --port 5000 ./build/index.js`

### ISSUE THREAD

**Issue by jakubmazanec** [remix-run/remix#7830]
### What version of Remix are you using?

2.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create new Remix app using `npx create-remix@latest --template remix-run/remix/templates/fly`, install dependencies, build the app.
2. Run `npx remix-serve ./build/index.js --port 5000`.
3. Observe the actual port number.

Also, `npx remix-serve --port 5000 ./build/index.js` doesn't work at all.

### Expected Behavior

According to this page https://remix.run/docs/en/main/other-api/dev#setting-a-custom-port, the app server should listen on the port I specified. 

### Actual Behavior

Port is random. Looking at the source code here https://github.com/remix-run/remix/blob/main/packages/remix-serve/cli.ts I see the port is only generated randomly, or taken from `PORT` env var. Or am I missing something?

**Comment by pcattori** [comment]
From the docs you linked:

> The remix dev --port option sets the internal port used for hot updates. It does not affect the port your app runs on.

If you want to set the port for your app server (in this case, `remix-serve`) you should use whatever mechanism you would use in prod (in this case the `PORT` env var).

**Comment by jakubmazanec** [comment]
@pcattori, thanks for the reply, but I'm not talking about `--port` option for `remix dev`, but for `remix-serve`. From the docs I linked, just below the part you quoted:

> If you are using remix-serve as your app server, you can use its --port flag to set the app server port:
> `remix dev -c "remix-serve --port 8000 ./build/index.js"`

So the documentation _is_ talking about **app** server. I'm okay with using `PORT` env variable, but then the documentation seems misleading.

**Comment by jakubmazanec** [comment]
Also, if you run it like it is specified in the documentation, i. e. `npx remix-serve --port 8000 ./build/index.js`, you get this error:

```
Error: ENOENT: no such file or directory, stat '\my-remix-app\--port'
    at Object.stat (node:internal/fs/sync:58:25)
    at Object.statSync (node:fs:1669:17)
    at reimportServer (\my-remix-app\node_modules\@remix-run\serve\dist\cli.js:69:39)
    at run (\my-remix-app\node_modules\@remix-run\serve\dist\cli.js:98:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Because of https://github.com/remix-run/remix/blob/20a3f7306119b393b9d9b67c22b241739ed6e7d4/packages/remix-serve/cli.ts#L36

**Comment by dan-cooke** [comment]
This is a real issue, for bootstrapping a quick remix project with app sever - you are unable to change the port.

Additionally setting `PORT` with the app server seems to cause a port conflict - it appears some other process (maybe the websocket?) is also reading from PORT env variable
