### ISSUE TITLE
Issues in @reduxjs/toolkit

### ISSUE THREAD

**Issue by emyot** [remix-run/remix#7938]
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

index.ts file in the store directory

// import { configureStore, combineReducers } from "@reduxjs/toolkit";

import pkg from "@reduxjs/toolkit";
const { configureStore, combineReducers } = pkg;

import skillNumArrSlice from "./skill-slice";
import workExpSlice from "./workExp-slice";
import certificateSlice from "./certificate-slice";
import eductBGSlice from "./eductBG-slice";
import parentInfoSlice from "./parentInfo-slice";
import charRefSlice from "./charReference-slice";
import basicInfoLanguageSlice from "./basicInfo-Language-slice";

const allReducers = combineReducers({
  workExp: workExpSlice.reducer,
  certificate: certificateSlice.reducer,
  eductBG: eductBGSlice.reducer,
  parentInfo: parentInfoSlice.reducer,
  charRef: charRefSlice.reducer,
  skillNumArr: skillNumArrSlice.reducer,
  basicInfoLangStateArr: basicInfoLanguageSlice.reducer,
});

export type RootState = ReturnType<typeof allReducers>;

const store = configureStore({
  reducer: {
    workExp: workExpSlice.reducer,
    certificate: certificateSlice.reducer,
    eductBG: eductBGSlice.reducer,
    parentInfo: parentInfoSlice.reducer,
    charRef: charRefSlice.reducer,
    skillNumArr: skillNumArrSlice.reducer,
    basicInfoLangStateArr: basicInfoLanguageSlice.reducer,
  },
});

export default store;

root.tsx route file in app directory
import { cssBundleHref } from "@remix-run/css-bundle";
import type { LinksFunction } from "@remix-run/node";
import {
  Links,
  LiveReload,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
} from "@remix-run/react";

import { Provider } from "react-redux";

import store from "./store";

export const links: LinksFunction = () => [
  ...(cssBundleHref
    ? [{ rel: "stylesheet", href: cssBundleHref }]
    : [
        {
          rel: "stylesheet",
          href: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css",
        },
      ]),
];

interface Props {
  children: React.ReactNode;
}

const Document = ({ children }: Props) => {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Meta />
        <Links />
      </head>
      <body>
        {children}
        <ScrollRestoration />
        <Scripts />
        <LiveReload />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
          integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
          crossOrigin="anonymous"
        ></script>
      </body>
    </html>
  );
};

export default function App() {
  return (
    <Document>
      <Provider store={store}>
        <Outlet />
      </Provider>
    </Document>
  );
}

### Expected Behavior

To run without errors.

Note: Don't have any problems in the pervious Remix version before 2.0

### Actual Behavior

It's giving me this error:

C:\Users\admin\Documents\Remix-Projects\remix-v2-testapp>npm run dev

> dev
> remix dev --manual

 �💿  remix d

 info  building...
X [ERROR] Build failed with 1 error:    
app/store/index.ts:3:7: ERROR: No matching export in "node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js" for import "default" [plugin css-bundle-plugin]  

    app/root.tsx:20:30:
      20 │ import { cssBundleHref } from "@remix-run/css-bundle";
         ╵
 ~~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onLoad" callback registered here:

    node_modules/@remix-run/dev/dist/compiler/plugins/cssBundlePlugin.js:35:12: 
      35 │       build.onLoad({
         ╵             ~~~~~~

    at setup (C:\Users\admin\Documents\Remix-Projects\remix-v2-testapp\node_modules\@remix-run\dev\dist\compiler\plugins\cssBundlePlugin.js:35:13)
    at handlePlugins (C:\Users\admin\Documents\Remix-Projects\remix-v2-testapp\node_modules\esbuild\lib\main.js:1279:21)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by emyot** [comment]
Ignore this report, I'm having this issues when using the esmodule but when I switched to vite I no longer have this problems at all.

**Comment by tbscode** [comment]
Had the same issue once, don't remember where I found the fix but this solved a similar error for me:

```js
import * as toolkitRaw from "@reduxjs/toolkit";
const { configureStore } = toolkitRaw.default ?? toolkitRaw;
```

**Comment by brookslybrand** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!  

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2.  If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.  

We plan to continue to address 2 types of issues in Remix v2:

* Bugs that pose security concerns
* Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new minimal reproduction against v7.

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
