### ISSUE TITLE
remix.init script fails on latest create-remix

### ISSUE THREAD

**Issue by andrelandgraf** [remix-run/remix#7951]
### What version of Remix are you using?

2.2.0, 2.3.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- Create new Remix project (`npx create-remix@latest`)
- Add `remix.init` folder
- Add `remix.init/index.js` file:

```js
console.log("Greetings from remix.init :)");

process.exit();
```

- Use the new template to create a new Remix app: `npx create-remix@latest --template <template-url>`

### Expected Behavior

Remix init script runs successfully.

### Actual Behavior

```bash
  init   This template has a remix.init script. Do you want to run it?
         Yes

      ✔  Dependencies installed

      ✔  Git initialized

      ◼  Running template's remix.init script... 


      ▲  Oh no! Template's remix.init script failed
```

Running `npx remix init` indicates an ESM error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/andrelandgraf/workspaces/tests/using-template/remix.init/index.js from /Users/andrelandgraf/workspaces/tests/using-template/node_modules/@remix-run/dev/dist/cli/commands.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/andrelandgraf/workspaces/tests/using-template/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.init (/Users/andrelandgraf/workspaces/tests/using-template/node_modules/@remix-run/dev/dist/cli/commands.js:97:16)
    at async Object.run (/Users/andrelandgraf/workspaces/tests/using-template/node_modules/@remix-run/dev/dist/cli/run.js:167:7) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by andrelandgraf** [comment]
Renaming `remix.init/index.js` to `remix.init/index.cjs` fixes the error but doesn't seem to execute the code? At least the console log is not printed on the terminal.

**Comment by leothorp** [comment]
The docs don't explicitly mention this, but from what I can tell the minimal way to have a working remix.init script with the is to do the following.

1. add a remix.init/package.json file that declares the directory as a commonjs module (necessary because it ends up being imported with `require`, hence that error message). Example:
```package.json
{
  "main": "index.js"
}
```
3. modify your remix.init/index.js to export a function which, when executed, carries out your init steps. In this case, something like:
```js
module.exports = () => console.log('Greetings from remix.init :)');
```

Minimal adaptation of this example in this stackblitz, see the remix.init directory: https://stackblitz.com/edit/remix-run-remix-63vl7y?file=remix.init%2Findex.js    

Running `npx remix init` in that project prints `Greetings from remix.init :)` as expected.

**Comment by garand** [comment]
Ran into this and added a new package.json file in the remix.init directory with just this:

```json
{
  "type": "commonjs"
}
```

And it works for me.

**Comment by brophdawg11** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2. If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.

We plan to continue to address 2 types of issues in Remix v2:

- Bugs that pose security concerns
- Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so:

- If this is a bug, please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new [minimal reproduction](https://reactrouter.com/new) against v7
- If this is a feature request, please open a new [Proposal Discussion](https://github.com/remix-run/react-router/discussions/new?category=proposals) in React Router, and if it gets enough community support it can be considered for implementation

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
