### ISSUE TITLE
Can't import JSON file from installed module

### ISSUE THREAD

**Issue by vixalien** [remix-run/remix#8131]
### Reproduction

Can't import JSON documents in app.

```js
import translations from "@shopify/polaris/locales/en.json" assert {
  type: "json",
};
```

### System Info

```shell
System:
    OS: Linux 6.6 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 439.21 MB / 7.33 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.5.1/bin/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
    pnpm: 8.10.5 - /usr/bin/pnpm
    bun: 1.0.13 - /usr/bin/bun
  npmPackages:
    @remix-run/css-bundle: ^2.3.0 => 2.3.0 
    @remix-run/dev: ^2.3.0 => 2.3.0 
    @remix-run/eslint-config: ^2.3.0 => 2.3.0 
    @remix-run/node: ^2.3.0 => 2.3.0 
    @remix-run/react: ^2.3.0 => 2.3.0 
    @remix-run/serve: ^2.3.0 => 2.3.0
```

### Used Package Manager

yarn

### Expected Behavior

I would expect the import to be imported correctly.

### Actual Behavior

It fails with the following error log:

```
✘ [ERROR] /home/alien/sites/rwarrims5/app/polaris/index.tsx: Support for the experimental syntax 'importAttributes' isn't currently enabled (16:61):

  14 |
  15 | import { AppProvider } from "@shopify/polaris";
> 16 | import translations from "@shopify/polaris/locales/en.json" assert {
     |                                                             ^
  17 |   type: "json",
  18 | };
  19 |

Add @babel/plugin-syntax-import-attributes (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-import-attributes) to the 'plugins' section of your Babel config to enable parsing. [plugin remix-hmr]

    app/root.tsx:22:28:
      22 │ import PolarisProvider from "./polaris";
         ╵                             ~~~~~~~~~~~

  This error came from the "onLoad" callback registered here:

    node_modules/@remix-run/dev/dist/compiler/js/plugins/hmr.js:149:12:
      149 │       build.onLoad({
          ╵             ~~~~~~

    at setup (/home/alien/sites/rwarrims5/node_modules/@remix-run/dev/dist/compiler/js/plugins/hmr.js:149:13)
    at handlePlugins (/home/alien/sites/rwarrims5/node_modules/esbuild/lib/main.js:1279:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


```

**Comment by vixalien** [comment]
It seems I cannot JSON files stored in `node_modules`.

**Comment by Dhanush-gitt** [comment]
facing the same issue.

**Comment by tobi110289** [comment]
Same problem here
<img width="1062" alt="Screenshot 2023-11-30 at 18 20 33" src="https://github.com/remix-run/remix/assets/63813520/e0848ba1-b062-4d0d-a964-29ce1b5d318f">

**Comment by jseparovic** [comment]
Same issue here. Is there a workaround?

**Comment by vixalien** [comment]
Not really a solution, but switching to Vite eliminates the issue. in production, I currently move the JSON files inside my source repo temporarily

**Comment by nullndr** [comment]
This is quite annoying because it is blocking me to upgrade my entire project to ESM. Any news?

**Comment by gyenabubakar** [comment]
Has anyone found a solution to this? I've created an [issue in the Shopify Remix template repo](https://github.com/Shopify/shopify-app-template-remix/issues/692).

**Comment by brophdawg11** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2. If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.

We plan to continue to address 2 types of issues in Remix v2:

- Bugs that pose security concerns
- Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so:

- If this is a bug, please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new [minimal reproduction](https://reactrouter.com/new) against v7
- If this is a feature request, please open a new [Proposal Discussion](https://github.com/remix-run/react-router/discussions/new?category=proposals) in React Router, and if it gets enough community support it can be considered for implementation

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
