### ISSUE TITLE
Build error when importing CSS file

### ISSUE THREAD

**Issue by jchimes5308** [remix-run/remix#8178]
### Reproduction

This is so basic, it must have been seen before. I just really need a workaround. I used npx to create a new project on Windows 10, Remix version 2.3.1. In the app/root.tsx file I replaced the links function with the following:
_import mainCss from '~/pagestyles/shared.css';
export const links: LinksFunction = () => [{ rel: "stylesheet", href: mainCss }];_
The file /app/jpagestyles/shared.css contains one line of css. When I execute npm run dev I get the following error:
The following error is a bug in Remix; please open an issue! https://github.com/remix-run/remix/issues/new
X [ERROR] entry file not found [plugin css-file]

    app/root.tsx:12:20:
      12 │ import mainCss from '~/pagestyles/shared.css';
         ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~
Am I missing something? This is too basic of a task. Is there another way to do this?

### System Info

```shell
Windows 10, Remix 2.3.1, plain, unedited project created by npx create-remix@latest
```

### Used Package Manager

npm

### Expected Behavior

Inject my css file into the HTML header without a compler error.

### Actual Behavior

Compiler error as described.

**Comment by brophdawg11** [comment]
This seems to be working ok in stackblitz: https://stackblitz.com/edit/remix-run-remix-eoyucp?file=app%2Froot.tsx

Can you download that repo, run `npm ci` and run it locally and see if it works for you there?  It seems like something local to your machine, or potentially Windows specific (I don't have a Windows machine to test on)

**Comment by jchimes5308** [comment]
Thanks brophdawg for having a look at this! I downloaded and ran on my box, and sure enough got the same error. Note that I am able to compile and run multi page apps using Remix. This only happens when I attempt to import a .css file for use in the links function. So a Windows file system issue? Are there any Windows experts out there who have seen something like this?

**Comment by jchimes5308** [comment]
I found this github link regarding Remix 1 that appears to be my exact issue. The developers seem to think the issue was fixed and closed, but at the end is a mysterious comment that it turned up in v2 also. Perhaps someone out there worked on this issue and can help me with a workaround or fix? Thanks! [https://github.com/remix-run/remix/issues/4726](url)

**Comment by jchimes5308** [comment]
I found a solution (or more accurately, a workaround): Install WSL and run it from there. Works perfectly! Clearly a Windows issue.

**Comment by nathanqueija** [comment]
I am getting the same error, even just importing a simple CSS file throws the error. The weird thing is that this was not happening before. I don't know exactly what triggered this. The import itself doesn't break the build, but as soon as I use the import, e.g., returning in the links function or just by trying to console.log its content the build fails with the error above.

**Comment by nathanqueija** [comment]
For people also getting this error: make sure you don't have any errors in your tailwind config file. I was missing a comma somewhere and this was the reason.

**Comment by foresterre** [comment]
I have the same issue after installing tailwind following the [instructions] in the docs:

```
X [ERROR] entry file not found [plugin css-file]

    node_modules/@remix-run/dev/dist/compiler/plugins/cssImports.js:174:30:
      174 │           invariant["default"](entryFile, "entry file not found");
          ╵                               ^

    at Object.invariant [as default] (D:\try\remix-trial\node_modules\@remix-run\dev\dist\invariant.js:18:11)
    at D:\try\remix-trial\node_modules\@remix-run\dev\dist\compiler\plugins\cssImports.js:174:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  This error came from the "onLoad" callback registered here:

    node_modules/@remix-run/dev/dist/compiler/plugins/cssImports.js:77:12:
      77 │       build.onLoad({
         ╵             ~~~~~~

    at setup (D:\try\remix-trial\node_modules\@remix-run\dev\dist\compiler\plugins\cssImports.js:77:13)
    at handlePlugins (D:\try\remix-trial\node_modules\esbuild\lib\main.js:1279:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  The plugin "css-file" was triggered by this import

    app/root.tsx:15:23:
      15 │ import stylesheet from "~/tailwind.css";
         ╵                        ~~~~~~~~~~~~~~~~
```

**Comment by jchimes5308** [comment]
foresterre: I was unable to solve this issue using Windows. I installed WSL on my Windows 10 machine and it's been smooth sailing ever since. Also, developing on WSL is a faster and superior experience in general.

**Comment by foresterre** [comment]
> foresterre: I was unable to solve this issue using Windows. I installed WSL on my Windows 10 machine and it's been smooth sailing ever since. Also, developing on WSL is a faster and superior experience in general.

That's unfortunate 😔: I rather not use WSL on my Windows machine; in the meantime I've tried getting it to work on my Linux machine, and indeed there it does seem to work out of the box.

Perhaps the most frustrating part was that, as someone unfamiliar with these libraries, it's not easy to find a solution or workaround based on this error message.

**Comment by brookslybrand** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!  

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2.  If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.  

We plan to continue to address 2 types of issues in Remix v2:

* Bugs that pose security concerns
* Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new minimal reproduction against v7.

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
