### ISSUE TITLE
Unable to gracefully handle the `exceeded upload size` error in uploadHandler

### ISSUE THREAD

**Issue by adanielyan** [remix-run/remix#8213]
### Reproduction

I have a route with a `<Form>` that has a file field. In my action I have the following code:
```ts
const contentType = request.headers.get("Content-Type");
if (contentType?.includes("multipart/form-data")) {
    try {
      const uploadHandler = unstable_createMemoryUploadHandler({
        maxPartSize: 500_000,
      });
      formData = await unstable_parseMultipartFormData(request, uploadHandler);
      if (!formData) {
        return json({ error: "Failed to parse form data" });
      }
      const file = formData.get("file");
      console.log({ file });
    } catch (error: any) {
      console.error("unstable_parseMultipartFormData", error); // <-- this works
      return json({ error: error.message }); // <-- this doesn't work
    }
  } else if (contentType?.includes("application/x-www-form-urlencoded")) {
    formData = await request.formData();
  } else {
    return json({ error: "Invalid content type" });
  }
```

I expect the `catch` block to return a json with an error when the file size exceeds 500KB The error log message is logged, however, instead of returning a json with an error the app "crashes" after waiting for a response for a few seconds and I get this error message on the page:

```
TypeError: Failed to fetch
    at fetchData (http://127.0.0.1:3000/build/_shared/chunk-LAK5XBJ4.js:7108:24)
    at async fetchServerHandler (http://127.0.0.1:3000/build/_shared/chunk-LAK5XBJ4.js:7384:16)
    at async callLoaderOrAction (http://127.0.0.1:3000/build/_shared/chunk-LAK5XBJ4.js:2680:16)
    at async handleAction (http://127.0.0.1:3000/build/_shared/chunk-LAK5XBJ4.js:1298:16)
    at async startNavigation (http://127.0.0.1:3000/build/_shared/chunk-LAK5XBJ4.js:1246:26)
    at async Object.navigate (http://127.0.0.1:3000/build/_shared/chunk-LAK5XBJ4.js:1174:12)
```

What am I doing wrong?

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 334.41 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
  Browsers:
    Chrome: 119.0.6045.199
    Safari: 17.1
  npmPackages:
    @remix-run/css-bundle: ^2.2.0 => 2.2.0 
    @remix-run/dev: ^2.2.0 => 2.2.0 
    @remix-run/eslint-config: ^2.2.0 => 2.2.0 
    @remix-run/node: ^2.2.0 => 2.2.0 
    @remix-run/react: ^2.2.0 => 2.2.0 
    @remix-run/serve: ^2.2.0 => 2.2.0
```

### Used Package Manager

npm

### Expected Behavior

When the file size exceeds the set limit a json with an error should be returned.

### Actual Behavior

Instead of returning a json with an error the app "crashes" after waiting for a response for a few seconds and I get this error message on the page:

```
TypeError: Failed to fetch
    at fetchData (http://127.0.0.1:3000/build/_shared/chunk-LAK5XBJ4.js:7108:24)
    at async fetchServerHandler (http://127.0.0.1:3000/build/_shared/chunk-LAK5XBJ4.js:7384:16)
    at async callLoaderOrAction (http://127.0.0.1:3000/build/_shared/chunk-LAK5XBJ4.js:2680:16)
    at async handleAction (http://127.0.0.1:3000/build/_shared/chunk-LAK5XBJ4.js:1298:16)
    at async startNavigation (http://127.0.0.1:3000/build/_shared/chunk-LAK5XBJ4.js:1246:26)
    at async Object.navigate (http://127.0.0.1:3000/build/_shared/chunk-LAK5XBJ4.js:1174:12)
```

**Comment by maddalax** [comment]
If you are still running into this, i fixed it for now by coping the remix in memory upload handler that doesn't throw the error, but instead returns a string. Not ideal but works for now.

```
import type { UploadHandler } from '@remix-run/server-runtime';
import type { MemoryUploadHandlerOptions } from '@remix-run/server-runtime/dist/upload/memoryUploadHandler';
import type { UploadHandlerPart } from '@remix-run/server-runtime/dist/formData';

export function createCustomMemoryUploadHandler({
  filter,
  maxPartSize = 3000000,
}: MemoryUploadHandlerOptions = {}): UploadHandler {
  return async ({ filename, contentType, name, data }: UploadHandlerPart) => {
    if (
      filter &&
      !(await filter({
        filename,
        contentType,
        name,
      }))
    ) {
      return undefined;
    }
    let size = 0;
    let chunks = [];
    for await (let chunk of data) {
      size += chunk.byteLength;
      if (size > maxPartSize) {
        /**
         * Remix seems to throw an error we cannot handle in their existing implementation, so i just copied their implementation
         * and modified it to return an object with an error property, instead of throwing
         */
        return 'error: file too large';
      }
      chunks.push(chunk);
    }
    if (typeof filename === 'string') {
      return new File(chunks, filename, {
        type: contentType,
      });
    }
    return await new Blob(chunks, {
      type: contentType,
    }).text();
  };
}
```
