### ISSUE TITLE
ffmpeg/WASM

### ISSUE THREAD

**Issue by PaulieScanlon** [remix-run/remix#8215]
### Reproduction

Reproduction repo: [remix-ffmpeg-wasm](https://github.com/PaulieScanlon/remix-ffmpeg-wasm)

1. Run the app, hit the "load" button.
2. You'll see the following error in the terminal.

Not sure if this is a Remix thing, or an [ffmpeg/wasm](https://ffmpegwasm.netlify.app/) thing so apologies in advance if i'm barking up the wrong tree.

### System Info

```shell
System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1
    Memory: 78.77 MB / 8.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 21.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 119.0.6045.199
    Safari: 16.6
  npmPackages:
    @remix-run/dev: ^2.3.1 => 2.3.1
    @remix-run/eslint-config: ^2.3.1 => 2.3.1
    @remix-run/react: ^2.3.1 => 2.3.1
    @remix-run/serve: ^2.3.1 => 2.3.1
```

### Used Package Manager

npm

### Expected Behavior

The .wasm stuff should load.

### Actual Behavior

Error in terminal relating to: "No routes matched location "/build/routes/worker.js""

```
Error: No route matches URL "/build/routes/worker.js"
    at getInternalRouterError (/Users/paulscanlon/Documents/Paulie/Dev Tests/remix-ffmpeg-wasm/node_modules/@remix-run/router/router.ts:4377:5)
    at Object.query (/Users/paulscanlon/Documents/Paulie/Dev Tests/remix-ffmpeg-wasm/node_modules/@remix-run/router/router.ts:2856:19)
    at handleDocumentRequestRR (/Users/paulscanlon/Documents/Paulie/Dev Tests/remix-ffmpeg-wasm/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
    at requestHandler (/Users/paulscanlon/Documents/Paulie/Dev Tests/remix-ffmpeg-wasm/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
    at /Users/paulscanlon/Documents/Paulie/Dev Tests/remix-ffmpeg-wasm/node_modules/@remix-run/express/dist/server.js:42:28
No routes matched location "/build/routes/worker.js"
ErrorResponseImpl {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/build/routes/worker.js"',
  error: Error: No route matches URL "/build/routes/worker.js"
      at getInternalRouterError (/Users/paulscanlon/Documents/Paulie/Dev Tests/remix-ffmpeg-wasm/node_modules/@remix-run/router/router.ts:4377:5)
      at Object.query (/Users/paulscanlon/Documents/Paulie/Dev Tests/remix-ffmpeg-wasm/node_modules/@remix-run/router/router.ts:2856:19)
      at handleDocumentRequestRR (/Users/paulscanlon/Documents/Paulie/Dev Tests/remix-ffmpeg-wasm/node_modules/@remix-run/server-runtime/dist/server.js:168:35)
      at requestHandler (/Users/paulscanlon/Documents/Paulie/Dev Tests/remix-ffmpeg-wasm/node_modules/@remix-run/server-runtime/dist/server.js:93:24)
      at /Users/paulscanlon/Documents/Paulie/Dev Tests/remix-ffmpeg-wasm/node_modules/@remix-run/express/dist/server.js:42:28
}
```

**Comment by hi-ogawa** [comment]
I think this is because ffmpeg is hard-coding `new URL("./worker.js", import.meta.url)` and this ends up requesting to `/build/routes/worker.js` due to the way Remix bundles assets.

Probably it's hard to get that working as is on Remix, so either you have to patch things up, or if you can wait, then there's already a PR to allow customizing the worker url https://github.com/ffmpegwasm/ffmpeg.wasm/pull/639.

**Comment by PaulieScanlon** [comment]
Thank you for the info. I had a look at the PR. It seems like a relatively small change so fingers crossed it get merged in.

I can probably patch for now so I can carry on working but that's cool it's a known issue, with a suggested fix. I really wasn't sure where to start with this one.

**Comment by brophdawg11** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2. If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.

We plan to continue to address 2 types of issues in Remix v2:

- Bugs that pose security concerns
- Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so:

- If this is a bug, please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new [minimal reproduction](https://reactrouter.com/new) against v7
- If this is a feature request, please open a new [Proposal Discussion](https://github.com/remix-run/react-router/discussions/new?category=proposals) in React Router, and if it gets enough community support it can be considered for implementation

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
