### ISSUE TITLE
problems in setting up projects with MUI and internationalization

### ISSUE THREAD

**Issue by rahad06** [remix-run/remix#8268]
### Reproduction

https://github.com/rahad06/int-remix-mui/tree/tokyo

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13700H
    Memory: 1.86 GB / 15.62 GB
  Binaries:
    Node: 21.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.61)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Expected Behavior

a simple mui admin dashboard with multiple languages

### Actual Behavior

errors in using packages and peers

**Comment by rahad06** [comment]
Error

Cannot read properties of undefined (reading 'type')

The stack trace is:

TypeError: Cannot read properties of undefined (reading 'type')
    at decomposeColor (file:///C:/Users/R.Darabi/WebstormProjects/cst.core.remixpanel/build/index.js?t=1702371803174.4136:2092:14)
    at getLuminance (file:///C:/Users/R.Darabi/WebstormProjects/cst.core.remixpanel/build/index.js?t=1702371803174.4136:2133:12)
    at getContrastRatio (file:///C:/Users/R.Darabi/WebstormProjects/cst.core.remixpanel/build/index.js?t=1702371803174.4136:2138:14)
    at Object.getContrastText (file:///C:/Users/R.Darabi/WebstormProjects/cst.core.remixpanel/build/index.js?t=1702371803174.4136:2459:24)
    at file:///C:/Users/R.Darabi/WebstormProjects/cst.core.remixpanel/build/index.js?t=1702371803174.4136:167142:27
    at muiStyledFunctionResolver (file:///C:/Users/R.Darabi/WebstormProjects/cst.core.remixpanel/build/index.js?t=1702371803174.4136:2023:28)
    at transformedStyleArg (file:///C:/Users/R.Darabi/WebstormProjects/cst.core.remixpanel/build/index.js?t=1702371803174.4136:1943:83)
    at handleInterpolation (C:\Users\R.Darabi\WebstormProjects\cst.core.remixpanel\node_modules\@emotion\serialize\dist\emotion-serialize.cjs.dev.js:149:24)
    at Object.serializeStyles (C:\Users\R.Darabi\WebstormProjects\cst.core.remixpanel\node_modules\@emotion\serialize\dist\emotion-serialize.cjs.dev.js:263:15)
    at C:\Users\R.Darabi\WebstormProjects\cst.core.remixpanel\node_modules\@emotion\styled\base\dist\emotion-styled-base.cjs.dev.js:167:34

The error name is:
TypeError

The error cause is:

**Comment by brophdawg11** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2. If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.

We plan to continue to address 2 types of issues in Remix v2:

- Bugs that pose security concerns
- Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so:

- If this is a bug, please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new [minimal reproduction](https://reactrouter.com/new) against v7
- If this is a feature request, please open a new [Proposal Discussion](https://github.com/remix-run/react-router/discussions/new?category=proposals) in React Router, and if it gets enough community support it can be considered for implementation

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
