### ISSUE TITLE
zod validation error within loader function yields a source map loading error instead of the zod error

### ISSUE THREAD

**Issue by rhyek** [remix-run/remix#8404]
### Reproduction

simple reproduction here: https://github.com/rhyek/remix-zod-issue

run `npm run dev` and click on the remix serve url. you will immediately see the error in both the terminal and the opened browser tab:
```bash
```bash
Error: ENOENT: no such file or directory, open '/Users/carlos/Dev/test/remix-zod-issue/node_modules/zod/lib/index.mjs.map'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at Array.retrieveSourceMap (/Users/carlos/Dev/test/remix-zod-issue/node_modules/@remix-run/serve/dist/cli.js:50:37)
    at /Users/carlos/Dev/test/remix-zod-issue/node_modules/source-map-support/source-map-support.js:85:24
    at mapSourcePosition (/Users/carlos/Dev/test/remix-zod-issue/node_modules/source-map-support/source-map-support.js:216:21)
    at wrapCallSite (/Users/carlos/Dev/test/remix-zod-issue/node_modules/source-map-support/source-map-support.js:397:20)
    at Function.prepareStackTrace (/Users/carlos/Dev/test/remix-zod-issue/node_modules/source-map-support/source-map-support.js:446:39)
    at maybeOverridePrepareStackTrace (node:internal/errors:140:29)
    at prepareStackTrace (node:internal/errors:114:5)
    at getStackString (node:internal/util/inspect:1240:16)
```
```

### System Info

```shell
❯ npx envinfo --system --npmPackages '{vite,@remix-run/*}' --binaries --browsers

  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 9.32 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    pnpm: 8.13.1 - /opt/homebrew/bin/pnpm
    bun: 1.0.4 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.129
    Edge: 120.0.2210.91
    Safari: 17.2.1
  npmPackages:
    @remix-run/css-bundle: ^2.4.1 => 2.4.1 
    @remix-run/dev: ^2.4.1 => 2.4.1 
    @remix-run/node: ^2.4.1 => 2.4.1 
    @remix-run/react: ^2.4.1 => 2.4.1 
    @remix-run/serve: ^2.4.1 => 2.4.1
```

### Used Package Manager

npm

### Expected Behavior

when loading `/` i expect to see the stack trace and description for the zod error

### Actual Behavior

In both the browser and terminal I get the above stack trace about not being able to load a zod source map

**Comment by IgnisDa** [comment]
Might also be related to #8309.
