### ISSUE TITLE
Isomorphic-dompurify not working with Remix

### ISSUE THREAD

**Issue by joaoguidev** [remix-run/remix#8628]
### Reproduction

https://stackblitz.com/~/github.com/joaoguidev/RemixDompurify

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
    Memory: 4.35 GB / 15.67 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.83)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @remix-run/cloudflare: ^2.5.1 => 2.5.1
    @remix-run/cloudflare-pages: ^2.5.1 => 2.5.1
    @remix-run/css-bundle: ^2.5.1 => 2.5.1
    @remix-run/dev: ^2.5.1 => 2.5.1
    @remix-run/react: ^2.5.1 => 2.5.1
```

### Used Package Manager

npm

### Expected Behavior

Isomorphic-dompurify does not work with Remix because it seems Remix is trying to use the browser entry point from package.json on server.
This problem is listed as a Known Issue on the Isomorphic-dompurify repository and refer to the issues [#214](https://github.com/kkomelin/isomorphic-dompurify/issues/214)

### Actual Behavior

Not get the error below when using Isomorphic-dompurify :
`service core:user:worker: Uncaught ReferenceError: window is not defined
  at c77tsl6ez28.js:29540:22 in node_modules/isomorphic-dompurify/browser.js
  at c77tsl6ez28.js:82:50
  at c77tsl6ez28.js:30604:43`

**Comment by sergiodxa** [comment]
The error means the library is trying to use the browser version, probably because Cloudflare picks the browser one instead of the Node one, and since it's not Node this is correct.

If you check their browser build, they just require this other package https://www.npmjs.com/package/dompurify and try to find them from `window` first. They could just stop trying to find it globally in `window` and instead just use ESM, but if they don't want to fix this on their side you could skip them and import `dompurify` yourself.

**Comment by brophdawg11** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2. If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.

We plan to continue to address 2 types of issues in Remix v2:

- Bugs that pose security concerns
- Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so:

- If this is a bug, please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new [minimal reproduction](https://reactrouter.com/new) against v7
- If this is a feature request, please open a new [Proposal Discussion](https://github.com/remix-run/react-router/discussions/new?category=proposals) in React Router, and if it gets enough community support it can be considered for implementation

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
