### ISSUE TITLE
[Bug]: Expected server HTML to contain a matching <script> in <body>.

### ISSUE THREAD

**Issue by d3vhound** [remix-run/remix#866]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [X] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

14.17

### Steps to Reproduce

1. Start a new remix project
2. Select architect deployment target
3. Run npm run dev & arc sandbox
4. Sometimes the following error shows up in the console: 
```bash
react-dom.development.js:67 Warning: Expected server HTML to contain a matching <script> in <body>.
    at script
    at LiveReload (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:3422:3)
    at body
    at html
    at Document (http://localhost:3333/_static/build/root-5H2DJAZU.js:66:3)
    at App
    at RemixCatchBoundary (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:1476:10)
    at RemixErrorBoundary (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:1415:5)
    at RemixRoute (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:2905:3)
    at Routes (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:2888:7)
    at Router2 (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:457:21)
    at RemixCatchBoundary (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:1476:10)
    at RemixErrorBoundary (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:1415:5)
    at RemixEntry (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:2785:12)
    at RemixBrowser (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:3467:42)
```

### Expected Behavior

Clean console.

### Actual Behavior

Sometimes the following error shows up in the console after setting up a new remix-architect project: 
```bash
react-dom.development.js:67 Warning: Expected server HTML to contain a matching <script> in <body>.
    at script
    at LiveReload (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:3422:3)
    at body
    at html
    at Document (http://localhost:3333/_static/build/root-5H2DJAZU.js:66:3)
    at App
    at RemixCatchBoundary (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:1476:10)
    at RemixErrorBoundary (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:1415:5)
    at RemixRoute (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:2905:3)
    at Routes (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:2888:7)
    at Router2 (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:457:21)
    at RemixCatchBoundary (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:1476:10)
    at RemixErrorBoundary (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:1415:5)
    at RemixEntry (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:2785:12)
    at RemixBrowser (http://localhost:3333/_static/build/_shared/chunk-R5U63JRH.js:3467:42)
```

**Comment by macjabeth** [comment]
Removing the `preferences.arc` file in favour of `.env` fixed the issue:
```
NODE_ENV=development
```

**Comment by edgesoft** [comment]
@d3vhound This error in console can also happen if we have extension injecting html in the dom. Try open your app in incognito window to see if the error disappears.

**Comment by d3vhound** [comment]
@macjabeth that worked. Thanks guys.

**Comment by lpsinger** [comment]
> Removing the `preferences.arc` file in favour of `.env` fixed the issue:
> 
> ```
> NODE_ENV=development
> ```

I tried this workaround with Remix 1.1.1 and Node 16.13.2, and it did not work.

Should this be reopened anyway given that the `preferences.arc` file is still present in the architect template in create-remix?

**Comment by digioi** [comment]
I was able to get rid of the error by reading in the .env file as a environmental variables like 
```
// package.json
...
 "scripts":  {
    "start": "env $(cat .env | tr \"\\n\" \" \") arc sandbox"
```

**Comment by kamtugeza** [comment]
...and 2 more cents from me 🤠

For some reason, the `markup` variable in `app/entry.server.tsx` doesn't contain `<LiveReload />`. Looking at the [LiveReload](https://github.com/remix-run/remix/blob/6ba9269799d09fdc6804cf2d24f315dccaa9530c/packages/remix-react/components.tsx#L1397) declaration, the problem is in the environment variable `NODE_ENV`. 

Unfortunately, playing with that variable doesn't help me, so I've found a workaround (**for development only**) wrapping `<LiveReload />` by `<div>` that has the [suppressHydrationWarning](https://reactjs.org/docs/dom-elements.html#suppresshydrationwarning) attribute.

P.S. I'm not sure should we reopen this issue or leave it as it is 🤓
