### ISSUE TITLE
File convention *.client.ts[x] generating GET / 500 error.

### ISSUE THREAD

**Issue by jklarenbeek** [remix-run/remix#8691]
### Reproduction

Create a new remix project. I assume that the latest `2.6.0` remix version will be installed.

(if on windows don't initialize a git repository, because it will break the setup procedure)

```
npx create-remix@latest
```

Open the `tsconfig.json` file and add the following compiler option to allow for dynamic imports:

```json
{
  "compilerOptions": {
    "module": "ES2022"
  }
}
```

Create a folder `components` in the app directory and then a file called `hello-world.client.tsx` in that new folder with the following contents.

```tsx

export default function Hello() {
  const rnd = 42; //Math.random();
  return <h1>Hello World {rnd}</h1>;
}

```

Now open the existing file `_index.tsx` in your routes folder and change it like this:

```tsx
import type { MetaFunction } from "@remix-run/node";
import { Suspense, lazy } from "react";
import Hello from "~/components/hello-world.client";

export const meta: MetaFunction = () => {
  return [
    { title: "New Remix App" },
    { name: "description", content: "Welcome to Remix!" },
  ];
};

export default function Index() {
  const MyHello = lazy(() => import("~/components/hello-world.client"));
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.8" }}>
      <h1>Client Bug</h1>
      <Suspense fallback={<div>Loading</div>}>
        <MyHello />
      </Suspense>
    </div>
  );
}

```

Start the dev server with `npm run dev` and browse to the url stated by the `remix-serve` output. (in my case `http://localhost:3000`. This will produce the following error:

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at renderElement (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\react-dom\cjs\react-dom-server.node.development.js:6109:9)
    at renderLazyComponent (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\react-dom\cjs\react-dom-server.node.development.js:6002:3)
    at renderElement (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\react-dom\cjs\react-dom-server.node.development.js:6095:11)
    at renderNodeDestructiveImpl (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)     
    at renderNodeDestructive (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at retryTask (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\react-dom\cjs\react-dom-server.node.development.js:6594:5)
    at performWork (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\react-dom\cjs\react-dom-server.node.development.js:6642:7)
    at Immediate._onImmediate (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\react-dom\cjs\react-dom-server.node.development.js:5448:14)        
    at processImmediate (node:internal/timers:478:21)
GET / 200 - - 19.343 ms
```

When changing `<MyHello />` for `<Hello />` on line 18, the error changes like this:

```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at _index.tsx:18.
    at Index
    at RenderedRoute (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\react-router\dist\umd\react-router.development.js:520:7)
    at Outlet (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\react-router\dist\umd\react-router.development.js:1123:28)
    at body
    at html
    at App
    at RenderedRoute (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\react-router\dist\umd\react-router.development.js:520:7)
    at RenderErrorBoundary (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\react-router\dist\umd\react-router.development.js:467:7)
    at DataRoutes (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\react-router-dom\server.js:130:3)
    at Router (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\react-router\dist\umd\react-router.development.js:1144:17)
    at StaticRouterProvider (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\react-router-dom\server.js:67:3)
    at RemixErrorBoundary (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\@remix-run\react\dist\errorBoundaries.js:40:5)
    at RemixServer (C:\Users\rapidsource\Projects\remix-bug\client-bug\node_modules\@remix-run\react\dist\server.js:47:3)
GET / 500 - - 28.693 ms
```

When changing `hello-world.client.tsx` to `hello-world.tsx` everything works fine in both cases and no error is generated on the server.

**Note that <ins>the client side is rendered correctly</ins> and that in both cases the error is generated on the server.** 

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 3.55 GB / 15.91 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.61)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @remix-run/css-bundle: ^2.6.0 => 2.6.0
    @remix-run/dev: ^2.6.0 => 2.6.0
    @remix-run/node: ^2.6.0 => 2.6.0
    @remix-run/react: ^2.6.0 => 2.6.0
    @remix-run/serve: ^2.6.0 => 2.6.0
```

### Used Package Manager

npm

### Expected Behavior

Should not render `hello-world.client.tsx` on the server, but instead only in the browser.
Should output better error messaging.
Should include the compileroptions: module: "ES2022" by default.
Should allow for using the canary version of react within the package.json of remix (i.e. `npx create-remix@canary`

### Actual Behavior

website keeps on running, but a server side 500 error is generated.

**Comment by joevingracien** [comment]
I was facing just that yesterday.

The solution is below (quoted from sergiodxa in discord )
"you need to combine the .client.tsx file to avoid the file being included in the server bundle, and ClientOnly to avoid trying to render it server-side" 

ClientOnly is from the remix-utils library.

**Comment by jklarenbeek** [comment]
Yes, I read that thread too.

However, if you look into the `package.json` file of the `remix-utils` lib, you will see that it uses remix version `2.0.0` and react version `18.0.0` instead of remix version `2.6.0` and react version `18.2.0`. I'm to much of an autistic nerd to feel comfortable with that (especially if you are aware of the problems in react 18.0.0, i guess a lot of side effect would disapear if remix would go with the react canary release like nextjs does). 

I also read somewhere else that remix-utils is not working for the latest remix package (but that could be already an outdated comment).

But besides that, it is kind of strange and in contradiction with the docs that the file is included in the server bundle. That said, it also clearly states that it is meant for `*.client.ts` instead of `*.client.ts[x]`.

Anyways, this seems like a really important feature that remix should have included in its core features.

I'll give it a shot and try remix-utils and see what happens with the latest remix-run package.

**Comment by jklarenbeek** [comment]
@joevingracien I now realize I didn't read that thread at all :S but thanks for the link to your own repo showing an example.

**Comment by kiliman** [comment]
@jklarenbeek Those are semantic version ranges. The `^` means include all _minor_ versions.

So `^18.0.0` means compatible with all `18.x` versions. Same with Remix. When you install the package, it will automatically install the latest version that meets that criteria if the dependency is not already installed.

If you remove the `^`, then you are _pinning_ to that specific version.

https://docs.npmjs.com/about-semantic-versioning

**Comment by brophdawg11** [comment]
Can this issue be closed via the solution provided above?

> you need to combine the .client.tsx file to avoid the file being included in the server bundle, and ClientOnly to avoid trying to render it server-side

**Comment by empz** [comment]
I don't get why Remix needs an external library utility to support such a basic use case of rendering a client component inside a route/server component. This should be natively supported!
