### ISSUE TITLE
TypeError: getPlatformProxy is not a function

### ISSUE THREAD

**Issue by aaronadamsCA** [remix-run/remix#8811]
### Reproduction

If you migrate Cloudflare Pages to Vite, but do not upgrade Wrangler to latest, Remix startup fails with `getPlatformProxy is not a function`.

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Memory: 10.69 GB / 15.61 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.11.0 - /usr/local/share/nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.2.4 - /usr/local/share/nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.1 - /usr/local/share/nvm/versions/node/v20.11.0/bin/pnpm
  npmPackages:
    @remix-run/cloudflare: 2.7.0 => 2.7.0 
    @remix-run/cloudflare-pages: 2.7.0 => 2.7.0 
    @remix-run/dev: 2.7.0 => 2.7.0 
    @remix-run/react: 2.7.0 => 2.7.0 
    @remix-run/server-runtime: 2.7.0 => 2.7.0 
    @remix-run/testing: 2.7.0 => 2.7.0 
    vite: 5.0.12 => 5.0.12 
```

### Used Package Manager

pnpm

### Expected Behavior

- Probably something in the docs and/or the changelog that you need to upgrade Wrangler.
- Hopefully a friendlier error message if the import fails, like "Did you remember to upgrade Wrangler?"

### Actual Behavior

A stack trace!

```
> remix vite:dev

TypeError: getPlatformProxy is not a function
    at configureServer (/workspaces/web-apps/node_modules/.pnpm/@remix-run+dev@2.7.0_typescript@5.3.3_vite@5.0.12_wrangler@3.26.0/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:55:17)
    at async _createServer (file:///workspaces/web-apps/node_modules/.pnpm/vite@5.0.12/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:60589:24)
    at async configResolved (/workspaces/web-apps/node_modules/.pnpm/@remix-run+dev@2.7.0_typescript@5.3.3_vite@5.0.12_wrangler@3.26.0/node_modules/@remix-run/dev/dist/vite/plugin.js:645:27)
    at async Promise.all (index 1)
    at async resolveConfig (file:///workspaces/web-apps/node_modules/.pnpm/vite@5.0.12/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:68124:5)
    at async _createServer (file:///workspaces/web-apps/node_modules/.pnpm/vite@5.0.12/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:60327:20)
    at async dev (/workspaces/web-apps/node_modules/.pnpm/@remix-run+dev@2.7.0_typescript@5.3.3_vite@5.0.12_wrangler@3.26.0/node_modules/@remix-run/dev/dist/vite/dev.js:39:16)
    at async Object.viteDev (/workspaces/web-apps/node_modules/.pnpm/@remix-run+dev@2.7.0_typescript@5.3.3_vite@5.0.12_wrangler@3.26.0/node_modules/@remix-run/dev/dist/cli/commands.js:213:3)
    at async Object.run (/workspaces/web-apps/node_modules/.pnpm/@remix-run+dev@2.7.0_typescript@5.3.3_vite@5.0.12_wrangler@3.26.0/node_modules/@remix-run/dev/dist/cli/run.js:226:7)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by aaronadamsCA** [comment]
I somehow managed to edit this out of my original post:

`getPlatformProxy` was added to Wrangler just [7 days ago](https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.28.2), so it's likely most people trying this migration for the first time would still be on a Wrangler version that doesn't have it.

**Comment by pcattori** [comment]
Closing as [Wrangler v3.28.2 or newer is already listed as a peer dependency of `@remix-run/dev`](https://github.com/remix-run/remix/blob/main/packages/remix-dev/package.json#L101)
