### ISSUE TITLE
Errors with the `vite-cloudflare` template on fresh install

### ISSUE THREAD

**Issue by rista404** [remix-run/remix#8812]
### Reproduction

Following the docs for creating a new vite cloudflare template and running `npm run dev` or `npm run build` throws a timeout error.

```sh
npx create-remix@latest --template remix-run/remix/templates/vite-cloudflare
# ...

npm run dev

> dev
> remix vite:dev

TypeError: fetch failed
    at fetch (/.../remix-cf-vite-test/node_modules/wrangler/wrangler-dist/cli.js:17033:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getRegisteredWorkers (/.../remix-cf-vite-test/node_modules/wrangler/wrangler-dist/cli.js:127178:22)
    at async getBoundRegisteredWorkers (/.../remix-cf-vite-test/node_modules/wrangler/wrangler-dist/cli.js:127197:29)
    at async getMiniflareOptionsFromConfig (/.../remix-cf-vite-test/node_modules/wrangler/wrangler-dist/cli.js:169370:29)
    at async getPlatformProxy (/.../remix-cf-vite-test/node_modules/wrangler/wrangler-dist/cli.js:169342:28)
    at async configureServer (/.../remix-cf-vite-test/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:55:11)
    at async _createServer (file:///.../remix-cf-vite-test/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:64518:24)
    at async configResolved (/.../remix-cf-vite-test/node_modules/@remix-run/dev/dist/vite/plugin.js:645:27)
    at async Promise.all (index 2) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (/.../remix-cf-vite-test/node_modules/wrangler/wrangler-dist/cli.js:5865:29)
      at /.../remix-cf-vite-test/node_modules/wrangler/wrangler-dist/cli.js:5821:51
      at Immediate._onImmediate (/.../remix-cf-vite-test/node_modules/wrangler/wrangler-dist/cli.js:5853:13)
      at process.processImmediate (node:internal/timers:478:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
```

Should be pretty easy to reproduce as I haven't changed anything in the template. Let me know if I can help in any other way!

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M2 Pro
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 21.5.0 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
  npmPackages:
    @remix-run/cloudflare: ^2.7.0 => 2.7.0
    @remix-run/cloudflare-pages: ^2.7.0 => 2.7.0
    @remix-run/dev: ^2.7.0 => 2.7.0
    @remix-run/react: ^2.7.0 => 2.7.0
    vite: ^5.1.0 => 5.1.3
    wrangler: 3.28.4
```

### Used Package Manager

npm

### Expected Behavior

Throws a wrangler-related  timeout  error. Added wrangler version to the system info.

### Actual Behavior

Runs the dev server.

**Comment by pcattori** [comment]
Related: https://github.com/cloudflare/workers-sdk/issues/1920
