### ISSUE TITLE
[2.7.0] Importing CSS URL breaks Vite server build on Windows

### ISSUE THREAD

**Issue by wKovacs64** [remix-run/remix#8814]
### Reproduction

Something broke Vite server builds on Windows if you're importing CSS URLs in `@remix-run/dev@2.7.0-pre.2` which carried through to 2.7.0 stable (it's fine in `@remix-run/dev@2.7.0-pre.1`). Tested and confirmed in a couple projects. Build works fine on Linux/macOS.

### System Info

```shell
Binaries:
  Node: 20.11.0 - ~\AppData\Local\nvs\default\node.EXE
  npm: 10.2.4 - ~\AppData\Local\nvs\default\npm.CMD
npmPackages:
  @remix-run/dev: ^2.7.0 => 2.7.0 
  @remix-run/node: ^2.7.0 => 2.7.0 
  @remix-run/react: ^2.7.0 => 2.7.0 
  @remix-run/serve: ^2.7.0 => 2.7.0 
  vite: ^5.1.0 => 5.1.3
```

### Used Package Manager

npm

### Expected Behavior

**2.7.0-pre.1**

```sh
vite v5.1.3 building for production...
✓ 82 modules transformed.
build/client/.vite/manifest.json                1.15 kB │ gzip:  0.35 kB
build/client/assets/app-CTx_A4Po.css            0.02 kB │ gzip:  0.04 kB
build/client/assets/_index-D_UUquDl.js          0.76 kB │ gzip:  0.39 kB
build/client/assets/root-jNyQ5NZw.js            1.53 kB │ gzip:  0.90 kB
build/client/assets/jsx-runtime-BlSqMCxk.js     8.09 kB │ gzip:  3.04 kB
build/client/assets/entry.client-DOhoKWHe.js   14.21 kB │ gzip:  4.94 kB
build/client/assets/components-CPc-b90R.js    212.68 kB │ gzip: 68.81 kB
✓ built in 954ms
vite v5.1.3 building SSR bundle for production...
✓ 7 modules transformed.
build/server/.vite/manifest.json      0.29 kB
build/server/assets/app-CTx_A4Po.css  0.02 kB
build/server/index.js                 7.37 kB
✓ built in 38ms
```

### Actual Behavior

**2.7.0-pre.2 (through 2.7.0)**

```sh
vite v5.1.3 building for production...
✓ 82 modules transformed.
build/client/.vite/manifest.json                1.15 kB │ gzip:  0.35 kB
build/client/assets/app-CTx_A4Po.css            0.02 kB │ gzip:  0.04 kB
build/client/assets/_index-D_UUquDl.js          0.76 kB │ gzip:  0.39 kB
build/client/assets/root-DLKVUbjd.js            1.53 kB │ gzip:  0.89 kB
build/client/assets/jsx-runtime-BlSqMCxk.js     8.09 kB │ gzip:  3.04 kB
build/client/assets/entry.client-5hEbCVyn.js   14.18 kB │ gzip:  4.94 kB
build/client/assets/components-BGQcvoVf.js    212.63 kB │ gzip: 68.80 kB
✓ built in 963ms
vite v5.1.3 building SSR bundle for production...
✓ 7 modules transformed.
build/server/.vite/manifest.json      0.29 kB
build/server/assets/app-CTx_A4Po.css  0.02 kB
build/server/index.js                 7.37 kB
x Build failed in 46ms
Error: [remix] dest already exists.
    at C:\dev\test\remix-2.7.0-vite\node_modules\fs-extra\lib\move\move.js:51:31
    at C:\dev\test\remix-2.7.0-vite\node_modules\universalify\index.js:21:38 {
  code: 'PLUGIN_ERROR',
  plugin: 'remix',
  hook: 'writeBundle'
}
```

**Comment by wKovacs64** [comment]
You beat me, @danestves!

**Comment by wKovacs64** [comment]
Closing as a duplicate of #8813
