### ISSUE TITLE
cannot start remix server on Mac

### ISSUE THREAD

**Issue by pullmann4rent** [remix-run/remix#8835]
### Reproduction

Hello,

I have a remix server on windows its started and works but on Mac I got this error:

```
Require stack:
- /Users/scr/Desktop/renting24/test_vercel/node_modules/@remix-run/serve/dist/index.js
- /Users/scr/Desktop/renting24/test_vercel/node_modules/@remix-run/dev/dist/devServer/serve.js
- /Users/scr/Desktop/renting24/test_vercel/node_modules/@remix-run/dev/dist/cli/commands.js
- /Users/scr/Desktop/renting24/test_vercel/node_modules/@remix-run/dev/dist/cli/run.js
- /Users/scr/Desktop/renting24/test_vercel/node_modules/@remix-run/dev/dist/cli/index.js
- /Users/scr/Desktop/renting24/test_vercel/node_modules/@remix-run/dev/dist/index.js
- /Users/scr/Desktop/renting24/test_vercel/node_modules/@remix-run/dev/dist/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function.Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at /Users/scr/Desktop/renting24/test_vercel/node_modules/@remix-run/serve/dist/index.js:43:17
    at Layer.handle [as handle_request] (/Users/scr/Desktop/renting24/test_vercel/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/scr/Desktop/renting24/test_vercel/node_modules/express/lib/router/route.js:144:13)
    at next (/Users/scr/Desktop/renting24/test_vercel/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/scr/Desktop/renting24/test_vercel/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/scr/Desktop/renting24/test_vercel/node_modules/express/lib/router/route.js:140:7)
```

### System Info

```shell
System:
    OS: macOS 14.2
    CPU: (8) arm64 Apple M3
    Memory: 155.11 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - /usr/local/bin/node
    npm: 10.4.0 - /usr/local/bin/npm
  Browsers:
    Safari: 17.2
```

### Used Package Manager

npm

### Expected Behavior

package.json

```
{
  "private": true,
  "sideEffects": false,
  "scripts": {
    "build": "remix build",
    "dev": "remix dev",
    "typecheck": "tsc"
  },
  "dependencies": {
    "@fullcalendar/core": "^6.1.6",
    "@fullcalendar/resource": "^6.1.6",
    "@fullcalendar/resource-timeline": "^6.1.6",
    "@mantine/core": "^7.1.2",
    "@mantine/dates": "^7.1.2",
    "@mantine/hooks": "^7.1.2",
    "@natscale/react-calendar": "^0.0.0-beta.26",
    "@paypal/react-paypal-js": "^7.8.3",
    "@react-pdf/renderer": "^3.1.14",
    "@react-spring/web": "^9.7.3",
    "@remix-run/css-bundle": "^2.0.1",
    "@remix-run/express": "^1.15.0",
    "@remix-run/node": "^1.15.0",
    "@remix-run/react": "^1.15.0",
    "@remix-run/vercel": "^1.15.0",
    "@remix-validated-form/with-yup": "^2.0.3",
    "@remix-validated-form/with-zod": "^2.0.7",
    "@stripe/react-stripe-js": "^2.1.0",
    "@stripe/stripe-js": "^1.52.1",
    "@vercel/node": "^2.10.3",
    "@vercel/remix": "^1.15.0",
    "compression": "^1.7.4",
    "cross-env": "^7.0.3",
    "dayjs": "^1.11.7",
    "express": "^4.18.2",
    "hamburger-react": "^2.5.0",
    "isbot": "^3.6.8",
    "mailgun.js": "^10.2.1",
    "mailtrap": "^3.3.0",
    "morgan": "^1.10.0",
    "nodemailer": "^6.9.9",
    "react": "^18.2.0",
    "react-calendar": "^4.2.1",
    "react-calendar-datetime-picker": "^1.6.3",
    "react-dom": "^18.2.0",
    "react-faq-component": "^1.3.4",
    "react-icons": "^5.0.1",
    "react-onclickoutside": "^6.13.0",
    "react-pdf": "^7.5.1",
    "react-rainbow-components": "^1.3.1",
    "react-slick": "^0.29.0",
    "react-spinners": "^0.13.8",
    "remix-utils": "^6.6.0",
    "remix-validated-form": "^4.6.11",
    "spinners-react": "^1.0.7",
    "stripe": "^12.1.1",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.15.0",
    "@remix-run/eslint-config": "^1.15.0",
    "@remix-run/serve": "^1.15.0",
    "@types/lodash": "^4.14.194",
    "@types/nodemailer": "^6.4.14",
    "@types/react": "^18.0.35",
    "@types/react-dom": "^18.0.11",
    "@types/react-slick": "^0.23.10",
    "dotenv": "^16.0.3",
    "eslint": "^8.38.0",
    "eslint-plugin-you-dont-need-lodash-underscore": "^6.12.0",
    "lodash": "^4.17.21",
    "nodemon": "^2.0.20",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.4.31",
    "postcss-preset-mantine": "^1.8.0",
    "postcss-simple-vars": "^7.0.1",
    "typescript": "^4.9.5"
  },
  "engines": {
    "node": ">=14"
  }
}

```

### Actual Behavior

what I am doing wrong on Mac ?

**Comment by brophdawg11** [comment]
Can you provide a reproduction repository?
