### ISSUE TITLE
In SPA mode, adding @aspida/axios causes build errors

### ISSUE THREAD

**Issue by kokuyouwind** [remix-run/remix#8940]
### Reproduction

1. Initialize SPA Remix App with `npx create-remix@latest --template remix-run/remix/templates/spa`
2. Install https://github.com/aspida/aspida with `$ npm install aspida @aspida/axios axios`
3. `import aspida from "@aspida/axios";` and refer `aspida` in somewhere

Then, `npm run build` fails with `SyntaxError: Cannot use import statement outside a module`

<details><summary>Build Log</summary>

```
❯ npm run build

> build
> remix vite:build

vite v5.1.4 building for production...
✓ 127 modules transformed.
build/client/.vite/manifest.json                0.90 kB │ gzip:  0.26 kB
build/client/assets/root-Bk8PTQwa.js            1.51 kB │ gzip:  0.87 kB
build/client/assets/jsx-runtime-BlSqMCxk.js     8.09 kB │ gzip:  3.04 kB
build/client/assets/entry.client-BJ12z_Rq.js   14.04 kB │ gzip:  5.00 kB
build/client/assets/_index-BUOPZt3W.js         32.01 kB │ gzip: 12.82 kB
build/client/assets/components-t0vHlsCC.js    212.81 kB │ gzip: 68.85 kB
✓ built in 474ms
vite v5.1.4 building SSR bundle for production...
✓ 5 modules transformed.
build/server/.vite/manifest.json  0.13 kB
build/server/index.js             4.43 kB
(node:6057) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
x Build failed in 31ms
/Users/kokuyouwind/tmp/remix-esm-test/node_modules/@aspida/axios/dist/esm/index.js:1
import { dataToURLString, optionToRequest, } from 'aspida';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1290:20)
    at Module._compile (node:internal/modules/cjs/loader:1342:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at cjsLoader (node:internal/modules/esm/translators:359:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:308:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24) {
  code: 'PLUGIN_ERROR',
  plugin: 'remix',
  hook: 'writeBundle'
```

</details>

Note that if SSR is enabled with `remix({ ssr: true }`, the build will complete without problems.

<details><summary>Build Log</summary>

```
❯ npm run build

> build
> remix vite:build

vite v5.1.4 building for production...
✓ 127 modules transformed.
build/client/.vite/manifest.json                0.90 kB │ gzip:  0.26 kB
build/client/assets/root-Bk8PTQwa.js            1.51 kB │ gzip:  0.87 kB
build/client/assets/jsx-runtime-BlSqMCxk.js     8.09 kB │ gzip:  3.04 kB
build/client/assets/entry.client-BJ12z_Rq.js   14.04 kB │ gzip:  5.00 kB
build/client/assets/_index-BUOPZt3W.js         32.01 kB │ gzip: 12.82 kB
build/client/assets/components-t0vHlsCC.js    212.81 kB │ gzip: 68.85 kB
✓ built in 483ms
vite v5.1.4 building SSR bundle for production...
✓ 5 modules transformed.
build/server/.vite/manifest.json  0.13 kB
build/server/index.js             4.43 kB
✓ built in 11ms
```

</details>

The complete reproduction code can be found at https://github.com/kokuyouwind/remix-spa-aspida.

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 226.38 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.2 - ~/.asdf/installs/nodejs/21.6.2/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
    bun: 1.0.3 - ~/.asdf/shims/bun
  Browsers:
    Chrome: 122.0.6261.69
    Safari: 17.2.1
  npmPackages:
    @remix-run/dev: ^2.8.0 => 2.8.0
    @remix-run/node: ^2.8.0 => 2.8.0
    @remix-run/react: ^2.8.0 => 2.8.0
    vite: ^5.1.0 => 5.1.4
```

### Used Package Manager

npm

### Expected Behavior

Build complete successfully.

### Actual Behavior

Build failed.

**Comment by kokuyouwind** [comment]
I thought ESM Modules might be the cause, but `@sindresorhus/slugify`, which only provides ESM packages, does not seem to have the problem.
Also, specifying `["@aspida/axios"]` or `"all"` in `serverDependenciesToBundle` did not solve the problem.

**Comment by kokuyouwind** [comment]
In `@aspida/axios`, instead of specifying the file path directly in `exports` in package.json, an object with the file path is set for each `import` and `require`.
Perhaps this is related to the problem.

```
❯ cat node_modules/@aspida/axios/package.json
{
  "name": "@aspida/axios",
  "version": "1.14.0",
  "description": "axios client for aspida",
  "author": "Solufa <solufa2020@gmail.com>",
  "license": "MIT",
  "main": "./dist/cjs/index.js",
  "module": "./dist/esm/index.js",
  "exports": {
    ".": {
      "require": "./dist/cjs/index.js",
      "import": "./dist/esm/index.js",
      "types": "./dist/esm/index.d.ts"
    },
    "./package.json": "./package.json"
  },
  // ...
```

For reference, @sindresorhus/slugify specifies the file path directly.

```
❯ cat node_modules/@sindresorhus/slugify/package.json
{
	"name": "@sindresorhus/slugify",
	"version": "2.2.1",
	"description": "Slugify a string",
	"license": "MIT",
	"repository": "sindresorhus/slugify",
	"funding": "https://github.com/sponsors/sindresorhus",
	"author": {
		"name": "Sindre Sorhus",
		"email": "sindresorhus@gmail.com",
		"url": "https://sindresorhus.com"
	},
	"type": "module",
	"exports": "./index.js",
        // ...
```

**Comment by brophdawg11** [comment]
With vite, `serverDependenciesToBundle` is no longer used since vite has it's own `ssr.noExternal` config that you can use.  We're updating this to be enabled for all server deps out of the box in the template in https://github.com/remix-run/remix/pull/8928 but you can also take a more streamlined approach:

```js
export default defineConfig({
  ssr: {
    noExternal: ["aspida", "@aspida/axios"],
  },
  plugins: [remix({ ssr: false }), tsconfigPaths()],
});
```

**Comment by kokuyouwind** [comment]
@brophdawg11 

Thanks for the response!
I had not found the `noExternal` option. I did the suggested `noExternal: ["aspida", "@aspida/axios"]` and the build was successful.

---

On the other hand, `noExternal: true` seems to cause other problems.
When I run `npx create-remix@latest --template remix-run/remix/templates/spa` with the current code and then `npm run build`, I get the following error.

<details><summary>Build Log</summary>

```
❯ npm run build

> build
> remix vite:build

vite v5.1.4 building for production...
✓ 80 modules transformed.
build/client/.vite/manifest.json                0.90 kB │ gzip:  0.26 kB
build/client/assets/_index-sQQQDCbE.js          0.62 kB │ gzip:  0.36 kB
build/client/assets/root-Bk8PTQwa.js            1.51 kB │ gzip:  0.87 kB
build/client/assets/jsx-runtime-BlSqMCxk.js     8.09 kB │ gzip:  3.04 kB
build/client/assets/entry.client-BJ12z_Rq.js   14.04 kB │ gzip:  5.00 kB
build/client/assets/components-t0vHlsCC.js    212.81 kB │ gzip: 68.85 kB
✓ built in 431ms
vite v5.1.4 building SSR bundle for production...
✓ 6 modules transformed.
x Build failed in 20ms
Error [RollupError]: [commonjs--resolver] Cannot bundle Node.js built-in "stream" imported from "node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js". Consider disabling ssr.noExternal or remove the built-in dependency.
file: /Users/kokuyou/tmp/remix-spa-test-2/node_modules/react-dom/server.node.js
    at getRollupEror (file:///Users/kokuyou/tmp/remix-spa-test-2/node_modules/rollup/dist/es/shared/parseAst.js:375:41)
    at error (file:///Users/kokuyou/tmp/remix-spa-test-2/node_modules/rollup/dist/es/shared/parseAst.js:372:42)
    at Object.error (file:///Users/kokuyou/tmp/remix-spa-test-2/node_modules/rollup/dist/es/shared/node-entry.js:19394:20)
    at Object.resolveId (file:///Users/kokuyou/tmp/remix-spa-test-2/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:47584:34)
    at Object.handler (file:///Users/kokuyou/tmp/remix-spa-test-2/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:67142:19)
    at file:///Users/kokuyou/tmp/remix-spa-test-2/node_modules/rollup/dist/es/shared/node-entry.js:19579:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/kokuyou/tmp/remix-spa-test-2/node_modules/rollup/dist/es/shared/node-entry.js:19479:28)
    at async resolveId (file:///Users/kokuyou/tmp/remix-spa-test-2/node_modules/rollup/dist/es/shared/node-entry.js:18149:26)
    at async ModuleLoader.resolveId (file:///Users/kokuyou/tmp/remix-spa-test-2/node_modules/rollup/dist/es/shared/node-entry.js:18563:15)
    at async file:///Users/kokuyou/tmp/remix-spa-test-2/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:8368:16 {
  code: 'PLUGIN_ERROR',
  plugin: 'commonjs--resolver',
  hook: 'resolveId',
  id: '/Users/kokuyou/tmp/remix-spa-test-2/node_modules/react-dom/server.node.js',
  watchFiles: [
    '/Users/kokuyou/tmp/remix-spa-test-2/app/routes/_index.tsx',
    '/Users/kokuyou/tmp/remix-spa-test-2/app/root.tsx',
    '/Users/kokuyou/tmp/remix-spa-test-2/app/entry.server.tsx',
    '/Users/kokuyou/tmp/remix-spa-test-2/node_modules/react/jsx-runtime.js',
    '/Users/kokuyou/tmp/remix-spa-test-2/node_modules/@remix-run/react/dist/esm/index.js',
    '/Users/kokuyou/tmp/remix-spa-test-2/node_modules/react-dom/server.node.js',
    '/Users/kokuyou/tmp/remix-spa-test-2/node_modules/react/cjs/react-jsx-runtime.production.min.js',
    '/Users/kokuyou/tmp/remix-spa-test-2/node_modules/react/cjs/react-jsx-runtime.development.js',
    '/Users/kokuyou/tmp/remix-spa-test-2/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js'
  ]
}
```

</details>

I think it would be a good idea to set the default value in the template to `noExternal: []` and add a comment to make it easier to add packages when needed.

**Comment by brophdawg11** [comment]
Yeah we found that `true` was a bit too much and reverted that in <https://github.com/remix-run/remix/pull/8952>.  We'll probably just look to update the docs a bit to point to those options and let users decide how they want to configure their vite setup 👍
