### ISSUE TITLE
Using regular CSS throws '[vite] Internal server error: URI malformed'

### ISSUE THREAD

**Issue by amanape** [remix-run/remix#8980]
### Reproduction

Go to https://stackblitz.com/edit/remix-run-remix-xjpfmw?file=app%2Froot.tsx and look at the terminal logs. Refresh if you don't see anything at first.

```shell
00:03:20 [vite] Internal server error: URI malformed
      at decodeURI (<anonymous>)
      at viteTransformMiddleware (file:///home/projects/remix-run-remix-xjpfmw/node_modules/vite/dist/node/chunks/dep-G-px366b.js:63401:19)
      at call (file:///home/projects/remix-run-remix-xjpfmw/node_modules/vite/dist/node/chunks/dep-G-px366b.js:42732:7)
      at next (file:///home/projects/remix-run-remix-xjpfmw/node_modules/vite/dist/node/chunks/dep-G-px366b.js:42676:5)
      at viteServePublicMiddleware (file:///home/projects/remix-run-remix-xjpfmw/node_modules/vite/dist/node/chunks/dep-G-px366b.js:53353:20)
      at call (file:///home/projects/remix-run-remix-xjpfmw/node_modules/vite/dist/node/chunks/dep-G-px366b.js:42732:7)
      at next (file:///home/projects/remix-run-remix-xjpfmw/node_modules/vite/dist/node/chunks/dep-G-px366b.js:42676:5)
      at viteHMRPingMiddleware (file:///home/projects/remix-run-remix-xjpfmw/node_modules/vite/dist/node/chunks/dep-G-px366b.js:64662:13)
      at call (file:///home/projects/remix-run-remix-xjpfmw/node_modules/vite/dist/node/chunks/dep-G-px366b.js:42732:7)
      at next (file:///home/projects/remix-run-remix-xjpfmw/node_modules/vite/dist/node/chunks/dep-G-px366b.js:42676:5)
```

Curiously, the browser console throws:
```
GET http://localhost:5173/*%20http://meyerweb.com/eric/tools/css/reset/%20%20%20%20v2.0%20%7C%2020110126%20%20%20License:%20none%20(public%20domain)*/html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,menu,nav,output,ruby,section,summary,time,mark,audio,video%20%7B%20%20margin:%200;%20%20padding:%200;%20%20border:%200;%20%20font-size:%20100%;%20%20font:%20inherit;%20%20vertical-align:%20baseline;%7D/*%20HTML5%20display-role%20reset%20for%20older%20browsers%20*/article,aside,details,figcaption,figure,footer,header,hgroup,menu,nav,section%20%7B%20%20display:%20block;%7Dbody%20%7B%20%20line-height:%201;%7Dol,ul%20%7B%20%20list-style:%20none;%7Dblockquote,q%20%7B%20%20quotes:%20none;%7Dblockquote:before,blockquote:after,q:before,q:after%20%7B%20%20content:%20'';%20%20content:%20none;%7Dtable%20%7B%20%20border-collapse:%20collapse;%20%20border-spacing:%200;%7D net::ERR_ABORTED 500 (Internal Server Error)

root.tsx:3 Uncaught SyntaxError: The requested module '/app/styles/global.css?t=1709650640317' does not provide an export named 'default' (at root.tsx:3:3)
```

### System Info

StackBlitz `envinfo`:
```shell
System:
    OS: Linux 5.0 undefined
    CPU: (2) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: * => 2.8.0 
    @remix-run/node: * => 2.8.0 
    @remix-run/react: * => 2.8.0 
    @remix-run/serve: * => 2.8.0 
    vite: ^5.1.0 => 5.1.5 
```

Local `envinfo`:
```shell
 System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 116.03 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 1.22.21 - ~/.yarn/bin/yarn
    npm: 10.3.0 - /opt/homebrew/bin/npm
    pnpm: 8.15.1 - /opt/homebrew/bin/pnpm
    bun: 1.0.29 - ~/.bun/bin/bun
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 120.1.61.109
    Safari: 17.2.1
  npmPackages:
    @remix-run/dev: ^2.8.0 => 2.8.0 
    @remix-run/node: ^2.8.0 => 2.8.0 
    @remix-run/react: ^2.8.0 => 2.8.0 
    @remix-run/serve: ^2.8.0 => 2.8.0 
    @remix-run/testing: ^2.8.0 => 2.8.0 
    vite: ^5.1.0 => 5.1.5 
```

### Used Package Manager

npm

### Expected Behavior

No URI malformed error thrown when using CSS stylesheets

### Actual Behavior

URI malformed error thrown when using CSS stylesheets

**Comment by amanape** [comment]
Interestingly, appending a `?url` to the end of the import stops the error from throwing:

`import styles from "~/styles/global.css?url";`

**Comment by markdalgleish** [comment]
Importing CSS via `import styles from "./styles.css"` has been deprecated in Vite in favour of providing an explicit query string denoting what you're trying to import. In your case, `?url` is what you want.

**Comment by amanape** [comment]
Nowhere in the documentation does it mention that. Maybe its worth updating it since Remix is finishing moving to Vite

**Comment by GOWxx** [comment]
> Nowhere in the documentation does it mention that. Maybe its worth updating it since Remix is finishing moving to Vite文档中没有提到这一点。也许值得更新，因为Remix正在完成迁移到Vite。

it is mentioned at https://remix.run/docs/en/main/future/vite#fix-up-css-imports-referenced-in-links, maybe not very obvious

> `.css?url` imports require Vite v5.1 or newer

```diff
-import styles from "~/styles/dashboard.css";
+import styles from "~/styles/dashboard.css?url";

export const links = () => {
  return [
    { rel: "stylesheet", href: styles }
  ];
}
```
