### ISSUE TITLE
Hydration issues in prod builds of Cloudflare starter template

### ISSUE THREAD

**Issue by commscheck** [remix-run/remix#9268]
### Reproduction

1. Create a new project using the cloudflare template:

```sh
pnpm create remix@latest my-project \
  --template remix-run/remix/templates/cloudflare \
  --yes
```

2. Build the new project for production:
```sh
pnpm run build
```

3. Start the production build locally with wrangler, or deploy to Cloudflare Pages:
```sh
pnpm run start
# or
pnpm run deploy
```

4. Open the printed URL.

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 192.39 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.15.4 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.61
    Safari: 17.2.1
  npmPackages:
    @remix-run/cloudflare: ^2.8.1 => 2.8.1 
    @remix-run/cloudflare-pages: ^2.8.1 => 2.8.1 
    @remix-run/dev: ^2.8.1 => 2.8.1 
    @remix-run/react: ^2.8.1 => 2.8.1 
    vite: ^5.1.0 => 5.2.10
```

### Used Package Manager

pnpm

### Expected Behavior

The page successfully loads with "Welcome to Remix (with Vite and Cloudflare)", and no errors in the dev tools console.

### Actual Behavior

The page contents is visible for a split second then disappears, leaving a blank white page.

The dev console contains logs like these:

```
entry.client-Vg7GJ-yF.js:10 Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Yo (components-Ij9FTKIE.js:22:4797)
    at bf (components-Ij9FTKIE.js:24:45467)
    at Gf (components-Ij9FTKIE.js:24:39676)
    at Hh (components-Ij9FTKIE.js:24:39648)
    at Yf (components-Ij9FTKIE.js:24:34654)
    at L (components-Ij9FTKIE.js:9:1569)
    at MessagePort.ce (components-Ij9FTKIE.js:9:1938)
z @ entry.client-Vg7GJ-yF.js:10
```
```
components-Ij9FTKIE.js:24 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at bf (components-Ij9FTKIE.js:24:45126)
    at Gf (components-Ij9FTKIE.js:24:39676)
    at $h (components-Ij9FTKIE.js:24:39604)
    at gi (components-Ij9FTKIE.js:24:39458)
    at sa (components-Ij9FTKIE.js:24:35840)
    at Yf (components-Ij9FTKIE.js:24:34791)
    at L (components-Ij9FTKIE.js:9:1569)
    at MessagePort.ce (components-Ij9FTKIE.js:9:1938)
```
Full log file: [localhost-1713682540919.log](https://github.com/remix-run/remix/files/15050948/localhost-1713682540919.log)

This issue doesn't happen when running in dev mode with `remix vite:dev`.

**Comment by huijiewei** [comment]
override rollup to 4.15.0, this is rollup issue.

**Comment by commscheck** [comment]
> override rollup to 4.15.0, this is rollup issue.

@huijiewei that worked, thank you!

**Comment by alexmartinezm** [comment]
> override rollup to 4.15.0, this is rollup issue.

Hey there, experiencing the same issue. Sorry asking but, what do you mean by "rollup to 4.15.0".

Thanks in advance!
