### ISSUE TITLE
Firestore Lite Does Not Work in Loader

### ISSUE THREAD

**Issue by jdgamble555** [remix-run/remix#9285]
### Reproduction

Here is the test repo (need to add any Firebase credentials and query any firebase document):

https://github.com/jdgamble555/remix-firebase-test/blob/master/app/lib/about.server.ts

https://github.com/jdgamble555/remix-firebase-test

The test deployed version (deployed working without Lite):

https://remix-firebase-test.vercel.app/

### System Info

```shell
Firebase: 10.11.0

Remix: 2.8.1
```

### Used Package Manager

npm

### Expected Behavior

Remix will resolver a firebase document as expected when loading `firebase/firestore`. However, when loading the `lite` version, which uses REST API, it will never get resolved.

You can test this by changing the path to use Firestore Lite to `firebase/firestore/lite` in the 

https://github.com/jdgamble555/remix-firebase-test/blob/master/app/lib/about.server.ts.

### Actual Behavior

It does not get Resolved. I submitted a bug report to Firebase. Firebase says this is a Remix problem.

https://github.com/firebase/firebase-js-sdk/issues/8195

Also probably related to:
https://github.com/firebase/firebase-js-sdk/issues/7911

J

**Comment by RafalFilipek** [comment]
This doesn't appear to be an issue in Remix. Will it work if you put this logic in a simple Node.js script? 

This will help us eliminate issues in `firebase/firestore/lite`.

**Comment by jdgamble555** [comment]
Yes, I have built the same app in NextJS.

https://github.com/jdgamble555/nextjs-firebase-todo/blob/master/lib/about.ts

The Firestore Teams seems to think this is a Remix problem:

https://github.com/firebase/firebase-js-sdk/issues/8195

J

**Comment by jdgamble555** [comment]
This is definitely a remix issue. When I add the `unstable_singleFetch: true` flag, the Firestore runtime actually resolves with the correct information (it would not resolve at all before). However, now I get this error:
```
TypeError: headers.getSetCookie is not a function or its return value is not iterable
    at proxyResponseToResponseStub (C:\web projects\remix-firebase-test\node_modules\@remix-run\server-runtime\dist\single-fetch.js:292:25)
    at C:\web projects\remix-firebase-test\node_modules\@remix-run\server-runtime\dist\single-fetch.js:61:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async C:\web projects\remix-firebase-test\node_modules\@remix-run\server-runtime\dist\single-fetch.js:39:19
    at async callDataStrategyImpl (C:\web projects\remix-firebase-test\node_modules\@remix-run\router\dist\router.cjs.js:4169:17)
    at async callDataStrategy (C:\web projects\remix-firebase-test\node_modules\@remix-run\router\dist\router.cjs.js:3702:19)
    at async loadRouteData (C:\web projects\remix-firebase-test\node_modules\@remix-run\router\dist\router.cjs.js:3677:19)
    at async queryImpl (C:\web projects\remix-firebase-test\node_modules\@remix-run\router\dist\router.cjs.js:3522:20)
    at async Object.query (C:\web projects\remix-firebase-test\node_modules\@remix-run\router\dist\router.cjs.js:3416:18)
    at async Object.singleFetchLoaders (C:\web projects\remix-firebase-test\node_modules\@remix-run\server-runtime\dist\single-fetch.js:161:18)
    at async handleSingleFetchRequest (C:\web projects\remix-firebase-test\node_modules\@remix-run\server-runtime\dist\server.js:203:146)
    at async requestHandler (C:\web projects\remix-firebase-test\node_modules\@remix-run\server-runtime\dist\server.js:114:18)
    at async nodeHandler (C:\web projects\remix-firebase-test\node_modules\@remix-run\dev\dist\vite\plugin.js:844:27)
    at async C:\web projects\remix-firebase-test\node_modules\@remix-run\dev\dist\vite\plugin.js:847:15
```

J

**Comment by amaany3** [comment]
@jdgamble555 
Please try enabling nativeFetch on this line

```
installGlobals({ nativeFetch: true });
```

https://github.com/jdgamble555/remix-firebase-test/blob/master/vite.config.ts#L6

same issue: https://github.com/remix-run/remix/issues/9324

**Comment by jdgamble555** [comment]
It looks like that fixed it!  Shouldn't this be the default?

J

**Comment by brophdawg11** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2. If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.

We plan to continue to address 2 types of issues in Remix v2:

- Bugs that pose security concerns
- Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so:

- If this is a bug, please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new [minimal reproduction](https://reactrouter.com/new) against v7
- If this is a feature request, please open a new [Proposal Discussion](https://github.com/remix-run/react-router/discussions/new?category=proposals) in React Router, and if it gets enough community support it can be considered for implementation

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
