### ISSUE TITLE
Dev mode not working (for SPA) with base/basename set to "/app/"

### ISSUE THREAD

**Issue by brophdawg11** [remix-run/remix#9382]
### Discussed in https://github.com/remix-run/remix/discussions/9375

<div type='discussions-op-text'>

<sup>Originally posted by **dimw** May  4, 2024</sup>
I'm trying to run an SPA with the base set to `/app/`. Therefore, I'm following the [Remix' SPA Mode doc](https://remix.run/docs/en/main/guides/spa-mode) as well as the [Deploying Remix to GitHub Pages tutorial](https://youtu.be/EO_-KwSslWQ?t=451) from @brookslybrand.

The steps are:
1. Bootstrapping a project from a template:
   ```sh
   npx create-remix@latest --template remix-run/remix/templates/spa spa-test
   ```
2. Changing the `base` and `basename` to `/app/` (to make accessible the SPA from http://example.com/app/):
   ```ts
   // vite.config.ts
   export default defineConfig({
     base: "/app/",   // <-- This line is new
     plugins: [
       remix({
         ssr: false,
         basename: "/app/",  // <-- This line is new
       }),
       tsconfigPaths(),
     ],
   });

When I now build (`npm run build`) and execute the preview (`npm run preview`), the page is working as expected under http://localhost:4173/app/.

### Issue
However, when running in the dev mode (`npm run dev`) and opening the provided URL (http://localhost:5173/app/), the dev server retrieves an internal server error while I'm seeing the following error messages on the console.
```shell
[vite] Pre-transform error: Failed to load url /root.tsx (resolved id: /root.tsx) in virtual:remix/server-build. Does the file exist?
[vite] Pre-transform error: Failed to load url /routes/foo.tsx (resolved id: /routes/foo.tsx) in virtual:remix/server-build. Does the file exist?
[vite] Pre-transform error: Failed to load url /routes/_index.tsx (resolved id: /routes/_index.tsx) in virtual:remix/server-build. Does the file exist?
[vite] Error when evaluating SSR module virtual:remix/server-build: failed to import "/root.tsx"
|- Error: Failed to load url /root.tsx (resolved id: /root.tsx) in virtual:remix/server-build. Does the file exist?
    at loadAndTransform (file:///<redacted>/spa-test/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:53884:21)
    at async instantiateModule (file:///<redacted>/spa-test/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:54954:10)

[vite] Internal server error: Failed to load url /root.tsx (resolved id: /root.tsx) in virtual:remix/server-build. Does the file exist?
```

The same error is happening with _dev_ when a regular Remix app (with SSR enabled) is used.

I tried to remove the Vite [`base` option](https://vitejs.dev/config/shared-options.html#base) but this leads to assets being loaded from the root instead of `/app/`. This would require more effort in server config when bringing the app to a server and I would like to avoid that.

<img width="857" alt="image" src="https://github.com/remix-run/remix/assets/2025688/d78fc3b0-33cd-4236-9c31-a1616dde1dce">

### Workaround
For now, I ended up having two Vite configurations:
- Default (dev) config (_vite.config.ts_) with no `base` set
- Build config (_vite.config.build.ts) which is extending the default config and setting the `base` on top:
   ```ts
   // vite.config.build.ts
   export default mergeConfig(defaultConfig, {
     base: "/app/",
   });
   ```
   Which is then executed from _package.json_ as following:
   ```js
   {
     "scripts": {
       "build": "remix vite:build --config ./vite.config.build.ts",
       // ...
     }
   }
   ```

Does anyone have a hint what I'm missing here in the Vite config or is that a bug?

**Versions**
- @remix-run/dev: 2.9.1
- vite: 5.1.0

**Related to**
- https://github.com/remix-run/remix/pull/8145
</div>

**Comment by brophdawg11** [comment]
Thank you for opening this issue, and our apologies we haven't gotten around to it yet!

With the release of [React Router v7](https://remix.run/blog/react-router-v7) we are sun-setting continued development/maintenance on Remix v2. If you have not already [upgraded to React Router v7](https://reactrouter.com/upgrading/remix), we recommend you do so. We've tried to make the upgrade process as smooth as possible with our [Future Flags](https://remix.run/docs/en/main/start/future-flags). We are now in the process of cleaning up outdated issues and pull requests to improve the overall hygiene of our repositories.

We plan to continue to address 2 types of issues in Remix v2:

- Bugs that pose security concerns
- Bugs that prevent upgrading to React Router v7

If you believe this issue meets one of those criteria, please respond or [create a new issue](https://github.com/remix-run/remix/issues/new?template=bug_report.yml).

For all other issues, ongoing maintenance will be happening in React Router v7, so:

- If this is a bug, please reopen this issue [in that repo](https://github.com/remix-run/react-router/issues/new?template=bug_report.yml) with a new [minimal reproduction](https://reactrouter.com/new) against v7
- If this is a feature request, please open a new [Proposal Discussion](https://github.com/remix-run/react-router/discussions/new?category=proposals) in React Router, and if it gets enough community support it can be considered for implementation

If you have any questions you can always reach out on [Discord](https://rmx.as/discord). Thanks again for providing feedback and helping us make our framework even better!
